#!/usr/bin/env bash
#
# WP-21: generate the down-call wrappers from the import inventory.
#
# Reads cygwin-imports.tsv and writes two artifacts, both committed and both
# reproduced byte for byte by a rerun:
#
#   wrappers.gen.c   one ms_abi forwarding thunk per imported function.
#   wrappers.gen.h   one ms_abi declaration per thunk, the boundary symbols.
#
# The thunk. Every call the runtime makes down into Windows crosses from the
# System V ABI the runtime is compiled to into the Microsoft ABI ntdll and
# kernel32 are compiled to. WP-21's rule is that no System V-side code names an
# import; it names a wrapper, and the wrapper is the one place the raw import
# is referenced. A thunk is
#
#   __attribute__((ms_abi)) void w_NtClose(void)
#   { __asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtClose)); }
#
# It receives an MS-ABI call -- the compiler emits the System V to MS shuffle
# at the runtime's call site, from the ms_abi prototype the caller declares --
# and tail-jumps through the import's address slot to the real function, MS ABI
# to MS ABI, touching neither the arguments nor the stack. Because it repacks
# nothing it is correct for any arity and any argument types without the thunk
# ever knowing the signature; the typed prototype belongs to whoever calls the
# wrapper, which is WP-22 as it consumes each import. The single indirect jump
# is the entire boundary, and it is mechanical: one line, generated, per import.
#
# gcc 7.4.0 ignores __attribute__((naked)) on x86_64, so the thunk is a plain
# ms_abi function whose only statement is the asm jump; at -O2 the compiler
# emits no prologue and no epilogue, which the reproduce test verifies by
# disassembly rather than trusting. A frame would break the tail jump, so the
# test treats its appearance as a failure.
#
# Variadic imports are refused here rather than forwarded. A generic thunk
# cannot bridge a variadic call -- a System V va_list is a twenty-four-byte
# descriptor and Microsoft's is an eight-byte pointer, and repacking is exactly
# what this thunk does not do -- so a variadic import is WP-24's, and the
# generator aborts if the inventory carries one, naming it. Today none do.
#
# Usage:
#   gen-wrappers.sh [options]
#
# Options:
#   -i FILE, --inventory=FILE   import inventory TSV. [default: cygwin-imports.tsv]
#   --c=FILE                    thunk output. [default: wrappers.gen.c]
#   --h=FILE                    header output. [default: wrappers.gen.h]
#   -V, --version               Print the version and exit.
#   -h, --help                  Print this message and exit.

set -u

prog=gen-wrappers
release='gen-wrappers 1.0'
here=$(cd "$(dirname "$0")" && pwd)

inventory=$here/cygwin-imports.tsv
out_c=$here/wrappers.gen.c
out_h=$here/wrappers.gen.h

usage() { awk '/^# Usage:/,/^[^#]/ { if ($0 ~ /^#/) print substr($0, 3) }' "$0"; }
die() { printf '%s: %s\n' "$prog" "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
	case $1 in
		-h|--help)       usage; exit 0 ;;
		-V|--version)    printf '%s\n' "$release"; exit 0 ;;
		-i|--inventory)  inventory=${2:-}; shift 2 ;;
		--inventory=*)   inventory=${1#*=}; shift ;;
		--c)             out_c=${2:-}; shift 2 ;;
		--c=*)           out_c=${1#*=}; shift ;;
		--h)             out_h=${2:-}; shift 2 ;;
		--h=*)           out_h=${1#*=}; shift ;;
		-?*)             printf '%s: unknown option %s\n' "$prog" "$1" >&2; exit 2 ;;
		*)               break ;;
	esac
done
[ -f "$inventory" ] || die "no inventory at $inventory"

# Validate the inventory shape and refuse variadic imports up front, so a
# malformed row fails the generation rather than producing a malformed thunk.
awk -F'\t' -v prog="$prog" '
	NF != 3 { printf "%s: line %d: want 3 fields, got %d: %s\n", prog, NR, NF, $0 > "/dev/stderr"; bad=1; next }
	$3 != "yes" && $3 != "no" { printf "%s: line %d: bad variadic flag %s\n", prog, NR, $3 > "/dev/stderr"; bad=1; next }
	$3 == "yes" { printf "%s: %s is variadic; that is WP-24, not a generated wrapper\n", prog, $2 > "/dev/stderr"; bad=1 }
	END { if (bad) exit 3 }
' "$inventory" || die "inventory rejected"

count=$(wc -l < "$inventory" | tr -d ' ')

# The header. Symbol declarations, ms_abi, one per import. This fixes the set
# of wrapper symbols and their ABI; it is not the typed call interface, which
# the consumer writes per function. It is what the audit and the smoke test
# read to know exactly which symbols must exist.
{
	printf '/* Generated by gen-wrappers.sh from cygwin-imports.tsv. Do not edit. */\n'
	printf '/* WP-21 down-call wrappers: the ms_abi boundary symbols, one per import. */\n'
	printf '#ifndef ELFSYSV_RUNTIME_IMPORTS_WRAPPERS_GEN_H\n'
	printf '#define ELFSYSV_RUNTIME_IMPORTS_WRAPPERS_GEN_H\n\n'
	printf '/* Each w_<Name> is the down-call boundary for one Windows import: an\n'
	printf '   ms_abi symbol the System V runtime calls in place of the raw import, so\n'
	printf '   the import is named in exactly one place. The prototype is opaque here;\n'
	printf '   the caller (WP-22) declares the real one as it consumes each import. */\n\n'
	printf '#ifdef __cplusplus\nextern "C" {\n#endif\n\n'
	while IFS=$'\t' read -r dll sym var; do
		printf '__attribute__((ms_abi)) void w_%s(void);\n' "$sym"
	done < "$inventory"
	printf '\n#ifdef __cplusplus\n}\n#endif\n\n'
	printf '#endif /* ELFSYSV_RUNTIME_IMPORTS_WRAPPERS_GEN_H */\n'
} > "$out_h" || die "cannot write $out_h"

# The thunks. One ms_abi tail-jump per import, plus the import address slot it
# jumps through. __imp_<Name> is the PE convention for the import's address
# table entry; the real slot is provided by the loader at run time, and for a
# standalone compile it is an undefined extern, which -c leaves unresolved.
{
	printf '/* Generated by gen-wrappers.sh from cygwin-imports.tsv. Do not edit. */\n'
	printf '/* WP-21 down-call wrappers: one ms_abi forwarding thunk per import. */\n'
	printf '/*\n'
	printf ' * Each thunk receives an MS-ABI call and tail-jumps through the import'"'"'s\n'
	printf ' * address slot to the real Windows function, repacking nothing, so it is\n'
	printf ' * correct for any signature. The System V to MS translation is emitted by\n'
	printf ' * the compiler at the caller'"'"'s site, from the ms_abi prototype the caller\n'
	printf ' * declares; this file is the one place a raw import is named.\n'
	printf ' */\n\n'
	while IFS=$'\t' read -r dll sym var; do
		printf 'extern void *__imp_%s;\n' "$sym"
	done < "$inventory"
	printf '\n'
	while IFS=$'\t' read -r dll sym var; do
		printf '__attribute__((ms_abi)) void w_%s(void)\n' "$sym"
		printf '{\n'
		printf '\t__asm__ __volatile__ ("jmp *%%0" : : "m"(__imp_%s));\n' "$sym"
		printf '}\n\n'
	done < "$inventory"
} > "$out_c" || die "cannot write $out_c"

printf '%s: wrote %s and %s, %s wrappers\n' "$prog" \
	"$(basename "$out_c")" "$(basename "$out_h")" "$count" >&2
