/* Generated by gen-wrappers.sh from cygwin-imports.tsv. Do not edit. */
/* WP-21 down-call wrappers: one ms_abi forwarding thunk per import. */
/*
 * Each thunk receives an MS-ABI call and tail-jumps through the import's
 * address slot to the real Windows function, repacking nothing, so it is
 * correct for any signature. The System V to MS translation is emitted by
 * the compiler at the caller's site, from the ms_abi prototype the caller
 * declares; this file is the one place a raw import is named.
 */

extern void *__imp_AcquireSRWLockExclusive;
extern void *__imp_AcquireSRWLockShared;
extern void *__imp_AddVectoredContinueHandler;
extern void *__imp_AddVectoredExceptionHandler;
extern void *__imp_AllocConsole;
extern void *__imp_AttachConsole;
extern void *__imp_CallNamedPipeA;
extern void *__imp_CancelIo;
extern void *__imp_CancelSynchronousIo;
extern void *__imp_ClearCommBreak;
extern void *__imp_ClearCommError;
extern void *__imp_CloseHandle;
extern void *__imp_CompareStringEx;
extern void *__imp_ConnectNamedPipe;
extern void *__imp_CreateFileA;
extern void *__imp_CreateFileW;
extern void *__imp_CreateNamedPipeA;
extern void *__imp_CreatePipe;
extern void *__imp_CreateProcessW;
extern void *__imp_CreateRemoteThread;
extern void *__imp_CreateSymbolicLinkW;
extern void *__imp_CreateTapePartition;
extern void *__imp_CreateThread;
extern void *__imp_DebugBreak;
extern void *__imp_DeleteCriticalSection;
extern void *__imp_DeleteProcThreadAttributeList;
extern void *__imp_DeviceIoControl;
extern void *__imp_DisconnectNamedPipe;
extern void *__imp_DuplicateHandle;
extern void *__imp_EnterCriticalSection;
extern void *__imp_EnumSystemLocalesEx;
extern void *__imp_EraseTape;
extern void *__imp_EscapeCommFunction;
extern void *__imp_ExitProcess;
extern void *__imp_ExitThread;
extern void *__imp_ExpandEnvironmentStringsW;
extern void *__imp_FillConsoleOutputAttribute;
extern void *__imp_FillConsoleOutputCharacterW;
extern void *__imp_FindFirstVolumeW;
extern void *__imp_FindNextVolumeW;
extern void *__imp_FindVolumeClose;
extern void *__imp_FlushConsoleInputBuffer;
extern void *__imp_FlushFileBuffers;
extern void *__imp_FlushViewOfFile;
extern void *__imp_FoldStringW;
extern void *__imp_FreeConsole;
extern void *__imp_FreeEnvironmentStringsW;
extern void *__imp_FreeLibrary;
extern void *__imp_GenerateConsoleCtrlEvent;
extern void *__imp_GetBinaryTypeW;
extern void *__imp_GetCommModemStatus;
extern void *__imp_GetCommState;
extern void *__imp_GetCommandLineW;
extern void *__imp_GetConsoleCP;
extern void *__imp_GetConsoleCursorInfo;
extern void *__imp_GetConsoleMode;
extern void *__imp_GetConsoleOutputCP;
extern void *__imp_GetConsoleProcessList;
extern void *__imp_GetConsoleScreenBufferInfo;
extern void *__imp_GetConsoleWindow;
extern void *__imp_GetCurrentConsoleFontEx;
extern void *__imp_GetCurrentProcess;
extern void *__imp_GetCurrentProcessId;
extern void *__imp_GetCurrentProcessorNumberEx;
extern void *__imp_GetCurrentThread;
extern void *__imp_GetCurrentThreadId;
extern void *__imp_GetEnvironmentStringsW;
extern void *__imp_GetEnvironmentVariableA;
extern void *__imp_GetEnvironmentVariableW;
extern void *__imp_GetExitCodeProcess;
extern void *__imp_GetFileAttributesA;
extern void *__imp_GetFileSize;
extern void *__imp_GetFileSizeEx;
extern void *__imp_GetFileType;
extern void *__imp_GetFinalPathNameByHandleW;
extern void *__imp_GetHandleInformation;
extern void *__imp_GetLastError;
extern void *__imp_GetLocaleInfoEx;
extern void *__imp_GetLogicalDriveStringsA;
extern void *__imp_GetLogicalDriveStringsW;
extern void *__imp_GetLogicalProcessorInformationEx;
extern void *__imp_GetModuleFileNameW;
extern void *__imp_GetModuleHandleA;
extern void *__imp_GetModuleHandleExA;
extern void *__imp_GetModuleHandleExW;
extern void *__imp_GetNamedPipeClientProcessId;
extern void *__imp_GetNumberOfConsoleInputEvents;
extern void *__imp_GetOverlappedResult;
extern void *__imp_GetPriorityClass;
extern void *__imp_GetProcAddress;
extern void *__imp_GetProcessAffinityMask;
extern void *__imp_GetProcessGroupAffinity;
extern void *__imp_GetProcessHeap;
extern void *__imp_GetProcessId;
extern void *__imp_GetProcessWorkingSetSize;
extern void *__imp_GetStartupInfoA;
extern void *__imp_GetStdHandle;
extern void *__imp_GetSystemDirectoryW;
extern void *__imp_GetSystemInfo;
extern void *__imp_GetSystemTimeAsFileTime;
extern void *__imp_GetSystemTimePreciseAsFileTime;
extern void *__imp_GetSystemWindowsDirectoryW;
extern void *__imp_GetTapeParameters;
extern void *__imp_GetTapePosition;
extern void *__imp_GetTapeStatus;
extern void *__imp_GetTempPathW;
extern void *__imp_GetThreadContext;
extern void *__imp_GetThreadGroupAffinity;
extern void *__imp_GetThreadId;
extern void *__imp_GetThreadPriority;
extern void *__imp_GetTickCount;
extern void *__imp_GetTickCount64;
extern void *__imp_GetTimeZoneInformation;
extern void *__imp_GetVolumeNameForVolumeMountPointW;
extern void *__imp_GetVolumePathNamesForVolumeNameW;
extern void *__imp_GlobalAlloc;
extern void *__imp_GlobalLock;
extern void *__imp_GlobalMemoryStatusEx;
extern void *__imp_GlobalSize;
extern void *__imp_GlobalUnlock;
extern void *__imp_HeapAlloc;
extern void *__imp_HeapCreate;
extern void *__imp_HeapDestroy;
extern void *__imp_HeapFree;
extern void *__imp_IdnToAscii;
extern void *__imp_IdnToUnicode;
extern void *__imp_InitializeCriticalSection;
extern void *__imp_InitializeProcThreadAttributeList;
extern void *__imp_IsDebuggerPresent;
extern void *__imp_IsProcessInJob;
extern void *__imp_K32EnumProcessModules;
extern void *__imp_K32GetModuleInformation;
extern void *__imp_LCMapStringEx;
extern void *__imp_LeaveCriticalSection;
extern void *__imp_LoadLibraryExA;
extern void *__imp_LoadLibraryExW;
extern void *__imp_LoadLibraryW;
extern void *__imp_LocalFree;
extern void *__imp_MapViewOfFile;
extern void *__imp_MapViewOfFileEx;
extern void *__imp_MultiByteToWideChar;
extern void *__imp_OpenProcess;
extern void *__imp_OpenThread;
extern void *__imp_OutputDebugStringA;
extern void *__imp_PeekConsoleInputA;
extern void *__imp_PeekConsoleInputW;
extern void *__imp_PeekNamedPipe;
extern void *__imp_PrefetchVirtualMemory;
extern void *__imp_PrepareTape;
extern void *__imp_PurgeComm;
extern void *__imp_QueryDosDeviceW;
extern void *__imp_QueryInformationJobObject;
extern void *__imp_QueryPerformanceCounter;
extern void *__imp_QueryPerformanceFrequency;
extern void *__imp_QueryUnbiasedInterruptTime;
extern void *__imp_QueueUserAPC;
extern void *__imp_RaiseException;
extern void *__imp_ReadConsoleInputA;
extern void *__imp_ReadConsoleInputW;
extern void *__imp_ReadConsoleOutputW;
extern void *__imp_ReadFile;
extern void *__imp_ReadProcessMemory;
extern void *__imp_ReleaseMutex;
extern void *__imp_ReleaseSRWLockExclusive;
extern void *__imp_ReleaseSRWLockShared;
extern void *__imp_ReleaseSemaphore;
extern void *__imp_RemoveVectoredExceptionHandler;
extern void *__imp_ResetEvent;
extern void *__imp_ResolveLocaleName;
extern void *__imp_ResumeThread;
extern void *__imp_RtlCaptureContext;
extern void *__imp_RtlLookupFunctionEntry;
extern void *__imp_RtlRestoreContext;
extern void *__imp_RtlUnwindEx;
extern void *__imp_RtlVirtualUnwind;
extern void *__imp_ScrollConsoleScreenBufferA;
extern void *__imp_ScrollConsoleScreenBufferW;
extern void *__imp_SetCommBreak;
extern void *__imp_SetCommMask;
extern void *__imp_SetCommState;
extern void *__imp_SetCommTimeouts;
extern void *__imp_SetComputerNameExW;
extern void *__imp_SetConsoleCP;
extern void *__imp_SetConsoleCtrlHandler;
extern void *__imp_SetConsoleCursorInfo;
extern void *__imp_SetConsoleCursorPosition;
extern void *__imp_SetConsoleMode;
extern void *__imp_SetConsoleOutputCP;
extern void *__imp_SetConsoleTextAttribute;
extern void *__imp_SetConsoleTitleW;
extern void *__imp_SetConsoleWindowInfo;
extern void *__imp_SetEnvironmentVariableW;
extern void *__imp_SetErrorMode;
extern void *__imp_SetEvent;
extern void *__imp_SetFilePointerEx;
extern void *__imp_SetHandleInformation;
extern void *__imp_SetLastError;
extern void *__imp_SetNamedPipeHandleState;
extern void *__imp_SetPriorityClass;
extern void *__imp_SetProcessAffinityMask;
extern void *__imp_SetProcessWorkingSetSize;
extern void *__imp_SetStdHandle;
extern void *__imp_SetSystemTime;
extern void *__imp_SetTapeParameters;
extern void *__imp_SetTapePosition;
extern void *__imp_SetThreadContext;
extern void *__imp_SetThreadGroupAffinity;
extern void *__imp_SetThreadPriority;
extern void *__imp_SetThreadStackGuarantee;
extern void *__imp_Sleep;
extern void *__imp_SuspendThread;
extern void *__imp_SwitchToThread;
extern void *__imp_TerminateProcess;
extern void *__imp_TerminateThread;
extern void *__imp_TlsAlloc;
extern void *__imp_TlsFree;
extern void *__imp_TlsGetValue;
extern void *__imp_TlsSetValue;
extern void *__imp_TransmitCommChar;
extern void *__imp_UnmapViewOfFile;
extern void *__imp_UpdateProcThreadAttribute;
extern void *__imp_VirtualAlloc;
extern void *__imp_VirtualFree;
extern void *__imp_VirtualProtect;
extern void *__imp_VirtualProtectEx;
extern void *__imp_VirtualQuery;
extern void *__imp_VirtualQueryEx;
extern void *__imp_WaitCommEvent;
extern void *__imp_WaitForMultipleObjects;
extern void *__imp_WaitForSingleObject;
extern void *__imp_WaitNamedPipeW;
extern void *__imp_WideCharToMultiByte;
extern void *__imp_WriteConsoleInputW;
extern void *__imp_WriteConsoleOutputW;
extern void *__imp_WriteConsoleW;
extern void *__imp_WriteFile;
extern void *__imp_WriteProcessMemory;
extern void *__imp_WriteTapemark;
extern void *__imp_NtAccessCheck;
extern void *__imp_NtAdjustPrivilegesToken;
extern void *__imp_NtAllocateLocallyUniqueId;
extern void *__imp_NtAssignProcessToJobObject;
extern void *__imp_NtCancelTimer;
extern void *__imp_NtClose;
extern void *__imp_NtCommitTransaction;
extern void *__imp_NtCreateDirectoryObject;
extern void *__imp_NtCreateEvent;
extern void *__imp_NtCreateFile;
extern void *__imp_NtCreateJobObject;
extern void *__imp_NtCreateKey;
extern void *__imp_NtCreateMutant;
extern void *__imp_NtCreateNamedPipeFile;
extern void *__imp_NtCreateSection;
extern void *__imp_NtCreateSemaphore;
extern void *__imp_NtCreateSymbolicLinkObject;
extern void *__imp_NtCreateTimer;
extern void *__imp_NtCreateTransaction;
extern void *__imp_NtDuplicateToken;
extern void *__imp_NtFlushBuffersFile;
extern void *__imp_NtFsControlFile;
extern void *__imp_NtLockFile;
extern void *__imp_NtLockVirtualMemory;
extern void *__imp_NtMapViewOfSection;
extern void *__imp_NtOpenDirectoryObject;
extern void *__imp_NtOpenEvent;
extern void *__imp_NtOpenFile;
extern void *__imp_NtOpenJobObject;
extern void *__imp_NtOpenKey;
extern void *__imp_NtOpenMutant;
extern void *__imp_NtOpenProcessToken;
extern void *__imp_NtOpenSection;
extern void *__imp_NtOpenSemaphore;
extern void *__imp_NtOpenSymbolicLinkObject;
extern void *__imp_NtOpenThreadToken;
extern void *__imp_NtPrivilegeCheck;
extern void *__imp_NtQueryAttributesFile;
extern void *__imp_NtQueryDirectoryFile;
extern void *__imp_NtQueryDirectoryObject;
extern void *__imp_NtQueryEaFile;
extern void *__imp_NtQueryEvent;
extern void *__imp_NtQueryInformationFile;
extern void *__imp_NtQueryInformationJobObject;
extern void *__imp_NtQueryInformationProcess;
extern void *__imp_NtQueryInformationThread;
extern void *__imp_NtQueryInformationToken;
extern void *__imp_NtQueryObject;
extern void *__imp_NtQueryQuotaInformationFile;
extern void *__imp_NtQuerySecurityObject;
extern void *__imp_NtQuerySemaphore;
extern void *__imp_NtQuerySymbolicLinkObject;
extern void *__imp_NtQuerySystemInformation;
extern void *__imp_NtQuerySystemTime;
extern void *__imp_NtQueryTimer;
extern void *__imp_NtQueryTimerResolution;
extern void *__imp_NtQueryValueKey;
extern void *__imp_NtQueryVirtualMemory;
extern void *__imp_NtQueryVolumeInformationFile;
extern void *__imp_NtReadFile;
extern void *__imp_NtRollbackTransaction;
extern void *__imp_NtSetEaFile;
extern void *__imp_NtSetEvent;
extern void *__imp_NtSetInformationFile;
extern void *__imp_NtSetInformationJobObject;
extern void *__imp_NtSetInformationThread;
extern void *__imp_NtSetInformationToken;
extern void *__imp_NtSetQuotaInformationFile;
extern void *__imp_NtSetSecurityObject;
extern void *__imp_NtSetTimer;
extern void *__imp_NtSetValueKey;
extern void *__imp_NtSetVolumeInformationFile;
extern void *__imp_NtUnlockFile;
extern void *__imp_NtUnlockVirtualMemory;
extern void *__imp_NtUnmapViewOfSection;
extern void *__imp_NtWaitForSingleObject;
extern void *__imp_NtWriteFile;
extern void *__imp_RtlAbsoluteToSelfRelativeSD;
extern void *__imp_RtlAddAccessAllowedAce;
extern void *__imp_RtlAddAccessAllowedAceEx;
extern void *__imp_RtlAddAccessDeniedAceEx;
extern void *__imp_RtlAllocateHeap;
extern void *__imp_RtlAppendUnicodeStringToString;
extern void *__imp_RtlAppendUnicodeToString;
extern void *__imp_RtlCheckRegistryKey;
extern void *__imp_RtlCompareUnicodeString;
extern void *__imp_RtlConvertSidToUnicodeString;
extern void *__imp_RtlCopySid;
extern void *__imp_RtlCopyUnicodeString;
extern void *__imp_RtlCreateAcl;
extern void *__imp_RtlCreateQueryDebugBuffer;
extern void *__imp_RtlCreateSecurityDescriptor;
extern void *__imp_RtlDestroyQueryDebugBuffer;
extern void *__imp_RtlDowncaseUnicodeString;
extern void *__imp_RtlEnterCriticalSection;
extern void *__imp_RtlEqualPrefixSid;
extern void *__imp_RtlEqualSid;
extern void *__imp_RtlEqualUnicodeString;
extern void *__imp_RtlFirstFreeAce;
extern void *__imp_RtlFreeHeap;
extern void *__imp_RtlFreeUnicodeString;
extern void *__imp_RtlGetAce;
extern void *__imp_RtlGetControlSecurityDescriptor;
extern void *__imp_RtlGetCurrentTransaction;
extern void *__imp_RtlGetDaclSecurityDescriptor;
extern void *__imp_RtlGetGroupSecurityDescriptor;
extern void *__imp_RtlGetNtVersionNumbers;
extern void *__imp_RtlGetOwnerSecurityDescriptor;
extern void *__imp_RtlGetVersion;
extern void *__imp_RtlIdentifierAuthoritySid;
extern void *__imp_RtlInitAnsiString;
extern void *__imp_RtlInitUnicodeString;
extern void *__imp_RtlInitializeSid;
extern void *__imp_RtlLeaveCriticalSection;
extern void *__imp_RtlLengthSid;
extern void *__imp_RtlNtStatusToDosError;
extern void *__imp_RtlPrefixUnicodeString;
extern void *__imp_RtlQueryProcessDebugInformation;
extern void *__imp_RtlQueryRegistryValues;
extern void *__imp_RtlSetControlSecurityDescriptor;
extern void *__imp_RtlSetCurrentDirectory_U;
extern void *__imp_RtlSetCurrentTransaction;
extern void *__imp_RtlSetDaclSecurityDescriptor;
extern void *__imp_RtlSetGroupSecurityDescriptor;
extern void *__imp_RtlSetOwnerSecurityDescriptor;
extern void *__imp_RtlSubAuthorityCountSid;
extern void *__imp_RtlSubAuthoritySid;
extern void *__imp_RtlUnicodeStringToAnsiString;
extern void *__imp_RtlUpcaseUnicodeChar;
extern void *__imp_RtlUpcaseUnicodeString;
extern void *__imp_RtlWaitOnAddress;
extern void *__imp_RtlWakeAddressSingle;

__attribute__((ms_abi)) void w_AcquireSRWLockExclusive(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_AcquireSRWLockExclusive));
}

__attribute__((ms_abi)) void w_AcquireSRWLockShared(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_AcquireSRWLockShared));
}

__attribute__((ms_abi)) void w_AddVectoredContinueHandler(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_AddVectoredContinueHandler));
}

__attribute__((ms_abi)) void w_AddVectoredExceptionHandler(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_AddVectoredExceptionHandler));
}

__attribute__((ms_abi)) void w_AllocConsole(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_AllocConsole));
}

__attribute__((ms_abi)) void w_AttachConsole(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_AttachConsole));
}

__attribute__((ms_abi)) void w_CallNamedPipeA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CallNamedPipeA));
}

__attribute__((ms_abi)) void w_CancelIo(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CancelIo));
}

__attribute__((ms_abi)) void w_CancelSynchronousIo(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CancelSynchronousIo));
}

__attribute__((ms_abi)) void w_ClearCommBreak(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ClearCommBreak));
}

__attribute__((ms_abi)) void w_ClearCommError(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ClearCommError));
}

__attribute__((ms_abi)) void w_CloseHandle(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CloseHandle));
}

__attribute__((ms_abi)) void w_CompareStringEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CompareStringEx));
}

__attribute__((ms_abi)) void w_ConnectNamedPipe(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ConnectNamedPipe));
}

__attribute__((ms_abi)) void w_CreateFileA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CreateFileA));
}

__attribute__((ms_abi)) void w_CreateFileW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CreateFileW));
}

__attribute__((ms_abi)) void w_CreateNamedPipeA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CreateNamedPipeA));
}

__attribute__((ms_abi)) void w_CreatePipe(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CreatePipe));
}

__attribute__((ms_abi)) void w_CreateProcessW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CreateProcessW));
}

__attribute__((ms_abi)) void w_CreateRemoteThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CreateRemoteThread));
}

__attribute__((ms_abi)) void w_CreateSymbolicLinkW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CreateSymbolicLinkW));
}

__attribute__((ms_abi)) void w_CreateTapePartition(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CreateTapePartition));
}

__attribute__((ms_abi)) void w_CreateThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_CreateThread));
}

__attribute__((ms_abi)) void w_DebugBreak(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_DebugBreak));
}

__attribute__((ms_abi)) void w_DeleteCriticalSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_DeleteCriticalSection));
}

__attribute__((ms_abi)) void w_DeleteProcThreadAttributeList(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_DeleteProcThreadAttributeList));
}

__attribute__((ms_abi)) void w_DeviceIoControl(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_DeviceIoControl));
}

__attribute__((ms_abi)) void w_DisconnectNamedPipe(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_DisconnectNamedPipe));
}

__attribute__((ms_abi)) void w_DuplicateHandle(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_DuplicateHandle));
}

__attribute__((ms_abi)) void w_EnterCriticalSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_EnterCriticalSection));
}

__attribute__((ms_abi)) void w_EnumSystemLocalesEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_EnumSystemLocalesEx));
}

__attribute__((ms_abi)) void w_EraseTape(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_EraseTape));
}

__attribute__((ms_abi)) void w_EscapeCommFunction(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_EscapeCommFunction));
}

__attribute__((ms_abi)) void w_ExitProcess(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ExitProcess));
}

__attribute__((ms_abi)) void w_ExitThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ExitThread));
}

__attribute__((ms_abi)) void w_ExpandEnvironmentStringsW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ExpandEnvironmentStringsW));
}

__attribute__((ms_abi)) void w_FillConsoleOutputAttribute(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FillConsoleOutputAttribute));
}

__attribute__((ms_abi)) void w_FillConsoleOutputCharacterW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FillConsoleOutputCharacterW));
}

__attribute__((ms_abi)) void w_FindFirstVolumeW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FindFirstVolumeW));
}

__attribute__((ms_abi)) void w_FindNextVolumeW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FindNextVolumeW));
}

__attribute__((ms_abi)) void w_FindVolumeClose(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FindVolumeClose));
}

__attribute__((ms_abi)) void w_FlushConsoleInputBuffer(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FlushConsoleInputBuffer));
}

__attribute__((ms_abi)) void w_FlushFileBuffers(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FlushFileBuffers));
}

__attribute__((ms_abi)) void w_FlushViewOfFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FlushViewOfFile));
}

__attribute__((ms_abi)) void w_FoldStringW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FoldStringW));
}

__attribute__((ms_abi)) void w_FreeConsole(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FreeConsole));
}

__attribute__((ms_abi)) void w_FreeEnvironmentStringsW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FreeEnvironmentStringsW));
}

__attribute__((ms_abi)) void w_FreeLibrary(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_FreeLibrary));
}

__attribute__((ms_abi)) void w_GenerateConsoleCtrlEvent(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GenerateConsoleCtrlEvent));
}

__attribute__((ms_abi)) void w_GetBinaryTypeW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetBinaryTypeW));
}

__attribute__((ms_abi)) void w_GetCommModemStatus(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetCommModemStatus));
}

__attribute__((ms_abi)) void w_GetCommState(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetCommState));
}

__attribute__((ms_abi)) void w_GetCommandLineW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetCommandLineW));
}

__attribute__((ms_abi)) void w_GetConsoleCP(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetConsoleCP));
}

__attribute__((ms_abi)) void w_GetConsoleCursorInfo(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetConsoleCursorInfo));
}

__attribute__((ms_abi)) void w_GetConsoleMode(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetConsoleMode));
}

__attribute__((ms_abi)) void w_GetConsoleOutputCP(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetConsoleOutputCP));
}

__attribute__((ms_abi)) void w_GetConsoleProcessList(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetConsoleProcessList));
}

__attribute__((ms_abi)) void w_GetConsoleScreenBufferInfo(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetConsoleScreenBufferInfo));
}

__attribute__((ms_abi)) void w_GetConsoleWindow(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetConsoleWindow));
}

__attribute__((ms_abi)) void w_GetCurrentConsoleFontEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetCurrentConsoleFontEx));
}

__attribute__((ms_abi)) void w_GetCurrentProcess(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetCurrentProcess));
}

__attribute__((ms_abi)) void w_GetCurrentProcessId(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetCurrentProcessId));
}

__attribute__((ms_abi)) void w_GetCurrentProcessorNumberEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetCurrentProcessorNumberEx));
}

__attribute__((ms_abi)) void w_GetCurrentThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetCurrentThread));
}

__attribute__((ms_abi)) void w_GetCurrentThreadId(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetCurrentThreadId));
}

__attribute__((ms_abi)) void w_GetEnvironmentStringsW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetEnvironmentStringsW));
}

__attribute__((ms_abi)) void w_GetEnvironmentVariableA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetEnvironmentVariableA));
}

__attribute__((ms_abi)) void w_GetEnvironmentVariableW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetEnvironmentVariableW));
}

__attribute__((ms_abi)) void w_GetExitCodeProcess(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetExitCodeProcess));
}

__attribute__((ms_abi)) void w_GetFileAttributesA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetFileAttributesA));
}

__attribute__((ms_abi)) void w_GetFileSize(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetFileSize));
}

__attribute__((ms_abi)) void w_GetFileSizeEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetFileSizeEx));
}

__attribute__((ms_abi)) void w_GetFileType(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetFileType));
}

__attribute__((ms_abi)) void w_GetFinalPathNameByHandleW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetFinalPathNameByHandleW));
}

__attribute__((ms_abi)) void w_GetHandleInformation(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetHandleInformation));
}

__attribute__((ms_abi)) void w_GetLastError(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetLastError));
}

__attribute__((ms_abi)) void w_GetLocaleInfoEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetLocaleInfoEx));
}

__attribute__((ms_abi)) void w_GetLogicalDriveStringsA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetLogicalDriveStringsA));
}

__attribute__((ms_abi)) void w_GetLogicalDriveStringsW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetLogicalDriveStringsW));
}

__attribute__((ms_abi)) void w_GetLogicalProcessorInformationEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetLogicalProcessorInformationEx));
}

__attribute__((ms_abi)) void w_GetModuleFileNameW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetModuleFileNameW));
}

__attribute__((ms_abi)) void w_GetModuleHandleA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetModuleHandleA));
}

__attribute__((ms_abi)) void w_GetModuleHandleExA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetModuleHandleExA));
}

__attribute__((ms_abi)) void w_GetModuleHandleExW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetModuleHandleExW));
}

__attribute__((ms_abi)) void w_GetNamedPipeClientProcessId(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetNamedPipeClientProcessId));
}

__attribute__((ms_abi)) void w_GetNumberOfConsoleInputEvents(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetNumberOfConsoleInputEvents));
}

__attribute__((ms_abi)) void w_GetOverlappedResult(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetOverlappedResult));
}

__attribute__((ms_abi)) void w_GetPriorityClass(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetPriorityClass));
}

__attribute__((ms_abi)) void w_GetProcAddress(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetProcAddress));
}

__attribute__((ms_abi)) void w_GetProcessAffinityMask(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetProcessAffinityMask));
}

__attribute__((ms_abi)) void w_GetProcessGroupAffinity(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetProcessGroupAffinity));
}

__attribute__((ms_abi)) void w_GetProcessHeap(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetProcessHeap));
}

__attribute__((ms_abi)) void w_GetProcessId(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetProcessId));
}

__attribute__((ms_abi)) void w_GetProcessWorkingSetSize(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetProcessWorkingSetSize));
}

__attribute__((ms_abi)) void w_GetStartupInfoA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetStartupInfoA));
}

__attribute__((ms_abi)) void w_GetStdHandle(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetStdHandle));
}

__attribute__((ms_abi)) void w_GetSystemDirectoryW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetSystemDirectoryW));
}

__attribute__((ms_abi)) void w_GetSystemInfo(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetSystemInfo));
}

__attribute__((ms_abi)) void w_GetSystemTimeAsFileTime(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetSystemTimeAsFileTime));
}

__attribute__((ms_abi)) void w_GetSystemTimePreciseAsFileTime(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetSystemTimePreciseAsFileTime));
}

__attribute__((ms_abi)) void w_GetSystemWindowsDirectoryW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetSystemWindowsDirectoryW));
}

__attribute__((ms_abi)) void w_GetTapeParameters(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetTapeParameters));
}

__attribute__((ms_abi)) void w_GetTapePosition(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetTapePosition));
}

__attribute__((ms_abi)) void w_GetTapeStatus(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetTapeStatus));
}

__attribute__((ms_abi)) void w_GetTempPathW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetTempPathW));
}

__attribute__((ms_abi)) void w_GetThreadContext(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetThreadContext));
}

__attribute__((ms_abi)) void w_GetThreadGroupAffinity(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetThreadGroupAffinity));
}

__attribute__((ms_abi)) void w_GetThreadId(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetThreadId));
}

__attribute__((ms_abi)) void w_GetThreadPriority(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetThreadPriority));
}

__attribute__((ms_abi)) void w_GetTickCount(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetTickCount));
}

__attribute__((ms_abi)) void w_GetTickCount64(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetTickCount64));
}

__attribute__((ms_abi)) void w_GetTimeZoneInformation(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetTimeZoneInformation));
}

__attribute__((ms_abi)) void w_GetVolumeNameForVolumeMountPointW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetVolumeNameForVolumeMountPointW));
}

__attribute__((ms_abi)) void w_GetVolumePathNamesForVolumeNameW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GetVolumePathNamesForVolumeNameW));
}

__attribute__((ms_abi)) void w_GlobalAlloc(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GlobalAlloc));
}

__attribute__((ms_abi)) void w_GlobalLock(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GlobalLock));
}

__attribute__((ms_abi)) void w_GlobalMemoryStatusEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GlobalMemoryStatusEx));
}

__attribute__((ms_abi)) void w_GlobalSize(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GlobalSize));
}

__attribute__((ms_abi)) void w_GlobalUnlock(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_GlobalUnlock));
}

__attribute__((ms_abi)) void w_HeapAlloc(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_HeapAlloc));
}

__attribute__((ms_abi)) void w_HeapCreate(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_HeapCreate));
}

__attribute__((ms_abi)) void w_HeapDestroy(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_HeapDestroy));
}

__attribute__((ms_abi)) void w_HeapFree(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_HeapFree));
}

__attribute__((ms_abi)) void w_IdnToAscii(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_IdnToAscii));
}

__attribute__((ms_abi)) void w_IdnToUnicode(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_IdnToUnicode));
}

__attribute__((ms_abi)) void w_InitializeCriticalSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_InitializeCriticalSection));
}

__attribute__((ms_abi)) void w_InitializeProcThreadAttributeList(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_InitializeProcThreadAttributeList));
}

__attribute__((ms_abi)) void w_IsDebuggerPresent(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_IsDebuggerPresent));
}

__attribute__((ms_abi)) void w_IsProcessInJob(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_IsProcessInJob));
}

__attribute__((ms_abi)) void w_K32EnumProcessModules(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_K32EnumProcessModules));
}

__attribute__((ms_abi)) void w_K32GetModuleInformation(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_K32GetModuleInformation));
}

__attribute__((ms_abi)) void w_LCMapStringEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_LCMapStringEx));
}

__attribute__((ms_abi)) void w_LeaveCriticalSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_LeaveCriticalSection));
}

__attribute__((ms_abi)) void w_LoadLibraryExA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_LoadLibraryExA));
}

__attribute__((ms_abi)) void w_LoadLibraryExW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_LoadLibraryExW));
}

__attribute__((ms_abi)) void w_LoadLibraryW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_LoadLibraryW));
}

__attribute__((ms_abi)) void w_LocalFree(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_LocalFree));
}

__attribute__((ms_abi)) void w_MapViewOfFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_MapViewOfFile));
}

__attribute__((ms_abi)) void w_MapViewOfFileEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_MapViewOfFileEx));
}

__attribute__((ms_abi)) void w_MultiByteToWideChar(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_MultiByteToWideChar));
}

__attribute__((ms_abi)) void w_OpenProcess(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_OpenProcess));
}

__attribute__((ms_abi)) void w_OpenThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_OpenThread));
}

__attribute__((ms_abi)) void w_OutputDebugStringA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_OutputDebugStringA));
}

__attribute__((ms_abi)) void w_PeekConsoleInputA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_PeekConsoleInputA));
}

__attribute__((ms_abi)) void w_PeekConsoleInputW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_PeekConsoleInputW));
}

__attribute__((ms_abi)) void w_PeekNamedPipe(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_PeekNamedPipe));
}

__attribute__((ms_abi)) void w_PrefetchVirtualMemory(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_PrefetchVirtualMemory));
}

__attribute__((ms_abi)) void w_PrepareTape(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_PrepareTape));
}

__attribute__((ms_abi)) void w_PurgeComm(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_PurgeComm));
}

__attribute__((ms_abi)) void w_QueryDosDeviceW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_QueryDosDeviceW));
}

__attribute__((ms_abi)) void w_QueryInformationJobObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_QueryInformationJobObject));
}

__attribute__((ms_abi)) void w_QueryPerformanceCounter(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_QueryPerformanceCounter));
}

__attribute__((ms_abi)) void w_QueryPerformanceFrequency(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_QueryPerformanceFrequency));
}

__attribute__((ms_abi)) void w_QueryUnbiasedInterruptTime(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_QueryUnbiasedInterruptTime));
}

__attribute__((ms_abi)) void w_QueueUserAPC(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_QueueUserAPC));
}

__attribute__((ms_abi)) void w_RaiseException(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RaiseException));
}

__attribute__((ms_abi)) void w_ReadConsoleInputA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ReadConsoleInputA));
}

__attribute__((ms_abi)) void w_ReadConsoleInputW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ReadConsoleInputW));
}

__attribute__((ms_abi)) void w_ReadConsoleOutputW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ReadConsoleOutputW));
}

__attribute__((ms_abi)) void w_ReadFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ReadFile));
}

__attribute__((ms_abi)) void w_ReadProcessMemory(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ReadProcessMemory));
}

__attribute__((ms_abi)) void w_ReleaseMutex(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ReleaseMutex));
}

__attribute__((ms_abi)) void w_ReleaseSRWLockExclusive(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ReleaseSRWLockExclusive));
}

__attribute__((ms_abi)) void w_ReleaseSRWLockShared(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ReleaseSRWLockShared));
}

__attribute__((ms_abi)) void w_ReleaseSemaphore(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ReleaseSemaphore));
}

__attribute__((ms_abi)) void w_RemoveVectoredExceptionHandler(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RemoveVectoredExceptionHandler));
}

__attribute__((ms_abi)) void w_ResetEvent(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ResetEvent));
}

__attribute__((ms_abi)) void w_ResolveLocaleName(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ResolveLocaleName));
}

__attribute__((ms_abi)) void w_ResumeThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ResumeThread));
}

__attribute__((ms_abi)) void w_RtlCaptureContext(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlCaptureContext));
}

__attribute__((ms_abi)) void w_RtlLookupFunctionEntry(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlLookupFunctionEntry));
}

__attribute__((ms_abi)) void w_RtlRestoreContext(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlRestoreContext));
}

__attribute__((ms_abi)) void w_RtlUnwindEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlUnwindEx));
}

__attribute__((ms_abi)) void w_RtlVirtualUnwind(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlVirtualUnwind));
}

__attribute__((ms_abi)) void w_ScrollConsoleScreenBufferA(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ScrollConsoleScreenBufferA));
}

__attribute__((ms_abi)) void w_ScrollConsoleScreenBufferW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_ScrollConsoleScreenBufferW));
}

__attribute__((ms_abi)) void w_SetCommBreak(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetCommBreak));
}

__attribute__((ms_abi)) void w_SetCommMask(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetCommMask));
}

__attribute__((ms_abi)) void w_SetCommState(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetCommState));
}

__attribute__((ms_abi)) void w_SetCommTimeouts(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetCommTimeouts));
}

__attribute__((ms_abi)) void w_SetComputerNameExW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetComputerNameExW));
}

__attribute__((ms_abi)) void w_SetConsoleCP(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetConsoleCP));
}

__attribute__((ms_abi)) void w_SetConsoleCtrlHandler(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetConsoleCtrlHandler));
}

__attribute__((ms_abi)) void w_SetConsoleCursorInfo(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetConsoleCursorInfo));
}

__attribute__((ms_abi)) void w_SetConsoleCursorPosition(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetConsoleCursorPosition));
}

__attribute__((ms_abi)) void w_SetConsoleMode(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetConsoleMode));
}

__attribute__((ms_abi)) void w_SetConsoleOutputCP(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetConsoleOutputCP));
}

__attribute__((ms_abi)) void w_SetConsoleTextAttribute(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetConsoleTextAttribute));
}

__attribute__((ms_abi)) void w_SetConsoleTitleW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetConsoleTitleW));
}

__attribute__((ms_abi)) void w_SetConsoleWindowInfo(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetConsoleWindowInfo));
}

__attribute__((ms_abi)) void w_SetEnvironmentVariableW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetEnvironmentVariableW));
}

__attribute__((ms_abi)) void w_SetErrorMode(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetErrorMode));
}

__attribute__((ms_abi)) void w_SetEvent(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetEvent));
}

__attribute__((ms_abi)) void w_SetFilePointerEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetFilePointerEx));
}

__attribute__((ms_abi)) void w_SetHandleInformation(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetHandleInformation));
}

__attribute__((ms_abi)) void w_SetLastError(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetLastError));
}

__attribute__((ms_abi)) void w_SetNamedPipeHandleState(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetNamedPipeHandleState));
}

__attribute__((ms_abi)) void w_SetPriorityClass(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetPriorityClass));
}

__attribute__((ms_abi)) void w_SetProcessAffinityMask(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetProcessAffinityMask));
}

__attribute__((ms_abi)) void w_SetProcessWorkingSetSize(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetProcessWorkingSetSize));
}

__attribute__((ms_abi)) void w_SetStdHandle(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetStdHandle));
}

__attribute__((ms_abi)) void w_SetSystemTime(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetSystemTime));
}

__attribute__((ms_abi)) void w_SetTapeParameters(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetTapeParameters));
}

__attribute__((ms_abi)) void w_SetTapePosition(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetTapePosition));
}

__attribute__((ms_abi)) void w_SetThreadContext(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetThreadContext));
}

__attribute__((ms_abi)) void w_SetThreadGroupAffinity(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetThreadGroupAffinity));
}

__attribute__((ms_abi)) void w_SetThreadPriority(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetThreadPriority));
}

__attribute__((ms_abi)) void w_SetThreadStackGuarantee(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SetThreadStackGuarantee));
}

__attribute__((ms_abi)) void w_Sleep(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_Sleep));
}

__attribute__((ms_abi)) void w_SuspendThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SuspendThread));
}

__attribute__((ms_abi)) void w_SwitchToThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_SwitchToThread));
}

__attribute__((ms_abi)) void w_TerminateProcess(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_TerminateProcess));
}

__attribute__((ms_abi)) void w_TerminateThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_TerminateThread));
}

__attribute__((ms_abi)) void w_TlsAlloc(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_TlsAlloc));
}

__attribute__((ms_abi)) void w_TlsFree(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_TlsFree));
}

__attribute__((ms_abi)) void w_TlsGetValue(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_TlsGetValue));
}

__attribute__((ms_abi)) void w_TlsSetValue(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_TlsSetValue));
}

__attribute__((ms_abi)) void w_TransmitCommChar(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_TransmitCommChar));
}

__attribute__((ms_abi)) void w_UnmapViewOfFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_UnmapViewOfFile));
}

__attribute__((ms_abi)) void w_UpdateProcThreadAttribute(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_UpdateProcThreadAttribute));
}

__attribute__((ms_abi)) void w_VirtualAlloc(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_VirtualAlloc));
}

__attribute__((ms_abi)) void w_VirtualFree(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_VirtualFree));
}

__attribute__((ms_abi)) void w_VirtualProtect(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_VirtualProtect));
}

__attribute__((ms_abi)) void w_VirtualProtectEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_VirtualProtectEx));
}

__attribute__((ms_abi)) void w_VirtualQuery(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_VirtualQuery));
}

__attribute__((ms_abi)) void w_VirtualQueryEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_VirtualQueryEx));
}

__attribute__((ms_abi)) void w_WaitCommEvent(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WaitCommEvent));
}

__attribute__((ms_abi)) void w_WaitForMultipleObjects(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WaitForMultipleObjects));
}

__attribute__((ms_abi)) void w_WaitForSingleObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WaitForSingleObject));
}

__attribute__((ms_abi)) void w_WaitNamedPipeW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WaitNamedPipeW));
}

__attribute__((ms_abi)) void w_WideCharToMultiByte(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WideCharToMultiByte));
}

__attribute__((ms_abi)) void w_WriteConsoleInputW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WriteConsoleInputW));
}

__attribute__((ms_abi)) void w_WriteConsoleOutputW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WriteConsoleOutputW));
}

__attribute__((ms_abi)) void w_WriteConsoleW(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WriteConsoleW));
}

__attribute__((ms_abi)) void w_WriteFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WriteFile));
}

__attribute__((ms_abi)) void w_WriteProcessMemory(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WriteProcessMemory));
}

__attribute__((ms_abi)) void w_WriteTapemark(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_WriteTapemark));
}

__attribute__((ms_abi)) void w_NtAccessCheck(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtAccessCheck));
}

__attribute__((ms_abi)) void w_NtAdjustPrivilegesToken(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtAdjustPrivilegesToken));
}

__attribute__((ms_abi)) void w_NtAllocateLocallyUniqueId(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtAllocateLocallyUniqueId));
}

__attribute__((ms_abi)) void w_NtAssignProcessToJobObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtAssignProcessToJobObject));
}

__attribute__((ms_abi)) void w_NtCancelTimer(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCancelTimer));
}

__attribute__((ms_abi)) void w_NtClose(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtClose));
}

__attribute__((ms_abi)) void w_NtCommitTransaction(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCommitTransaction));
}

__attribute__((ms_abi)) void w_NtCreateDirectoryObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateDirectoryObject));
}

__attribute__((ms_abi)) void w_NtCreateEvent(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateEvent));
}

__attribute__((ms_abi)) void w_NtCreateFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateFile));
}

__attribute__((ms_abi)) void w_NtCreateJobObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateJobObject));
}

__attribute__((ms_abi)) void w_NtCreateKey(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateKey));
}

__attribute__((ms_abi)) void w_NtCreateMutant(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateMutant));
}

__attribute__((ms_abi)) void w_NtCreateNamedPipeFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateNamedPipeFile));
}

__attribute__((ms_abi)) void w_NtCreateSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateSection));
}

__attribute__((ms_abi)) void w_NtCreateSemaphore(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateSemaphore));
}

__attribute__((ms_abi)) void w_NtCreateSymbolicLinkObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateSymbolicLinkObject));
}

__attribute__((ms_abi)) void w_NtCreateTimer(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateTimer));
}

__attribute__((ms_abi)) void w_NtCreateTransaction(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtCreateTransaction));
}

__attribute__((ms_abi)) void w_NtDuplicateToken(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtDuplicateToken));
}

__attribute__((ms_abi)) void w_NtFlushBuffersFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtFlushBuffersFile));
}

__attribute__((ms_abi)) void w_NtFsControlFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtFsControlFile));
}

__attribute__((ms_abi)) void w_NtLockFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtLockFile));
}

__attribute__((ms_abi)) void w_NtLockVirtualMemory(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtLockVirtualMemory));
}

__attribute__((ms_abi)) void w_NtMapViewOfSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtMapViewOfSection));
}

__attribute__((ms_abi)) void w_NtOpenDirectoryObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenDirectoryObject));
}

__attribute__((ms_abi)) void w_NtOpenEvent(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenEvent));
}

__attribute__((ms_abi)) void w_NtOpenFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenFile));
}

__attribute__((ms_abi)) void w_NtOpenJobObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenJobObject));
}

__attribute__((ms_abi)) void w_NtOpenKey(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenKey));
}

__attribute__((ms_abi)) void w_NtOpenMutant(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenMutant));
}

__attribute__((ms_abi)) void w_NtOpenProcessToken(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenProcessToken));
}

__attribute__((ms_abi)) void w_NtOpenSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenSection));
}

__attribute__((ms_abi)) void w_NtOpenSemaphore(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenSemaphore));
}

__attribute__((ms_abi)) void w_NtOpenSymbolicLinkObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenSymbolicLinkObject));
}

__attribute__((ms_abi)) void w_NtOpenThreadToken(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtOpenThreadToken));
}

__attribute__((ms_abi)) void w_NtPrivilegeCheck(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtPrivilegeCheck));
}

__attribute__((ms_abi)) void w_NtQueryAttributesFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryAttributesFile));
}

__attribute__((ms_abi)) void w_NtQueryDirectoryFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryDirectoryFile));
}

__attribute__((ms_abi)) void w_NtQueryDirectoryObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryDirectoryObject));
}

__attribute__((ms_abi)) void w_NtQueryEaFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryEaFile));
}

__attribute__((ms_abi)) void w_NtQueryEvent(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryEvent));
}

__attribute__((ms_abi)) void w_NtQueryInformationFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryInformationFile));
}

__attribute__((ms_abi)) void w_NtQueryInformationJobObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryInformationJobObject));
}

__attribute__((ms_abi)) void w_NtQueryInformationProcess(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryInformationProcess));
}

__attribute__((ms_abi)) void w_NtQueryInformationThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryInformationThread));
}

__attribute__((ms_abi)) void w_NtQueryInformationToken(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryInformationToken));
}

__attribute__((ms_abi)) void w_NtQueryObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryObject));
}

__attribute__((ms_abi)) void w_NtQueryQuotaInformationFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryQuotaInformationFile));
}

__attribute__((ms_abi)) void w_NtQuerySecurityObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQuerySecurityObject));
}

__attribute__((ms_abi)) void w_NtQuerySemaphore(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQuerySemaphore));
}

__attribute__((ms_abi)) void w_NtQuerySymbolicLinkObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQuerySymbolicLinkObject));
}

__attribute__((ms_abi)) void w_NtQuerySystemInformation(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQuerySystemInformation));
}

__attribute__((ms_abi)) void w_NtQuerySystemTime(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQuerySystemTime));
}

__attribute__((ms_abi)) void w_NtQueryTimer(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryTimer));
}

__attribute__((ms_abi)) void w_NtQueryTimerResolution(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryTimerResolution));
}

__attribute__((ms_abi)) void w_NtQueryValueKey(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryValueKey));
}

__attribute__((ms_abi)) void w_NtQueryVirtualMemory(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryVirtualMemory));
}

__attribute__((ms_abi)) void w_NtQueryVolumeInformationFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtQueryVolumeInformationFile));
}

__attribute__((ms_abi)) void w_NtReadFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtReadFile));
}

__attribute__((ms_abi)) void w_NtRollbackTransaction(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtRollbackTransaction));
}

__attribute__((ms_abi)) void w_NtSetEaFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetEaFile));
}

__attribute__((ms_abi)) void w_NtSetEvent(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetEvent));
}

__attribute__((ms_abi)) void w_NtSetInformationFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetInformationFile));
}

__attribute__((ms_abi)) void w_NtSetInformationJobObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetInformationJobObject));
}

__attribute__((ms_abi)) void w_NtSetInformationThread(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetInformationThread));
}

__attribute__((ms_abi)) void w_NtSetInformationToken(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetInformationToken));
}

__attribute__((ms_abi)) void w_NtSetQuotaInformationFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetQuotaInformationFile));
}

__attribute__((ms_abi)) void w_NtSetSecurityObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetSecurityObject));
}

__attribute__((ms_abi)) void w_NtSetTimer(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetTimer));
}

__attribute__((ms_abi)) void w_NtSetValueKey(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetValueKey));
}

__attribute__((ms_abi)) void w_NtSetVolumeInformationFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtSetVolumeInformationFile));
}

__attribute__((ms_abi)) void w_NtUnlockFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtUnlockFile));
}

__attribute__((ms_abi)) void w_NtUnlockVirtualMemory(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtUnlockVirtualMemory));
}

__attribute__((ms_abi)) void w_NtUnmapViewOfSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtUnmapViewOfSection));
}

__attribute__((ms_abi)) void w_NtWaitForSingleObject(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtWaitForSingleObject));
}

__attribute__((ms_abi)) void w_NtWriteFile(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_NtWriteFile));
}

__attribute__((ms_abi)) void w_RtlAbsoluteToSelfRelativeSD(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlAbsoluteToSelfRelativeSD));
}

__attribute__((ms_abi)) void w_RtlAddAccessAllowedAce(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlAddAccessAllowedAce));
}

__attribute__((ms_abi)) void w_RtlAddAccessAllowedAceEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlAddAccessAllowedAceEx));
}

__attribute__((ms_abi)) void w_RtlAddAccessDeniedAceEx(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlAddAccessDeniedAceEx));
}

__attribute__((ms_abi)) void w_RtlAllocateHeap(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlAllocateHeap));
}

__attribute__((ms_abi)) void w_RtlAppendUnicodeStringToString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlAppendUnicodeStringToString));
}

__attribute__((ms_abi)) void w_RtlAppendUnicodeToString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlAppendUnicodeToString));
}

__attribute__((ms_abi)) void w_RtlCheckRegistryKey(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlCheckRegistryKey));
}

__attribute__((ms_abi)) void w_RtlCompareUnicodeString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlCompareUnicodeString));
}

__attribute__((ms_abi)) void w_RtlConvertSidToUnicodeString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlConvertSidToUnicodeString));
}

__attribute__((ms_abi)) void w_RtlCopySid(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlCopySid));
}

__attribute__((ms_abi)) void w_RtlCopyUnicodeString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlCopyUnicodeString));
}

__attribute__((ms_abi)) void w_RtlCreateAcl(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlCreateAcl));
}

__attribute__((ms_abi)) void w_RtlCreateQueryDebugBuffer(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlCreateQueryDebugBuffer));
}

__attribute__((ms_abi)) void w_RtlCreateSecurityDescriptor(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlCreateSecurityDescriptor));
}

__attribute__((ms_abi)) void w_RtlDestroyQueryDebugBuffer(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlDestroyQueryDebugBuffer));
}

__attribute__((ms_abi)) void w_RtlDowncaseUnicodeString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlDowncaseUnicodeString));
}

__attribute__((ms_abi)) void w_RtlEnterCriticalSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlEnterCriticalSection));
}

__attribute__((ms_abi)) void w_RtlEqualPrefixSid(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlEqualPrefixSid));
}

__attribute__((ms_abi)) void w_RtlEqualSid(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlEqualSid));
}

__attribute__((ms_abi)) void w_RtlEqualUnicodeString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlEqualUnicodeString));
}

__attribute__((ms_abi)) void w_RtlFirstFreeAce(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlFirstFreeAce));
}

__attribute__((ms_abi)) void w_RtlFreeHeap(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlFreeHeap));
}

__attribute__((ms_abi)) void w_RtlFreeUnicodeString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlFreeUnicodeString));
}

__attribute__((ms_abi)) void w_RtlGetAce(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlGetAce));
}

__attribute__((ms_abi)) void w_RtlGetControlSecurityDescriptor(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlGetControlSecurityDescriptor));
}

__attribute__((ms_abi)) void w_RtlGetCurrentTransaction(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlGetCurrentTransaction));
}

__attribute__((ms_abi)) void w_RtlGetDaclSecurityDescriptor(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlGetDaclSecurityDescriptor));
}

__attribute__((ms_abi)) void w_RtlGetGroupSecurityDescriptor(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlGetGroupSecurityDescriptor));
}

__attribute__((ms_abi)) void w_RtlGetNtVersionNumbers(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlGetNtVersionNumbers));
}

__attribute__((ms_abi)) void w_RtlGetOwnerSecurityDescriptor(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlGetOwnerSecurityDescriptor));
}

__attribute__((ms_abi)) void w_RtlGetVersion(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlGetVersion));
}

__attribute__((ms_abi)) void w_RtlIdentifierAuthoritySid(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlIdentifierAuthoritySid));
}

__attribute__((ms_abi)) void w_RtlInitAnsiString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlInitAnsiString));
}

__attribute__((ms_abi)) void w_RtlInitUnicodeString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlInitUnicodeString));
}

__attribute__((ms_abi)) void w_RtlInitializeSid(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlInitializeSid));
}

__attribute__((ms_abi)) void w_RtlLeaveCriticalSection(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlLeaveCriticalSection));
}

__attribute__((ms_abi)) void w_RtlLengthSid(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlLengthSid));
}

__attribute__((ms_abi)) void w_RtlNtStatusToDosError(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlNtStatusToDosError));
}

__attribute__((ms_abi)) void w_RtlPrefixUnicodeString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlPrefixUnicodeString));
}

__attribute__((ms_abi)) void w_RtlQueryProcessDebugInformation(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlQueryProcessDebugInformation));
}

__attribute__((ms_abi)) void w_RtlQueryRegistryValues(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlQueryRegistryValues));
}

__attribute__((ms_abi)) void w_RtlSetControlSecurityDescriptor(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlSetControlSecurityDescriptor));
}

__attribute__((ms_abi)) void w_RtlSetCurrentDirectory_U(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlSetCurrentDirectory_U));
}

__attribute__((ms_abi)) void w_RtlSetCurrentTransaction(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlSetCurrentTransaction));
}

__attribute__((ms_abi)) void w_RtlSetDaclSecurityDescriptor(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlSetDaclSecurityDescriptor));
}

__attribute__((ms_abi)) void w_RtlSetGroupSecurityDescriptor(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlSetGroupSecurityDescriptor));
}

__attribute__((ms_abi)) void w_RtlSetOwnerSecurityDescriptor(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlSetOwnerSecurityDescriptor));
}

__attribute__((ms_abi)) void w_RtlSubAuthorityCountSid(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlSubAuthorityCountSid));
}

__attribute__((ms_abi)) void w_RtlSubAuthoritySid(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlSubAuthoritySid));
}

__attribute__((ms_abi)) void w_RtlUnicodeStringToAnsiString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlUnicodeStringToAnsiString));
}

__attribute__((ms_abi)) void w_RtlUpcaseUnicodeChar(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlUpcaseUnicodeChar));
}

__attribute__((ms_abi)) void w_RtlUpcaseUnicodeString(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlUpcaseUnicodeString));
}

__attribute__((ms_abi)) void w_RtlWaitOnAddress(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlWaitOnAddress));
}

__attribute__((ms_abi)) void w_RtlWakeAddressSingle(void)
{
	__asm__ __volatile__ ("jmp *%0" : : "m"(__imp_RtlWakeAddressSingle));
}

