#!/usr/bin/env bash
#
# WP-61 certification: write a core from a fabricated process image and
# read every planted value back through the tools that will consume a real
# one. The writer is the unit under test; the readers are the WP-60 gdb and
# the cross readelf, deliberately not our own parser, so the bar is "the
# debugger agrees", not "we agree with ourselves".
#
# The refusal cases run inside corewrite_test before the file is written.
# What a live fault adds -- collection of the real segments under the stub
# -- is the seam DR-0033 leaves to the fatal path, and is not reachable
# until the loader can run a process (the WP-15/WP-60 boundary).
set -u
cd "$(dirname "$0")"

CROSS=${CROSS:-$HOME/x-elfsysvnt/bin/x86_64-elfsysvnt-linux-gnu}
GDB=${GDB:-${CROSS}-gdb}
READELF=${READELF:-${CROSS}-readelf}

pass=0 fail=0
ok()   { echo "PASS: $1"; pass=$((pass+1)); }
bad()  { echo "FAIL: $1"; fail=$((fail+1)); }
have() { command -v "$1" >/dev/null 2>&1; }

# ---- build and run the writer -------------------------------------------
gcc -std=c11 -Wall -Wextra -Werror -O2 -o corewrite_test.exe \
    corewrite_test.c ../elfcore.c || { bad "build"; echo "1 failure"; exit 1; }
./corewrite_test.exe | grep -q '^OK' && ok "writer ran and refusals refused" \
                                     || bad "writer run"
[ -s core.elf ] || { bad "core.elf missing"; echo "1 failure"; exit 1; }

# ---- binutils reads the container ---------------------------------------
if have "$READELF"; then
    h=$("$READELF" -h core.elf)
    echo "$h" | grep -q 'CORE (Core file)' && ok "readelf: ET_CORE" \
                                           || bad "readelf: type is not CORE"
    n=$("$READELF" -n core.elf)
    for note in NT_PRSTATUS NT_PRPSINFO NT_AUXV; do
        echo "$n" | grep -q "$note" && ok "readelf: $note present" \
                                    || bad "readelf: $note missing"
    done
    # This readelf is a 32-bit build and prints "Cannot decode
    # 64-bit note" for the NT_FILE desc; presence is checked here
    # and the decoded mapping through gdb below, which reads it
    # in full.
    echo "$n" | grep -q 'NT_FILE' && ok "readelf: NT_FILE present" \
                                  || bad "readelf: NT_FILE missing"
    "$READELF" -l core.elf | grep -q 'LOAD' && ok "readelf: LOAD segments" \
                                            || bad "readelf: no LOAD"
else
    bad "cross readelf not found at $READELF"
fi

# ---- gdb reads the process back -----------------------------------------
if have "$GDB"; then
    g=$("$GDB" -nx -batch -c core.elf \
        -ex 'info registers rip rsp rax r15' \
        -ex 'x/gx 0x7ffff0001000' \
        -ex 'info proc mappings' 2>&1)
    echo "$g" | grep -q "generated by .crashme --hard" \
        && ok "gdb: psargs read back" || bad "gdb: psargs wrong"
    echo "$g" | grep -q '/fake/bin/crashme' \
        && ok "gdb: NT_FILE mapping decoded" \
        || bad "gdb: NT_FILE mapping missing"
    echo "$g" | grep -q 'terminated with signal SIGSEGV' \
        && ok "gdb: fatal signal reported" || bad "gdb: signal not seen"
    echo "$g" | grep -q '0x400123'  && ok "gdb: rip read back" \
                                    || bad "gdb: rip wrong"
    echo "$g" | grep -q '0x7ffff0001000' && ok "gdb: rsp read back" \
                                         || bad "gdb: rsp wrong"
    echo "$g" | grep -q '0x1111111111111111' && ok "gdb: rax read back" \
                                             || bad "gdb: rax wrong"
    echo "$g" | grep -q '0x1515151515151515' && ok "gdb: r15 read back" \
                                             || bad "gdb: r15 wrong"
    echo "$g" | grep -q '0xdeadbeefcafef00d' \
        && ok "gdb: stack word read out of the LOAD segment" \
        || bad "gdb: stack word wrong"
else
    bad "WP-60 gdb not found at $GDB"
fi

echo
echo "$pass passed, $fail failed"
exit $((fail != 0))
