/* Generated by gen-veneer.sh from variadic-exports.tsv. Do not edit. */
/* WP-24 variadic veneer: the sysv_abi prototype of each format-driven export. */
#ifndef ELFSYSV_RUNTIME_VARARGS_VENEER_GEN_H
#define ELFSYSV_RUNTIME_VARARGS_VENEER_GEN_H

#include <stddef.h>
#include <stdio.h>
#include <wchar.h>
#include "sv2ms.h"

struct _reent;

#ifdef __cplusplus
extern "C" {
#endif

__attribute__((sysv_abi)) int printf(const char *__fmt, ...);
__attribute__((sysv_abi)) int vprintf(const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int iprintf(const char *__fmt, ...);
__attribute__((sysv_abi)) int wprintf(const wchar_t *__fmt, ...);
__attribute__((sysv_abi)) int vwprintf(const wchar_t *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int fprintf(FILE *__fp, const char *__fmt, ...);
__attribute__((sysv_abi)) int vfprintf(FILE *__fp, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int fiprintf(FILE *__fp, const char *__fmt, ...);
__attribute__((sysv_abi)) int vfiprintf(FILE *__fp, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int fwprintf(FILE *__fp, const wchar_t *__fmt, ...);
__attribute__((sysv_abi)) int vfwprintf(FILE *__fp, const wchar_t *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int sprintf(char *__s, const char *__fmt, ...);
__attribute__((sysv_abi)) int vsprintf(char *__s, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int siprintf(char *__s, const char *__fmt, ...);
__attribute__((sysv_abi)) int snprintf(char *__s, size_t __n, const char *__fmt, ...);
__attribute__((sysv_abi)) int vsnprintf(char *__s, size_t __n, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int swprintf(wchar_t *__s, size_t __n, const wchar_t *__fmt, ...);
__attribute__((sysv_abi)) int vswprintf(wchar_t *__s, size_t __n, const wchar_t *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int dprintf(int __fd, const char *__fmt, ...);
__attribute__((sysv_abi)) int vdprintf(int __fd, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int asprintf(char **__sp, const char *__fmt, ...);
__attribute__((sysv_abi)) int vasprintf(char **__sp, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) char * asnprintf(char *__buf, size_t *__lenp, const char *__fmt, ...);
__attribute__((sysv_abi)) char * vasnprintf(char *__buf, size_t *__lenp, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int __sprintf_chk(char *__s, int __flag, size_t __os, const char *__fmt, ...);
__attribute__((sysv_abi)) int __vsprintf_chk(char *__s, int __flag, size_t __os, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int __snprintf_chk(char *__s, size_t __n, int __flag, size_t __os, const char *__fmt, ...);
__attribute__((sysv_abi)) int __vsnprintf_chk(char *__s, size_t __n, int __flag, size_t __os, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int scanf(const char *__fmt, ...);
__attribute__((sysv_abi)) int vscanf(const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int wscanf(const wchar_t *__fmt, ...);
__attribute__((sysv_abi)) int vwscanf(const wchar_t *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int fscanf(FILE *__fp, const char *__fmt, ...);
__attribute__((sysv_abi)) int vfscanf(FILE *__fp, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int fwscanf(FILE *__fp, const wchar_t *__fmt, ...);
__attribute__((sysv_abi)) int vfwscanf(FILE *__fp, const wchar_t *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int sscanf(const char *__s, const char *__fmt, ...);
__attribute__((sysv_abi)) int vsscanf(const char *__s, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int swscanf(const wchar_t *__s, const wchar_t *__fmt, ...);
__attribute__((sysv_abi)) int vswscanf(const wchar_t *__s, const wchar_t *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) int _fscanf_r(struct _reent *__r, FILE *__fp, const char *__fmt, ...);
__attribute__((sysv_abi)) void err(int __eval, const char *__fmt, ...);
__attribute__((sysv_abi)) void verr(int __eval, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) void errx(int __eval, const char *__fmt, ...);
__attribute__((sysv_abi)) void verrx(int __eval, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) void warn(const char *__fmt, ...);
__attribute__((sysv_abi)) void vwarn(const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) void warnx(const char *__fmt, ...);
__attribute__((sysv_abi)) void vwarnx(const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) void syslog(int __pri, const char *__fmt, ...);
__attribute__((sysv_abi)) void vsyslog(int __pri, const char *__fmt, __sysv_va_list __ap);
__attribute__((sysv_abi)) void error(int __status, int __errnum, const char *__fmt, ...);
__attribute__((sysv_abi)) void error_at_line(int __status, int __errnum, const char *__file, unsigned int __line, const char *__fmt, ...);
__attribute__((sysv_abi)) void setproctitle(const char *__fmt, ...);

#ifdef __cplusplus
}
#endif

#endif /* ELFSYSV_RUNTIME_VARARGS_VENEER_GEN_H */
