/* Generated by gen-veneer.sh from variadic-exports.tsv. Do not edit. */
/* WP-24 variadic veneer: one sysv_abi entry point per format-driven export.
 *
 * Each establishes or receives a System V va_list, rebuilds a Microsoft one
 * with __sv2ms_* (driven by the format), and repasses through the MS-ABI core
 * named in core.h. There is no forwarding: the two va_list types disagree at
 * twenty-four bytes against eight. See the README and sv2ms.c.
 */
#include <stddef.h>
#include <stdio.h>
#include <wchar.h>
#include "sv2ms.h"
#include "core.h"

__attribute__((sysv_abi))
int printf(const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfprintf(stdout, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vprintf(const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfprintf(stdout, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int iprintf(const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfiprintf(stdout, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int wprintf(const wchar_t *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_wprint(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfwprintf(stdout, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vwprintf(const wchar_t *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_wprint(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfwprintf(stdout, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int fprintf(FILE *__fp, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfprintf(__fp, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vfprintf(FILE *__fp, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfprintf(__fp, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int fiprintf(FILE *__fp, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfiprintf(__fp, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vfiprintf(FILE *__fp, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfiprintf(__fp, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int fwprintf(FILE *__fp, const wchar_t *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_wprint(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfwprintf(__fp, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vfwprintf(FILE *__fp, const wchar_t *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_wprint(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfwprintf(__fp, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int sprintf(char *__s, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsprintf(__s, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vsprintf(char *__s, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsprintf(__s, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int siprintf(char *__s, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsiprintf(__s, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int snprintf(char *__s, size_t __n, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsnprintf(__s, __n, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vsnprintf(char *__s, size_t __n, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsnprintf(__s, __n, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int swprintf(wchar_t *__s, size_t __n, const wchar_t *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_wprint(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vswprintf(__s, __n, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vswprintf(wchar_t *__s, size_t __n, const wchar_t *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_wprint(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vswprintf(__s, __n, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int dprintf(int __fd, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vdprintf(__fd, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vdprintf(int __fd, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vdprintf(__fd, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int asprintf(char **__sp, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vasprintf(__sp, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vasprintf(char **__sp, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vasprintf(__sp, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
char * asnprintf(char *__buf, size_t *__lenp, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	char * __ret = __core_vasnprintf(__buf, __lenp, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
char * vasnprintf(char *__buf, size_t *__lenp, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	char * __ret = __core_vasnprintf(__buf, __lenp, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int __sprintf_chk(char *__s, int __flag, size_t __os, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsprintf_chk(__s, __flag, __os, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int __vsprintf_chk(char *__s, int __flag, size_t __os, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsprintf_chk(__s, __flag, __os, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int __snprintf_chk(char *__s, size_t __n, int __flag, size_t __os, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsnprintf_chk(__s, __n, __flag, __os, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int __vsnprintf_chk(char *__s, size_t __n, int __flag, size_t __os, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsnprintf_chk(__s, __n, __flag, __os, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int scanf(const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_scan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfscanf(stdin, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vscanf(const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_scan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfscanf(stdin, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int wscanf(const wchar_t *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_wscan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfwscanf(stdin, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vwscanf(const wchar_t *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_wscan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfwscanf(stdin, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int fscanf(FILE *__fp, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_scan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfscanf(__fp, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vfscanf(FILE *__fp, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_scan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfscanf(__fp, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int fwscanf(FILE *__fp, const wchar_t *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_wscan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfwscanf(__fp, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vfwscanf(FILE *__fp, const wchar_t *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_wscan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfwscanf(__fp, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int sscanf(const char *__s, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_scan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsscanf(__s, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vsscanf(const char *__s, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_scan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vsscanf(__s, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int swscanf(const wchar_t *__s, const wchar_t *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_wscan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vswscanf(__s, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
int vswscanf(const wchar_t *__s, const wchar_t *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_wscan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vswscanf(__s, __fmt, __ms);
	return __ret;
}

__attribute__((sysv_abi))
int _fscanf_r(struct _reent *__r, FILE *__fp, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_scan(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	int __ret = __core_vfscanf_r(__r, __fp, __fmt, __ms);
	__sysv_va_end(__ap);
	return __ret;
}

__attribute__((sysv_abi))
void err(int __eval, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_verr(__eval, __fmt, __ms);
	__sysv_va_end(__ap);
}

__attribute__((sysv_abi))
void verr(int __eval, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_verr(__eval, __fmt, __ms);
}

__attribute__((sysv_abi))
void errx(int __eval, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_verrx(__eval, __fmt, __ms);
	__sysv_va_end(__ap);
}

__attribute__((sysv_abi))
void verrx(int __eval, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_verrx(__eval, __fmt, __ms);
}

__attribute__((sysv_abi))
void warn(const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_vwarn(__fmt, __ms);
	__sysv_va_end(__ap);
}

__attribute__((sysv_abi))
void vwarn(const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_vwarn(__fmt, __ms);
}

__attribute__((sysv_abi))
void warnx(const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_vwarnx(__fmt, __ms);
	__sysv_va_end(__ap);
}

__attribute__((sysv_abi))
void vwarnx(const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_vwarnx(__fmt, __ms);
}

__attribute__((sysv_abi))
void syslog(int __pri, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_vsyslog(__pri, __fmt, __ms);
	__sysv_va_end(__ap);
}

__attribute__((sysv_abi))
void vsyslog(int __pri, const char *__fmt, __sysv_va_list __ap)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_vsyslog(__pri, __fmt, __ms);
}

__attribute__((sysv_abi))
void error(int __status, int __errnum, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_verror(__status, __errnum, __fmt, __ms);
	__sysv_va_end(__ap);
}

__attribute__((sysv_abi))
void error_at_line(int __status, int __errnum, const char *__file, unsigned int __line, const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_verror_at_line(__status, __errnum, __file, __line, __fmt, __ms);
	__sysv_va_end(__ap);
}

__attribute__((sysv_abi))
void setproctitle(const char *__fmt, ...)
{
	unsigned long long __slots[VARARGS_MAX_SLOTS];
	__sysv_va_list __ap;
	__sysv_va_start(__ap, __fmt);
	va_list __ms = __sv2ms_print(__slots, VARARGS_MAX_SLOTS, __fmt, __ap);
	__core_vsetproctitle(__fmt, __ms);
	__sysv_va_end(__ap);
}

