#!/usr/bin/env python3
"""Generate the versioned assembly and linker version script for libc.so.6.

WP-53. Reads WP-51's version map and node ladder and WP-52's classification and
emits, for one soname (libc.so.6 by default):

  - an assembly source: one internally-named, independently-addressable defined
    symbol per map row, bound to its GLIBC_2.x node by a .symver directive
    (@@ for the default binding, @ for a hidden compat binding);
  - a linker version script: the base node is left to the linker (it names it
    after the -soname, which keeps DT_SONAME and the base verdef node in sync,
    the invariant spike 4's trap turns on), the 29 GLIBC_2.x nodes declared in
    ladder order with each node's single parent chained so readelf -V rebuilds
    the vendor's tree, and `local: *` under the first node so the internal
    label names do not leak into .dynsym;
  - a forward map: each emitted symbol@node paired with the WP-52 bucket and the
    elfsysv1.dll export it forwards to, the record the runtime loader binds by.

Nothing here is hand-written per symbol: the symbol list is the vendor's own,
read from the map. The linker turns .symver plus the version script into the
.gnu.version_d ladder and the versioned .dynsym entries.
"""
import argparse
import sys

TYPE_ELF = {
    "func": "@function",
    "ifunc": "@gnu_indirect_function",
    "object": "@object",
    "tls": "@tls_object",
}


def read_rows(path, soname):
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line:
                continue
            f = line.split("\t")
            if f[0] == soname:
                rows.append(f)
    return rows


def load_nodes(path, soname):
    """Return the non-base nodes in ascending ladder order, each with its
    parent, plus the base node name. Order is the vd_ndx order the extractor
    recorded, which is the order the linker must re-emit."""
    base = None
    ladder = []
    for f in read_rows(path, soname):
        _, index, node, flags, parents = f[0], f[1], f[2], f[3], f[4]
        if flags == "base":
            base = node
            continue
        parent = None if parents == "-" else parents.split(",")[0]
        ladder.append((int(index), node, parent))
    ladder.sort(key=lambda t: t[0])
    return base, [(node, parent) for _, node, parent in ladder]


def load_classification(path, soname):
    """(symbol, version) -> (bucket, disposition, target)."""
    cls = {}
    for f in read_rows(path, soname):
        # soname symbol version bucket disposition target flag reason
        cls[(f[1], f[2])] = (f[3], f[4], f[5])
    return cls


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--soname", default="libc.so.6")
    ap.add_argument("--map", required=True)
    ap.add_argument("--nodes", required=True)
    ap.add_argument("--classification", required=True)
    ap.add_argument("--asm", required=True, help="assembly output")
    ap.add_argument("--version-script", required=True)
    ap.add_argument("--forward-map", required=True)
    ap.add_argument("--limit", type=int, default=0,
                    help="emit only the first N symbol rows (prototyping)")
    args = ap.parse_args()

    base, ladder = load_nodes(args.nodes, args.soname)
    if base != args.soname:
        sys.exit("base verdef node %r != soname %r: spike 4's trap; refusing"
                 % (base, args.soname))
    node_set = {n for n, _ in ladder}
    cls = load_classification(args.classification, args.soname)
    rows = read_rows(args.map, args.soname)
    if args.limit:
        rows = rows[: args.limit]


    asm = []
    asm.append('\t.file\t"libc-symbols.s"')
    asm.append("# generated by veneer/libc/generate.py -- do not edit")
    fwd = []
    counts = {"func": 0, "ifunc": 0, "object": 0, "tls": 0}
    per_node = {}
    scaffold = 0
    for i, f in enumerate(rows):
        # soname symbol version binding type bind
        symbol, version, binding, styp, sbind = f[1], f[2], f[3], f[4], f[5]
        if version not in node_set:
            sys.exit("row %d: symbol %s bound to unknown node %s"
                     % (i, symbol, version))
        if styp not in TYPE_ELF:
            sys.exit("row %d: symbol %s unknown type %s" % (i, symbol, styp))
        if (symbol, version) not in cls:
            sys.exit("row %d: symbol %s@%s absent from classification"
                     % (i, symbol, version))
        bucket, disp, target = cls[(symbol, version)]
        fwd.append("\t".join((symbol, version, binding, styp, sbind,
                              bucket, disp, target)))
        if disp == "scaffold":
            # A version-node identity object (DR-0017): `GLIBC_2.14@@GLIBC_2.14`,
            # an absolute zero-valued object. The linker emits one per declared
            # node out of the version script itself, so defining it here would
            # collide with the linker's own. Recorded in the forward map,
            # emitted by nobody; the test asserts the linker produced all 29.
            scaffold += 1
            continue
        counts[styp] += 1
        per_node.setdefault(version, []).append(symbol)
        label = "v%05d" % i
        decl = "\t.weak\t%s" % label if sbind == "weak" else "\t.globl\t%s" % label
        sep = "@@" if binding == "default" else "@"
        symver = "\t.symver\t%s, %s%s%s" % (label, symbol, sep, version)
        if styp in ("func", "ifunc"):
            asm.append("\t.text")
            asm.append(decl)
            asm.append("\t.type\t%s, %s" % (label, TYPE_ELF[styp]))
            asm.append("%s:" % label)
            asm.append("\tret")
            asm.append("\t.size\t%s, .-%s" % (label, label))
        elif styp == "object":
            asm.append("\t.data")
            asm.append(decl)
            asm.append("\t.type\t%s, %s" % (label, TYPE_ELF[styp]))
            asm.append("\t.size\t%s, 8" % label)
            asm.append("%s:\t.quad 0" % label)
        else:  # tls
            asm.append('\t.section\t.tbss,"awT",@nobits')
            asm.append(decl)
            asm.append("\t.type\t%s, %s" % (label, TYPE_ELF[styp]))
            asm.append("\t.size\t%s, 8" % label)
            asm.append("%s:\t.zero 8" % label)
        asm.append(symver)


    # Version script. The base node is the linker's, named for -soname; we
    # declare only the 29 GLIBC_2.x nodes, in ladder order, each chained to its
    # parent so the emitted .gnu.version_d rebuilds the vendor tree.
    #
    # Every symbol is listed by name under its own node, the way glibc's own
    # Versions files do it. The .symver directive alone is not enough: the
    # linker still decides global against local by matching the base name
    # against the script's patterns, so a bare `local: *` swallows most of the
    # versioned aliases. A symbol carried at two nodes is listed at both, which
    # is how the compat binding and the default binding stay independent.
    # `local: *` lives under the first node and catches the internal vNNNNN
    # labels, which are named by nothing else.
    vs = []
    vs.append("/* generated by veneer/libc/generate.py -- do not edit */")
    vs.append("")
    for pos, (node, parent) in enumerate(ladder):
        vs.append("%s {" % node)
        names = sorted(set(per_node.get(node, ())))
        if names:
            vs.append("  global:")
            for name in names:
                vs.append("    %s;" % name)
        if pos == 0:
            vs.append("  local:")
            vs.append("    *;")
        if parent is None:
            vs.append("};")
        else:
            vs.append("} %s;" % parent)
        vs.append("")

    with open(args.asm, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(asm) + "\n")
        fh.write('\t.section\t.note.GNU-stack,"",@progbits\n')
    with open(args.version_script, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(vs) + "\n")
    with open(args.forward_map, "w", encoding="utf-8", newline="\n") as fh:
        for line in fwd:
            fh.write(line + "\n")

    sys.stderr.write(
        "soname=%s rows=%d nodes=%d (base=%s) scaffold=%d\n"
        % (args.soname, len(rows), len(ladder), base, scaffold))
    sys.stderr.write(
        "types: func=%d ifunc=%d object=%d tls=%d\n"
        % (counts["func"], counts["ifunc"], counts["object"], counts["tls"]))
    missing = [n for n, _ in ladder if not per_node.get(n)]
    if missing:
        sys.stderr.write("nodes with no symbols (still emitted): %s\n"
                         % ",".join(missing))


if __name__ == "__main__":
    main()
