#!/usr/bin/env python3
"""What would each package cost to pin to the acceptance set?

DR-0079 derives the claimed surface from what the acceptance set imports, so
pinning a package costs exactly the names it adds to that set. A package that
adds none is free, and free is the interesting word: its bodies are already
claimed, written for somebody else's demands, so running it tests the surface
rather than extending it. A failure there is a defect in something believed
finished, not a missing body.

That makes two counters rather than one, and the whole value of this report is
keeping them apart. Passing a surface-free package is confidence; passing a
surface-extending one is breadth, and it is bought. Summed into a single
"packages passing" they would be indistinguishable, and the cheap one would
carry the number.

Unlike split-demand, this report is a function of the current claimed surface
and moves whenever the surface moves. That is by design: the frontier it
describes shrinks as the surface grows, and a transcript that did not change
when a package was pinned would be describing a stale frontier.

A package needing an absent capability is not costed. No surface buys it --
`public-absent` names are what the floor beneath does not have -- so it sits in
its own class rather than at the expensive end of a scale it is not on.

Usage:
  pin-cost.py --root DIR [options]

Options:
  --root DIR         the census work root, holding frag/ (required)
  --claimed FILE     claimed-surface.tsv        [default: the tree's]
  --inventory FILE   bucket4-inventory.tsv      [default: the tree's]
  -o FILE            transcript, - for stdout   [default: -]
  --tsv FILE         also write the full per-package cost table here
  -h, --help         this help

Exit: 0 the report was taken, 2 a usage error or a missing input.
"""
import argparse, collections, datetime, os, sys

VERSION = "pin-cost 1.0"
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir))
CLAIMED = os.path.join(ROOT, "veneer", "classification", "claimed-surface.tsv")
INV = os.path.join(ROOT, "veneer", "classification", "bucket4-inventory.tsv")

# The cost bands. A band is a label a reader acts on, not a number: "free" is
# a pin queue, "1-5" is a cheap frontier, "51+" is a project.
BANDS = ((0, "free"), (5, "cheap"), (20, "moderate"), (50, "expensive"))
UNPINNABLE = "unpinnable"


def load_claimed(path):
    return set(l.split("\t")[0] for l in open(path, encoding="utf-8")
               if l.strip() and not l.startswith("#"))


def load_gap(path):
    """The names no surface buys: the floor beneath does not have them."""
    out = set()
    for l in open(path, encoding="utf-8"):
        f = l.rstrip("\n").split("\t")
        if len(f) >= 3 and f[0] == "public-absent":
            out.add(f[2])
    return out


def band_of(added):
    for limit, name in BANDS:
        if added <= limit:
            return name
    return "project"


def cost(frag_dir, claimed, gap):
    """Per package: (band, names it would add, claimed names it exercises)."""
    rows = []
    for name in sorted(os.listdir(frag_dir)):
        if not name.endswith(".tsv"):
            continue
        syms = set()
        for l in open(os.path.join(frag_dir, name), encoding="utf-8"):
            f = l.rstrip("\n").split("\t")
            if len(f) >= 3:
                syms.add(f[1])
        if not syms:
            continue
        pkg = name[:-4]
        if syms & gap:
            rows.append((pkg, UNPINNABLE, len(syms & gap), len(syms & claimed)))
            continue
        added = len(syms - claimed)
        rows.append((pkg, band_of(added), added, len(syms & claimed)))
    return rows


def emit(out, rows, claimed, frag_dir):
    tally = collections.Counter(r[1] for r in rows)
    free = sorted((r for r in rows if r[1] == "free"),
                  key=lambda r: (-r[3], r[0]))
    cheap = sorted((r for r in rows if r[1] == "cheap"),
                   key=lambda r: (r[2], -r[3], r[0]))

    w = out.write
    w("# What each package would cost to pin, in names added to the claimed\n"
      "# surface. Free packages test the surface; extending ones buy breadth\n"
      "# and are paid for. The two are never one number.\n"
      "#\n"
      "# Generated by pin-cost 1.0. Rerunning it regenerates this file, and it\n"
      "# moves when the claimed surface moves, which is the point.\n\n")
    w("script  %s\n" % VERSION)
    w("run_date  %s\n" % datetime.date.today().isoformat())
    w("frag_root  %s\n" % os.path.basename(os.path.dirname(frag_dir.rstrip("/"))))
    w("claimed_surface  %d names\n" % len(claimed))
    w("\n## The cost bands\n\n")
    for _, name in BANDS:
        w("%-12s %5d packages\n" % (name, tally[name]))
    w("%-12s %5d packages\n" % ("project", tally["project"]))
    w("%-12s %5d packages  (no surface buys these; the floor lacks the capability)\n"
      % (UNPINNABLE, tally[UNPINNABLE]))
    w("\n## The free frontier, deepest exercise first\n\n")
    w("# Each of these adds nothing to the claimed surface. Pinning one buys a\n"
      "# test of bodies already written and claims no new obligation.\n\n")
    for pkg, _, _, ex in free:
        w("free  %-40s exercises %d\n" % (pkg, ex))
    w("\n## The cheap frontier, least added first\n\n")
    for pkg, _, add, ex in cheap[:40]:
        w("cheap %-40s adds %-3d exercises %d\n" % (pkg, add, ex))
    w("\n## The finding\n\n")
    w("free_frontier  exists and is not empty\n")
    w("free_packages  %d add nothing to the claimed surface\n" % tally["free"])
    w("counters  surface-free passes measure confidence, extending passes measure breadth\n")
    w("summing  refused: one number would let the cheap counter carry it\n")
    w("frontier_shrinks  as the surface grows, which is why this report is regenerated\n")
    w("\nverdict=a-free-frontier-exists\n")


def write_tsv(path, rows):
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# package\tband\tnames-added\tclaimed-names-exercised\n")
        for pkg, band, add, ex in sorted(rows):
            fh.write("%s\t%s\t%d\t%d\n" % (pkg, band, add, ex))


def main(argv):
    ap = argparse.ArgumentParser(add_help=False)
    ap.add_argument("--root")
    ap.add_argument("--claimed", default=CLAIMED)
    ap.add_argument("--inventory", default=INV)
    ap.add_argument("-o", default="-")
    ap.add_argument("--tsv")
    ap.add_argument("-h", "--help", action="store_true")
    args = ap.parse_args(argv)

    if args.help or not args.root:
        sys.stdout.write(__doc__)
        return 0 if args.help else 2

    frag = os.path.join(args.root, "frag")
    for path, what in ((frag, "the census work root's frag/"),
                       (args.claimed, "the claimed surface"),
                       (args.inventory, "the fourth-bucket inventory")):
        if not os.path.exists(path):
            sys.stderr.write("pin-cost: %s is absent: %s\n"
                             "pin-cost: run the census first; this reads what it collected.\n"
                             % (what, path))
            return 2

    claimed = load_claimed(args.claimed)
    gap = load_gap(args.inventory)
    rows = cost(frag, claimed, gap)

    fh = sys.stdout if args.o == "-" else open(args.o, "w", encoding="utf-8", newline="\n")
    emit(fh, rows, claimed, frag)
    if fh is not sys.stdout:
        fh.close()
    if args.tsv:
        write_tsv(args.tsv, rows)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
