#!/usr/bin/env bash
#
# Does the linker emit %fs-relative code on its own?
#
# DR-0003 replaced %fs-relative TLS with a runtime-owned pointer reached
# through %gs, and its cost paragraph says the ELF format and the glibc TCB
# layout are untouched, only how the pointer is fetched changes. That reads as
# a codegen concern, and DR-0003's list of places the carrier is named --
# WP-30's codegen, WP-37's loader, WP-13's specs -- has no linker in it.
#
# The linker is not on that list and should be. ld's x86-64 backend rewrites
# the psABI's TLS access sequences in place, and the bytes it writes are its
# own rather than the compiler's. This assembles the two rewritable sequences
# and reads back what came out.
#
# Usage:
#   measure-relaxation.sh [options]
#
# Options:
#   -B DIR, --bindir=DIR  Where the cross tools live. [default: from PATH]
#   -T TRIPLE, --target=TRIPLE
#                         Tool prefix. [default: x86_64-elfsysvnt-linux-gnu]
#   -w DIR, --work=DIR    Scratch. Cleared on entry. [default: $TMPDIR/ldtls]
#   -q, --quiet           Errors only.
#   -v, --verbose         Name each step.
#   -d, --debug           Trace execution; implies --verbose.
#   -V, --version         Print the version and exit.
#   -h, --help            Print this message and exit.
#
# Exit codes: 0 the measurement ran, 1 it could not, 2 usage error.

set -u

prog=measure-relaxation
release='measure-relaxation 1.0'

here=$(cd "$(dirname "$0")" && pwd)

bindir=${MEASURE_RELAXATION_BINDIR:-}
target=${MEASURE_RELAXATION_TARGET:-x86_64-elfsysvnt-linux-gnu}
work=${MEASURE_RELAXATION_WORK:-${TMPDIR:-/tmp}/ldtls}
quiet=${MEASURE_RELAXATION_QUIET:-0}
verbose=${MEASURE_RELAXATION_VERBOSE:-0}
debug=${MEASURE_RELAXATION_DEBUG:-0}

usage() { awk '/^# Usage:/,/^[^#]/ { if ($0 ~ /^#/) print substr($0, 3) }' "$0"; }

die() { printf '%s: %s\n' "$prog" "$*" >&2; exit 1; }

usage_error() { printf '%s: %s\n' "$prog" "$*" >&2; usage >&2; exit 2; }

note() { [ "$quiet" = 1 ] || printf '%s: %s\n' "$prog" "$*" >&2; }

chat() { [ "$verbose" = 1 ] && note "$@"; return 0; }

while [ $# -gt 0 ]; do
    opt=$1; shift
    val=
    case $opt in
        --*=*) val=${opt#*=}; opt=${opt%%=*} ;;
    esac
    takes=0
    case $opt in
        -B|--bindir|-T|--target|-w|--work) takes=1 ;;
    esac
    if [ "$takes" = 1 ] && [ -z "$val" ]; then
        [ $# -gt 0 ] || usage_error "$opt wants a value"
        val=$1; shift
    fi
    case $opt in
        -B|--bindir) bindir=$val ;;
        -T|--target) target=$val ;;
        -w|--work) work=$val ;;
        -q|--quiet) quiet=1 ;;
        -v|--verbose) verbose=1 ;;
        -d|--debug) debug=1; verbose=1 ;;
        -V|--version) printf '%s\n' "$release"; exit 0 ;;
        -h|--help) usage; exit 0 ;;
        --) break ;;
        *) usage_error "unknown option $opt" ;;
    esac
done

[ "$debug" = 1 ] && set -x
[ -z "$bindir" ] || PATH=$bindir:$PATH
AS=$target-as; LD=$target-ld; OBJDUMP=$target-objdump; READELF=$target-readelf
for t in "$AS" "$LD" "$OBJDUMP" "$READELF"; do
    command -v "$t" >/dev/null 2>&1 || die "$t is not on PATH"
done

rm -rf "$work"; mkdir -p "$work" || die "cannot create $work"
cd "$work" || die "cannot enter $work"

"$AS" -o tls.o "$here/tls-models.s" || die "the assembler rejected tls-models.s"
chat "assembled"

cat <<'HEADER'
# Does the linker emit %fs-relative code on its own?
#
# Generated by measure-relaxation 1.0. Rerunning it regenerates this file.

HEADER

printf 'run_date=%s\n' "$(date +%Y-%m-%d)"
printf 'target=%s\n' "$target"
printf 'ld=%s\n' "$("$LD" --version | head -1)"

printf '\n## Relocations the assembler emitted\n\n'
"$READELF" -rW tls.o | grep -i -e TLSGD -e GOTTPOFF -e TPOFF | sed 's/^/    /'

# Linked as an executable with the definition in the same object, which is
# the case that licenses both relaxations: general dynamic to local exec, and
# initial exec to local exec. Since this spike first ran, WP-12's binutils
# patch made ld refuse these relocations outright rather than relax them into
# an %fs fetch, so a refusal naming the FS segment base is a measured outcome
# here, not a broken run.
if "$LD" -o tls.exe tls.o -e _start 2>ld.err; then
    printf '\n## _start after the linker rewrote it\n\n'
    "$OBJDUMP" -d tls.exe | sed -n '/<_start>:/,/ret/p' | sed 's/^/    /'

    printf '\n## Segment-prefixed instructions in the output\n\n'
    if "$OBJDUMP" -d tls.exe | grep -q '%fs:'; then
        "$OBJDUMP" -d tls.exe | grep '%fs:' | sed 's/^/    /'
        printf '\nverdict=ld emits fs-relative thread pointer fetches\n'
    else
        printf '    none\n\nverdict=ld emitted no segment-prefixed access\n'
    fi

    printf '\n## Whether the sequences leave room for a longer rewrite\n\n'
    gd=$("$OBJDUMP" -d tls.exe | sed -n '/<_start>:/,$p' | sed -n 2p | sed 's/^/    /')
    printf '%s\n' "$gd"
    printf '    general dynamic occupies 16 bytes before rewriting and the\n'
    printf '    local-exec form ld writes occupies 16 after, padding included.\n'
else
    printf '\n## What the linker did with them\n\n'
    sed 's/^/    /' ld.err
    grep -q 'presumes a thread pointer' ld.err ||
        die "the link failed for a reason this spike does not classify"
    printf '\nverdict=ld refuses the fs-presuming TLS relocations\n'
fi

exit 0
