#!/usr/bin/env bash
#
# Could FreeBSD's runtime linker be lifted instead of written?
#
# AGENTS.md now asks this before any code is written, and the question had
# never been asked about the loader. The answer that stood was that glibc's
# resolver is unusable, on a licence reading that turned out to be wrong; the
# real obstacle is coupling. FreeBSD's rtld-elf is the other complete
# implementation, and unlike glibc's it is under a licence this tree can take
# outright, so the coupling question is the only one left.
#
# This surveys rather than ports. It answers three things a decision needs:
# what the licence actually says, whether the versioning path is really there,
# and how much of rtld.c that path drags behind it. A survey that concluded
# "liftable" without measuring the third would be the same kind of claim this
# spike exists to correct.
#
# Usage:
#   survey-rtld.sh [options]
#
# Options:
#   -D DIR, --dest=DIR       Sources land here.
#   -s FILE, --sources=FILE  The pin. [default: beside this one]
#   -b URL, --base=URL       Raw-file base for the pinned tag.
#   -q, --quiet              Errors only.
#   -v, --verbose            Name every step.
#   -V, --version            Print the version and exit.
#   -h, --help               Print this message and exit.
#
# Exit codes: 0 success, 1 failure, 2 usage error.

set -u

prog=survey-rtld
release='survey-rtld 1.0'
here=$(cd "$(dirname "$0")" && pwd)

dest=${SURVEY_RTLD_DEST:-}
sources=${SURVEY_RTLD_SOURCES:-$here/sources.tsv}
base=${SURVEY_RTLD_BASE:-https://raw.githubusercontent.com/freebsd/freebsd-src/release/14.2.0/libexec/rtld-elf}
quiet=${SURVEY_RTLD_QUIET:-0}
verbose=${SURVEY_RTLD_VERBOSE:-0}

usage() { awk '/^# Usage:/,/^[^#]/ { if ($0 ~ /^#/) print substr($0, 3) }' "$0"; }
die() { printf '%s: %s\n' "$prog" "$*" >&2; exit 1; }
usage_error() { printf '%s: %s\n' "$prog" "$*" >&2; usage >&2; exit 2; }
note() { [ "$quiet" = 1 ] || printf '%s: %s\n' "$prog" "$*" >&2; }
chat() { [ "$verbose" = 1 ] && note "$@"; return 0; }

while [ $# -gt 0 ]; do
	opt=$1; shift; val=
	case $opt in --*=*) val=${opt#*=}; opt=${opt%%=*} ;; esac
	case $opt in
		-D|--dest|-s|--sources|-b|--base)
			[ -n "$val" ] || { [ $# -gt 0 ] || usage_error "$opt wants a value"; val=$1; shift; } ;;
	esac
	case $opt in
		-D|--dest) dest=$val ;;
		-s|--sources) sources=$val ;;
		-b|--base) base=$val ;;
		-q|--quiet) quiet=1 ;;
		-v|--verbose) verbose=1 ;;
		-V|--version) printf '%s\n' "$release"; exit 0 ;;
		-h|--help) usage; exit 0 ;;
		--) break ;;
		*) usage_error "unknown option $opt" ;;
	esac
done

[ -n "$dest" ] || usage_error "--dest is required"
[ -r "$sources" ] || die "cannot read the pin: $sources"
command -v curl >/dev/null 2>&1 || die "curl is not on PATH"

mkdir -p "$dest" || die "cannot create $dest"
fetched=0; reused=0

while IFS="$(printf '\t')" read -r name path want; do
	case $name in ''|\#*) continue ;; esac
	f=$dest/$name
	if [ -f "$f" ] && [ "$(sha256sum "$f" | cut -d' ' -f1)" = "$want" ]; then
		reused=$((reused + 1)); chat "have $name"
	else
		rm -f "$f"; chat "fetch $name"
		o=$f; command -v cygpath >/dev/null 2>&1 && o=$(cygpath -w "$f")
		curl -fsS --retry 3 --retry-delay 2 -o "$o" "$base/$path" \
			|| die "cannot fetch $name"
		got=$(sha256sum "$f" | cut -d' ' -f1)
		[ "$got" = "$want" ] || die "checksum mismatch on $name: $got"
		fetched=$((fetched + 1))
	fi
done < "$sources"

c=$dest/rtld.c
h=$dest/rtld.h

# The versioning path, named by its entry points. A function's extent runs from
# its definition line to the next closing brace in column 1, which is the
# style this file is written in throughout; the count is the honest size of
# what a lift would have to carry, not a guess at it.
fns="find_symdef symlook_obj symlook_obj1_gnu symlook_obj1_sysv matched_symbol rtld_verify_versions"

span_of() {
	awk -v fn="$1" '
		$0 ~ "^" fn "\\(" { inside = 1; n = 0 }
		inside { n++ }
		inside && /^}/ { print n; exit }
	' "$c"
}

# Coupling, counted rather than characterised. A header under sys/ or machine/
# is a BSD kernel interface and does not exist here; everything else is either
# standard C or rtld's own.
bsd_includes=$(grep -cE '^#include <(sys|machine)/' "$c")
own_includes=$(grep -cE '^#include "' "$c")
std_includes=$(grep -cE '^#include <' "$c")
std_includes=$((std_includes - bsd_includes))

[ "$quiet" = 1 ] || cat <<'HEADER'
# Could FreeBSD's runtime linker be lifted instead of written? The licence, the
# presence of a real versioning path, and the size of what that path drags
# behind it.
#
# Generated by survey-rtld 1.0. Rerunning it regenerates this file.

HEADER

printf 'script  survey-rtld 1.0\n'
printf 'run_date  %s\n' "$(date +%Y-%m-%d)"
printf 'source  %s\n' "$base"
printf 'fetched  %d\n' "$fetched"
printf 'reused  %d\n' "$reused"

printf '\n## Licence\n\n'
printf 'rtld_c_spdx=%s\n' \
	"$(sed -n 's/^ \* SPDX-License-Identifier: *//p' "$c" | head -1)"
printf 'rtld_h_spdx=%s\n' \
	"$(sed -n 's/^ \* SPDX-License-Identifier: *//p' "$h" | head -1)"
printf 'compatible_with_lgplv3_tree=%s\n' \
	"$(sed -n 's/^ \* SPDX-License-Identifier: *//p' "$c" | head -1 \
	   | grep -q 'BSD' && echo yes || echo unknown)"

printf '\n## Is the versioning path really there\n\n'
for f in $fns; do
	if grep -qE "^$f\(" "$c"; then
		printf '%s=present\n' "$f"
	else
		printf '%s=ABSENT\n' "$f"
	fi
done
printf 'verdef_parsed=%s\n' "$(grep -q 'obj->verdef' "$c" && echo yes || echo no)"
printf 'verneed_parsed=%s\n' "$(grep -q 'obj->verneed' "$c" && echo yes || echo no)"

printf '\n## What a lift would carry\n\n'
total=0
for f in $fns; do
	n=$(span_of "$f"); n=${n:-0}
	total=$((total + n))
done
printf 'versioning_path_lines=%d\n' "$total"
printf 'rtld_c_lines=%d\n' "$(wc -l < "$c" | tr -d ' ')"
printf 'bsd_kernel_includes=%d\n' "$bsd_includes"
printf 'rtld_own_includes=%d\n' "$own_includes"
printf 'standard_includes=%d\n' "$std_includes"

# The verdict is about the licence and the presence of the path, which are the
# two things a survey can settle. Whether the adaptation is worth doing is a
# decision, and this deliberately does not take it.
printf '\n## Verdict\n\n'
if grep -q 'BSD-2-Clause' "$c" && grep -qE '^rtld_verify_versions\(' "$c"; then
	printf 'verdict=liftable-on-licence-adaptation-is-the-question\n'
else
	printf 'verdict=refuted\n'
fi

note "surveyed $(wc -l < "$c" | tr -d ' ') lines of rtld.c under $dest"
exit 0
