#!/usr/bin/env bash
#
# WP-56 -- unit-test the acceptance classifier (classify.awk). Two bars this
# harness rests on:
#   * a bucket-4 stub named in the filled manifest reports as filled, and a
#     bucket-4 stub that is not reports as stub (DR-0052);
#   * a bucket-3 shim named in the certified-shim manifest reports as wired,
#     and a bucket-3 shim that is not reports as shim -- the same manifest-not-
#     bucket distinction, one bucket up.
# Also checks the other dispositions. Host only -- no network, no toolchain, no
# image.
#
# Exit: 0 all checks passed, 1 a divergence.
set -u
here=$(cd "$(dirname "$0")" && pwd)
awkf=$here/../classify.awk
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
fail=0

# A classification fixture: one row per disposition, tabs via printf so no
# literal tab has to survive this heredoc. Two bucket-3 shims -- one the wiring
# layer has written and certified, one it has not.
classif=$tmp/classif.tsv
{
printf 'libc.so.6\tfwd_same\tGLIBC_2.2.5\t2\tforward-same\t-\t-\tx\n'
printf 'libc.so.6\tfwd_alias\tGLIBC_2.2.5\t1\tforward-alias\t-\t-\tx\n'
printf 'libc.so.6\ta_wired\tGLIBC_2.2.5\t3\tshim\t-\t-\tx\n'
printf 'libc.so.6\ta_shim\tGLIBC_2.2.5\t3\tshim\t-\t-\tx\n'
printf 'libc.so.6\tfilled_one\tGLIBC_2.3\t4\tstub\t-\t-\tabsent\n'
printf 'libc.so.6\tplain_stub\tGLIBC_2.3\t4\tstub\t-\t-\tabsent\n'
printf 'libc.so.6\ta_scaffold\tGLIBC_2.14\tscaffold\tscaffold\t-\t-\tnode\n'
} > "$classif"

# A filled manifest naming one of the two bucket-4 stubs, with comment lines.
filled=$tmp/filled.tsv
{
printf '# a filled manifest\n'
printf '# symbol\tversion\tbody\tcertified-by\n'
printf 'filled_one\tGLIBC_2.3\tbody.c\tt.sh\n'
} > "$filled"

# A certified-shim manifest naming one of the two bucket-3 shims, with the
# comment and version-node columns a real wire-<slice>.shims.tsv carries.
wired=$tmp/wired.tsv
{
printf '# generated by gen-wire.py, slice example; do not edit\n'
printf '# symbol\tversion\tbinding\ttarget\ttable-index\n'
printf 'a_wired\tGLIBC_2.2.5\tdefault\t-\t0\n'
} > "$wired"

# The binary needs every mapped name plus one the map does not know.
needs=$tmp/needs
printf '%s\n' fwd_same fwd_alias a_wired a_shim filled_one plain_stub a_scaffold not_mapped > "$needs"

got=$(awk -v filled="$filled" -v wired="$wired" -v needs="$needs" -f "$awkf" \
	"$filled" "$wired" "$needs" "$classif" | sort)
want=$(printf '%s\n' \
'filled filled_one' \
'forward fwd_alias' \
'forward fwd_same' \
'shim a_shim' \
'stub plain_stub' \
'unclassified a_scaffold' \
'unclassified not_mapped' \
'wired a_wired' | sort)

if [ "$got" = "$want" ]; then
echo "classify: every disposition correct; a written shim is not an unwritten shim, a filled stub not a failing stub"
else
echo "classify: FAIL -- dispositions diverged" >&2
diff <(printf '%s\n' "$want") <(printf '%s\n' "$got") >&2
fail=1
fi

# The fill must come from the manifest, not the bucket: with an empty manifest
# the same symbol is a plain stub.
empty=$tmp/empty; : > "$empty"
nf=$(awk -v filled="$empty" -v wired="$wired" -v needs="$needs" -f "$awkf" \
	"$empty" "$wired" "$needs" "$classif" | grep -c '^filled ')
if [ "$nf" -eq 0 ]; then
echo "classify: no symbol is filled without a manifest"
else
echo "classify: FAIL -- a symbol reported filled with no manifest" >&2
fail=1
fi

# The wiring must come from the manifest too: with an empty certified-shim
# manifest the bucket-3 symbol is an unwritten shim, not wired.
nw=$(awk -v filled="$filled" -v wired="$empty" -v needs="$needs" -f "$awkf" \
	"$filled" "$empty" "$needs" "$classif" | grep -c '^wired ')
ns=$(awk -v filled="$filled" -v wired="$empty" -v needs="$needs" -f "$awkf" \
	"$filled" "$empty" "$needs" "$classif" | grep -c '^shim ')
if [ "$nw" -eq 0 ] && [ "$ns" -eq 2 ]; then
echo "classify: no shim is wired without a manifest; both bucket-3 symbols read shim"
else
echo "classify: FAIL -- wired disposition did not turn on the manifest (wired=$nw shim=$ns)" >&2
fail=1
fi

[ "$fail" = 0 ] && echo "classify: ok"
exit $fail
