#!/usr/bin/env bash
#
# WP-27: emit the export table that puts the faces on the DLL.
#
# face.din is the .def/.din seam: one export row per face-table row, in
# face-table order, each row disposed by the tables this directory already
# certifies. The fence marker the vendor din carried travels through
# face.tsv's third column unchanged, so the sigfe fence stays outside the
# face: export -> sigfe stub -> System V face -> Microsoft body. The stub
# touches only r10, r11, and the stack, which both conventions treat as
# scratch, so it forwards a System V argument set undisturbed.
#
# Row dispositions:
#   data                      name DATA            (exported object, unchanged)
#   sv2ms resolved to asis    the vendor row       (PE-side protocol, unfaced)
#   sv2ms resolved to data    name DATA            (__infinity, the marker the
#                                                   vendor din omitted)
#   variadic, sv2ms int/fp/aggr
#                             name = __face_<name> (the face, renamed back to
#                                                   the export name; the alias
#                                                   target is already bound
#                                                   inside the face)
#
# The variadic rows bind __face_<name> like every other faced row; the
# wiring step renames WP-24's veneer entries onto that prefix when the
# objects join the DLL, so the seam names one convention, not two.
#
# The LIBRARY line reproduces the vendor din's, name and base both.
#
# Usage:
#   gen-din.sh [-o FILE] [--face FILE] [--sigclass FILE] [--unlisted FILE]
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
face=$here/face.tsv
sigclass=$here/sigclass.tsv
unlisted=$here/unlisted.tsv
out=$here/face.din
while [ $# -gt 0 ]; do
  case $1 in
    -o) out=$2; shift 2;;
    --face) face=$2; shift 2;;
    --sigclass) sigclass=$2; shift 2;;
    --unlisted) unlisted=$2; shift 2;;
    *) echo "unknown option: $1" >&2; exit 2;;
  esac
done

gen() {
  printf '# Generated by gen-din.sh from face.tsv; do not edit.\n'
  printf 'LIBRARY "elfsysv1.dll" BASE=0x180040000\n'
  printf '\nEXPORTS\n'
  awk -F'\t' -v sig="$sigclass" -v unl="$unlisted" '
    BEGIN {
      while ((getline line < sig) > 0) { split(line, f, "\t"); cls[f[1]] = f[2] }
      while ((getline line < unl) > 0) {
        split(line, f, "\t")
        if (cls[f[1]] == "unlisted") cls[f[1]] = f[2]
      }
    }
    {
      name = $1; disp = $2; fence = $3; target = $4
      mark = (fence == "none" || fence == "-") ? "" : " " fence
      if (disp == "data") { print name " DATA"; next }
      c = cls[name]
      if (disp == "sv2ms" && c == "data") { print name " DATA"; next }
      if (disp == "sv2ms" && c == "asis") {
        if (target != name) print name " = " target mark
        else print name mark
        next
      }
      print name " = __face_" name mark
    }
  ' "$face"
}

if [ "$out" = - ]; then gen; else gen > "$out"; fi
