#!/usr/bin/env bash
#
# WP-27: emit the int-class faces from the face and signature-class tables.
#
# One generated assembly unit, one macro invocation per int-class sv2ms
# export: `sv2ms_int_face __face_<name>, <target>`. The face symbol carries
# the __face_ prefix because 1666 of the sv2ms rows bind to a target of
# their own name; the export table (the .def/.din seam, next milestone)
# renames the face back to the export name, the way an alias row already
# renames accept onto cygwin_accept. The macro itself is hand-written and
# certified on its own in sv2ms-int.inc; this unit only instantiates it.
#
# Rows come from face.tsv (the sv2ms surface, in export order) intersected
# with sigclass.tsv (class int). Rows sigclass.tsv left unlisted take their
# class from unlisted.tsv, so the 193 unlisted-int faces are emitted here
# too. fp, aggr, asis, and data rows are other shapes per the face-shapes
# and unlisted-disposition records and are not emitted here; neither are
# ctx.tsv's rows, the setjmp family whose context-capturing bodies take the
# frameless face gen-ctx-faces.sh emits instead.
#
# Usage:
#   gen-int-faces.sh [-o FILE] [--face FILE] [--sigclass FILE] [--unlisted FILE] [--ctx FILE]
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
face=$here/face.tsv
sigclass=$here/sigclass.tsv
unlisted=$here/unlisted.tsv
ctx=$here/ctx.tsv
out=$here/int-faces.gen.S
while [ $# -gt 0 ]; do
  case $1 in
    -o) out=$2; shift 2;;
    --face) face=$2; shift 2;;
    --sigclass) sigclass=$2; shift 2;;
    --unlisted) unlisted=$2; shift 2;;
    --ctx) ctx=$2; shift 2;;
    *) echo "unknown option: $1" >&2; exit 2;;
  esac
done

gen() {
  printf '/* Generated by gen-int-faces.sh; do not edit. */\n'
  printf '#include "sv2ms-int.inc"\n'
  awk -F'\t' -v sig="$sigclass" -v unl="$unlisted" -v ctxf="$ctx" '
    BEGIN {
      while ((getline line < sig) > 0) { split(line, f, "\t"); cls[f[1]] = f[2] }
      while ((getline line < unl) > 0) {
        split(line, f, "\t")
        if (cls[f[1]] == "unlisted") cls[f[1]] = f[2]
      }
      while ((getline line < ctxf) > 0) { split(line, f, "\t"); ctx[f[1]] = 1 }
    }
    $2 == "sv2ms" && cls[$1] == "int" && !($1 in ctx) {
      printf "\tsv2ms_int_face\t__face_%s, %s\n", $1, $4
    }
  ' "$face"
}

if [ "$out" = - ]; then gen; else gen > "$out"; fi
