#!/usr/bin/env bash
#
# WP-27: emit the context-transparent faces from the curated ctx table.
#
# One macro invocation per ctx.tsv row: `sv2ms_ctx_face __face_<name>,
# <target>`. The rows are the setjmp family -- bodies that capture or
# restore their caller's context and therefore cannot sit behind the
# call-style int face (see sv2ms-ctx.inc and the context-transparent-faces
# decision record). ctx.tsv is curated, not derived: membership is a
# promise about the body (gendef assembly that never touches caller shadow
# space), which no header can state. gen-int-faces.sh excludes these rows;
# the export table binds the same __face_ prefix, so the .din seam does not
# change shape.
#
# Usage:
#   gen-ctx-faces.sh [-o FILE] [--ctx FILE]
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
ctx=$here/ctx.tsv
out=$here/ctx-faces.gen.S
while [ $# -gt 0 ]; do
  case $1 in
    -o) out=$2; shift 2;;
    --ctx) ctx=$2; shift 2;;
    *) echo "unknown option: $1" >&2; exit 2;;
  esac
done

gen() {
  printf '/* Generated by gen-ctx-faces.sh; do not edit. */\n'
  printf '#include "sv2ms-ctx.inc"\n'
  awk -F'\t' '{ printf "\tsv2ms_ctx_face\t__face_%s, %s\n", $1, $2 }' "$ctx"
}

if [ "$out" = - ]; then gen; else gen > "$out"; fi
