#!/usr/bin/env bash
#
# WP-27: emit the typed fp- and aggr-class faces from their recorded
# prototypes.
#
# The int class shares one generic shape because integer arguments occupy
# the same positional slots under both conventions. A float, double,
# _Complex, or by-value aggregate anywhere in the signature breaks that:
# which registers carry what now depends on the whole prototype, and the
# only correct mover is the compiler that knows both conventions. So each
# fp and aggr face is a C thunk compiled from the prototype sigclass.tsv
# recorded: a sysv_abi function that calls the Microsoft-convention body
# and returns its result, and gcc emits the crossing.
#
# The body is reached through an __asm__ label, not its C name. Three
# reasons: the face-table target may differ from the export name (drem's
# body is remainder); the target's own header declaration may disagree
# with the face's recorded prototype (imaxdiv's body is lldiv, and
# imaxdiv_t and lldiv_t are distinct struct types); and math.h shadows
# names like isinf with function-like macros. A private __body_ symbol
# aliased to the target dodges all three, and binds exactly what the
# .def/.din seam will export.
#
# The prelude -- the header block that declares every parameter and
# return type -- is the same probe block derive-sigclass.sh read the
# prototypes out of, extracted from that script so the two cannot drift.
# --prelude substitutes an include for it so the certification harness
# can drive the same emission over fabricated tables.
#
# Rows sigclass.tsv left unlisted take their class and prototype from
# unlisted.tsv, so the 16 unlisted-fp faces are emitted here too, from the
# prototypes that table records.
#
# Usage:
#   gen-typed-faces.sh [-o FILE] [--face FILE] [--sigclass FILE] [--unlisted FILE] [--prelude NAME]
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
face=$here/face.tsv
sigclass=$here/sigclass.tsv
unlisted=$here/unlisted.tsv
out=$here/typed-faces.gen.c
prelude=
while [ $# -gt 0 ]; do
  case $1 in
    -o) out=$2; shift 2;;
    --face) face=$2; shift 2;;
    --sigclass) sigclass=$2; shift 2;;
    --unlisted) unlisted=$2; shift 2;;
    --prelude) prelude=$2; shift 2;;
    *) echo "unknown option: $1" >&2; exit 2;;
  esac
done

gen() {
  printf '/* Generated by gen-typed-faces.sh; do not edit. */\n'
  if [ -n "$prelude" ]; then
    printf '#include "%s"\n' "$prelude"
  else
    sed -n '/^cat > "\$tmp\/probe\.c"/,/^EOF$/p' "$here/derive-sigclass.sh" \
    | sed '1d;$d'
    printf '\n/* The unlisted fp rows use two types no installed header provides:\n'
    printf ' * the xdr pair from the headers the tree ships but the host does\n'
    printf ' * not install. bool_t is int there; XDR only ever crosses here\n'
    printf ' * behind a pointer, so an incomplete struct carries it. */\n'
    printf 'typedef int bool_t;\n'
    printf 'typedef struct __rpc_xdr XDR;\n'
  fi
  awk -F'\t' -v face="$face" -v unl="$unlisted" '
    BEGIN {
      n = 0
      while ((getline line < face) > 0) {
        split(line, f, "\t")
        if (f[2] == "sv2ms") target[f[1]] = f[4]
      }
      while ((getline line < unl) > 0) {
        split(line, f, "\t")
        ucls[f[1]] = f[2]; uproto[f[1]] = f[3]
      }
    }
    $2 == "unlisted" && (ucls[$1] == "fp" || ucls[$1] == "aggr") {
      $2 = ucls[$1]; $3 = uproto[$1]
    }
    $2 != "fp" && $2 != "aggr" { next }
    {
      name = $1; p = $3
      i = index(p, name " (")
      if (i == 0) {
        printf "gen-typed-faces: no \"%s (\" in: %s\n", name, p > "/dev/stderr"
        exit 1
      }
      ret = substr(p, 1, i - 1)
      sub(/[ \t]+$/, "", ret)
      args = substr(p, i + length(name) + 2)
      sub(/\)[ \t]*$/, "", args)
      sub(/^[ \t]+/, "", args); sub(/[ \t]+$/, "", args)
      if (args ~ /[(\[]/ || args ~ /\.\.\./) {
        printf "gen-typed-faces: unhandled shape in %s: %s\n", name, p > "/dev/stderr"
        exit 1
      }
      if (args == "" || args == "void") {
        decl = "void"; call = ""
      } else {
        na = split(args, a, /, /)
        decl = ""; call = ""
        for (j = 1; j <= na; j++) {
          t = a[j]
          sub(/[ \t]+$/, "", t)
          decl = decl (j > 1 ? ", " : "") t " a" j
          call = call (j > 1 ? ", " : "") "a" j
        }
      }
      body = "__body_" name
      printf "\nextern %s %s (%s) __asm__(\"%s\");\n", ret, body, decl, target[name]
      printf "__attribute__((sysv_abi)) %s __face_%s (%s)\n", ret, name, decl
      printf "{ %s%s (%s); }\n", (ret == "void" ? "" : "return "), body, call
    }
  ' "$sigclass"
}

if [ "$out" = - ]; then gen; else gen > "$out"; fi
