/* Generated by gen-typed-faces.sh; do not edit. */
#define _GNU_SOURCE 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <unistd.h>
#include <fcntl.h>
#include <signal.h>
#include <time.h>
#include <math.h>
#include <complex.h>
#include <ctype.h>
#include <wchar.h>
#include <wctype.h>
#include <locale.h>
#include <setjmp.h>
#include <stdarg.h>
#include <dirent.h>
#include <dlfcn.h>
#include <errno.h>
#include <glob.h>
#include <grp.h>
#include <pwd.h>
#include <iconv.h>
#include <langinfo.h>
#include <libgen.h>
#include <malloc.h>
#include <mntent.h>
#include <netdb.h>
#include <nl_types.h>
#include <poll.h>
#include <pthread.h>
#include <regex.h>
#include <sched.h>
#include <search.h>
#include <semaphore.h>
#include <spawn.h>
#include <termios.h>
#include <utime.h>
#include <utmp.h>
#include <utmpx.h>
#include <wordexp.h>
#include <aio.h>
#include <fenv.h>
#include <fnmatch.h>
#include <ftw.h>
#include <fts.h>
#include <inttypes.h>
#include <mqueue.h>
#include <monetary.h>
#include <ucontext.h>
#include <envz.h>
#include <argz.h>
#include <err.h>
#include <error.h>
#include <getopt.h>
#include <ifaddrs.h>
#include <memory.h>
#include <paths.h>
#include <resolv.h>
#include <stdio_ext.h>
#include <syslog.h>
#include <sys/acl.h>
#include <sys/cygwin.h>
#include <sys/file.h>
#include <sys/ioctl.h>
#include <sys/ipc.h>
#include <sys/mman.h>
#include <sys/msg.h>
#include <sys/mount.h>
#include <sys/quota.h>
#include <sys/random.h>
#include <sys/reent.h>
#include <sys/resource.h>
#include <sys/select.h>
#include <sys/sem.h>
#include <sys/shm.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/statfs.h>
#include <sys/statvfs.h>
#include <sys/sysinfo.h>
#include <sys/time.h>
#include <sys/timeb.h>
#include <sys/times.h>
#include <sys/uio.h>
#include <sys/un.h>
#include <sys/utsname.h>
#include <sys/wait.h>
#include <sys/xattr.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <arpa/nameser.h>

extern int __body___fpclassifyd (double a1) __asm__("__fpclassifyd");
__attribute__((sysv_abi)) int __face___fpclassifyd (double a1)
{ return __body___fpclassifyd (a1); }

extern int __body___fpclassifyf (float a1) __asm__("__fpclassifyf");
__attribute__((sysv_abi)) int __face___fpclassifyf (float a1)
{ return __body___fpclassifyf (a1); }

extern int __body___isinfd (double a1) __asm__("isinf");
__attribute__((sysv_abi)) int __face___isinfd (double a1)
{ return __body___isinfd (a1); }

extern int __body___isinff (float a1) __asm__("isinff");
__attribute__((sysv_abi)) int __face___isinff (float a1)
{ return __body___isinff (a1); }

extern int __body___isnand (double a1) __asm__("isnan");
__attribute__((sysv_abi)) int __face___isnand (double a1)
{ return __body___isnand (a1); }

extern int __body___isnanf (float a1) __asm__("isnanf");
__attribute__((sysv_abi)) int __face___isnanf (float a1)
{ return __body___isnanf (a1); }

extern int __body___signbitd (double a1) __asm__("__signbitd");
__attribute__((sysv_abi)) int __face___signbitd (double a1)
{ return __body___signbitd (a1); }

extern int __body___signbitf (float a1) __asm__("__signbitf");
__attribute__((sysv_abi)) int __face___signbitf (float a1)
{ return __body___signbitf (a1); }

extern double __body_acos (double a1) __asm__("acos");
__attribute__((sysv_abi)) double __face_acos (double a1)
{ return __body_acos (a1); }

extern float __body_acosf (float a1) __asm__("acosf");
__attribute__((sysv_abi)) float __face_acosf (float a1)
{ return __body_acosf (a1); }

extern double __body_acosh (double a1) __asm__("acosh");
__attribute__((sysv_abi)) double __face_acosh (double a1)
{ return __body_acosh (a1); }

extern float __body_acoshf (float a1) __asm__("acoshf");
__attribute__((sysv_abi)) float __face_acoshf (float a1)
{ return __body_acoshf (a1); }

extern long double __body_acoshl (long double a1) __asm__("acoshl");
__attribute__((sysv_abi)) long double __face_acoshl (long double a1)
{ return __body_acoshl (a1); }

extern long double __body_acosl (long double a1) __asm__("acosl");
__attribute__((sysv_abi)) long double __face_acosl (long double a1)
{ return __body_acosl (a1); }

extern double __body_asin (double a1) __asm__("asin");
__attribute__((sysv_abi)) double __face_asin (double a1)
{ return __body_asin (a1); }

extern float __body_asinf (float a1) __asm__("asinf");
__attribute__((sysv_abi)) float __face_asinf (float a1)
{ return __body_asinf (a1); }

extern double __body_asinh (double a1) __asm__("asinh");
__attribute__((sysv_abi)) double __face_asinh (double a1)
{ return __body_asinh (a1); }

extern float __body_asinhf (float a1) __asm__("asinhf");
__attribute__((sysv_abi)) float __face_asinhf (float a1)
{ return __body_asinhf (a1); }

extern long double __body_asinhl (long double a1) __asm__("asinhl");
__attribute__((sysv_abi)) long double __face_asinhl (long double a1)
{ return __body_asinhl (a1); }

extern long double __body_asinl (long double a1) __asm__("asinl");
__attribute__((sysv_abi)) long double __face_asinl (long double a1)
{ return __body_asinl (a1); }

extern double __body_atan (double a1) __asm__("atan");
__attribute__((sysv_abi)) double __face_atan (double a1)
{ return __body_atan (a1); }

extern double __body_atan2 (double a1, double a2) __asm__("atan2");
__attribute__((sysv_abi)) double __face_atan2 (double a1, double a2)
{ return __body_atan2 (a1, a2); }

extern float __body_atan2f (float a1, float a2) __asm__("atan2f");
__attribute__((sysv_abi)) float __face_atan2f (float a1, float a2)
{ return __body_atan2f (a1, a2); }

extern long double __body_atan2l (long double a1, long double a2) __asm__("atan2l");
__attribute__((sysv_abi)) long double __face_atan2l (long double a1, long double a2)
{ return __body_atan2l (a1, a2); }

extern float __body_atanf (float a1) __asm__("atanf");
__attribute__((sysv_abi)) float __face_atanf (float a1)
{ return __body_atanf (a1); }

extern double __body_atanh (double a1) __asm__("atanh");
__attribute__((sysv_abi)) double __face_atanh (double a1)
{ return __body_atanh (a1); }

extern float __body_atanhf (float a1) __asm__("atanhf");
__attribute__((sysv_abi)) float __face_atanhf (float a1)
{ return __body_atanhf (a1); }

extern long double __body_atanhl (long double a1) __asm__("atanhl");
__attribute__((sysv_abi)) long double __face_atanhl (long double a1)
{ return __body_atanhl (a1); }

extern long double __body_atanl (long double a1) __asm__("atanl");
__attribute__((sysv_abi)) long double __face_atanl (long double a1)
{ return __body_atanl (a1); }

extern double __body_atof (const char * a1) __asm__("atof");
__attribute__((sysv_abi)) double __face_atof (const char * a1)
{ return __body_atof (a1); }

extern float __body_atoff (const char * a1) __asm__("atoff");
__attribute__((sysv_abi)) float __face_atoff (const char * a1)
{ return __body_atoff (a1); }

extern double __body_cabs (complex double a1) __asm__("cabs");
__attribute__((sysv_abi)) double __face_cabs (complex double a1)
{ return __body_cabs (a1); }

extern float __body_cabsf (complex float a1) __asm__("cabsf");
__attribute__((sysv_abi)) float __face_cabsf (complex float a1)
{ return __body_cabsf (a1); }

extern long double __body_cabsl (complex long double a1) __asm__("cabsl");
__attribute__((sysv_abi)) long double __face_cabsl (complex long double a1)
{ return __body_cabsl (a1); }

extern complex double __body_cacos (complex double a1) __asm__("cacos");
__attribute__((sysv_abi)) complex double __face_cacos (complex double a1)
{ return __body_cacos (a1); }

extern complex float __body_cacosf (complex float a1) __asm__("cacosf");
__attribute__((sysv_abi)) complex float __face_cacosf (complex float a1)
{ return __body_cacosf (a1); }

extern complex double __body_cacosh (complex double a1) __asm__("cacosh");
__attribute__((sysv_abi)) complex double __face_cacosh (complex double a1)
{ return __body_cacosh (a1); }

extern complex float __body_cacoshf (complex float a1) __asm__("cacoshf");
__attribute__((sysv_abi)) complex float __face_cacoshf (complex float a1)
{ return __body_cacoshf (a1); }

extern complex long double __body_cacoshl (complex long double a1) __asm__("cacoshl");
__attribute__((sysv_abi)) complex long double __face_cacoshl (complex long double a1)
{ return __body_cacoshl (a1); }

extern complex long double __body_cacosl (complex long double a1) __asm__("cacosl");
__attribute__((sysv_abi)) complex long double __face_cacosl (complex long double a1)
{ return __body_cacosl (a1); }

extern double __body_carg (complex double a1) __asm__("carg");
__attribute__((sysv_abi)) double __face_carg (complex double a1)
{ return __body_carg (a1); }

extern float __body_cargf (complex float a1) __asm__("cargf");
__attribute__((sysv_abi)) float __face_cargf (complex float a1)
{ return __body_cargf (a1); }

extern long double __body_cargl (complex long double a1) __asm__("cargl");
__attribute__((sysv_abi)) long double __face_cargl (complex long double a1)
{ return __body_cargl (a1); }

extern complex double __body_casin (complex double a1) __asm__("casin");
__attribute__((sysv_abi)) complex double __face_casin (complex double a1)
{ return __body_casin (a1); }

extern complex float __body_casinf (complex float a1) __asm__("casinf");
__attribute__((sysv_abi)) complex float __face_casinf (complex float a1)
{ return __body_casinf (a1); }

extern complex double __body_casinh (complex double a1) __asm__("casinh");
__attribute__((sysv_abi)) complex double __face_casinh (complex double a1)
{ return __body_casinh (a1); }

extern complex float __body_casinhf (complex float a1) __asm__("casinhf");
__attribute__((sysv_abi)) complex float __face_casinhf (complex float a1)
{ return __body_casinhf (a1); }

extern complex long double __body_casinhl (complex long double a1) __asm__("casinhl");
__attribute__((sysv_abi)) complex long double __face_casinhl (complex long double a1)
{ return __body_casinhl (a1); }

extern complex long double __body_casinl (complex long double a1) __asm__("casinl");
__attribute__((sysv_abi)) complex long double __face_casinl (complex long double a1)
{ return __body_casinl (a1); }

extern complex double __body_catan (complex double a1) __asm__("catan");
__attribute__((sysv_abi)) complex double __face_catan (complex double a1)
{ return __body_catan (a1); }

extern complex float __body_catanf (complex float a1) __asm__("catanf");
__attribute__((sysv_abi)) complex float __face_catanf (complex float a1)
{ return __body_catanf (a1); }

extern complex double __body_catanh (complex double a1) __asm__("catanh");
__attribute__((sysv_abi)) complex double __face_catanh (complex double a1)
{ return __body_catanh (a1); }

extern complex float __body_catanhf (complex float a1) __asm__("catanhf");
__attribute__((sysv_abi)) complex float __face_catanhf (complex float a1)
{ return __body_catanhf (a1); }

extern complex long double __body_catanhl (complex long double a1) __asm__("catanhl");
__attribute__((sysv_abi)) complex long double __face_catanhl (complex long double a1)
{ return __body_catanhl (a1); }

extern complex long double __body_catanl (complex long double a1) __asm__("catanl");
__attribute__((sysv_abi)) complex long double __face_catanl (complex long double a1)
{ return __body_catanl (a1); }

extern double __body_cbrt (double a1) __asm__("cbrt");
__attribute__((sysv_abi)) double __face_cbrt (double a1)
{ return __body_cbrt (a1); }

extern float __body_cbrtf (float a1) __asm__("cbrtf");
__attribute__((sysv_abi)) float __face_cbrtf (float a1)
{ return __body_cbrtf (a1); }

extern long double __body_cbrtl (long double a1) __asm__("cbrtl");
__attribute__((sysv_abi)) long double __face_cbrtl (long double a1)
{ return __body_cbrtl (a1); }

extern complex double __body_ccos (complex double a1) __asm__("ccos");
__attribute__((sysv_abi)) complex double __face_ccos (complex double a1)
{ return __body_ccos (a1); }

extern complex float __body_ccosf (complex float a1) __asm__("ccosf");
__attribute__((sysv_abi)) complex float __face_ccosf (complex float a1)
{ return __body_ccosf (a1); }

extern complex double __body_ccosh (complex double a1) __asm__("ccosh");
__attribute__((sysv_abi)) complex double __face_ccosh (complex double a1)
{ return __body_ccosh (a1); }

extern complex float __body_ccoshf (complex float a1) __asm__("ccoshf");
__attribute__((sysv_abi)) complex float __face_ccoshf (complex float a1)
{ return __body_ccoshf (a1); }

extern complex long double __body_ccoshl (complex long double a1) __asm__("ccoshl");
__attribute__((sysv_abi)) complex long double __face_ccoshl (complex long double a1)
{ return __body_ccoshl (a1); }

extern complex long double __body_ccosl (complex long double a1) __asm__("ccosl");
__attribute__((sysv_abi)) complex long double __face_ccosl (complex long double a1)
{ return __body_ccosl (a1); }

extern double __body_ceil (double a1) __asm__("ceil");
__attribute__((sysv_abi)) double __face_ceil (double a1)
{ return __body_ceil (a1); }

extern float __body_ceilf (float a1) __asm__("ceilf");
__attribute__((sysv_abi)) float __face_ceilf (float a1)
{ return __body_ceilf (a1); }

extern long double __body_ceill (long double a1) __asm__("ceill");
__attribute__((sysv_abi)) long double __face_ceill (long double a1)
{ return __body_ceill (a1); }

extern complex double __body_cexp (complex double a1) __asm__("cexp");
__attribute__((sysv_abi)) complex double __face_cexp (complex double a1)
{ return __body_cexp (a1); }

extern complex float __body_cexpf (complex float a1) __asm__("cexpf");
__attribute__((sysv_abi)) complex float __face_cexpf (complex float a1)
{ return __body_cexpf (a1); }

extern complex long double __body_cexpl (complex long double a1) __asm__("cexpl");
__attribute__((sysv_abi)) complex long double __face_cexpl (complex long double a1)
{ return __body_cexpl (a1); }

extern double __body_cimag (complex double a1) __asm__("cimag");
__attribute__((sysv_abi)) double __face_cimag (complex double a1)
{ return __body_cimag (a1); }

extern float __body_cimagf (complex float a1) __asm__("cimagf");
__attribute__((sysv_abi)) float __face_cimagf (complex float a1)
{ return __body_cimagf (a1); }

extern long double __body_cimagl (complex long double a1) __asm__("cimagl");
__attribute__((sysv_abi)) long double __face_cimagl (complex long double a1)
{ return __body_cimagl (a1); }

extern complex double __body_clog (complex double a1) __asm__("clog");
__attribute__((sysv_abi)) complex double __face_clog (complex double a1)
{ return __body_clog (a1); }

extern complex double __body_clog10 (complex double a1) __asm__("clog10");
__attribute__((sysv_abi)) complex double __face_clog10 (complex double a1)
{ return __body_clog10 (a1); }

extern complex float __body_clog10f (complex float a1) __asm__("clog10f");
__attribute__((sysv_abi)) complex float __face_clog10f (complex float a1)
{ return __body_clog10f (a1); }

extern complex long double __body_clog10l (complex long double a1) __asm__("clog10l");
__attribute__((sysv_abi)) complex long double __face_clog10l (complex long double a1)
{ return __body_clog10l (a1); }

extern complex float __body_clogf (complex float a1) __asm__("clogf");
__attribute__((sysv_abi)) complex float __face_clogf (complex float a1)
{ return __body_clogf (a1); }

extern complex long double __body_clogl (complex long double a1) __asm__("clogl");
__attribute__((sysv_abi)) complex long double __face_clogl (complex long double a1)
{ return __body_clogl (a1); }

extern complex double __body_conj (complex double a1) __asm__("conj");
__attribute__((sysv_abi)) complex double __face_conj (complex double a1)
{ return __body_conj (a1); }

extern complex float __body_conjf (complex float a1) __asm__("conjf");
__attribute__((sysv_abi)) complex float __face_conjf (complex float a1)
{ return __body_conjf (a1); }

extern complex long double __body_conjl (complex long double a1) __asm__("conjl");
__attribute__((sysv_abi)) complex long double __face_conjl (complex long double a1)
{ return __body_conjl (a1); }

extern double __body_copysign (double a1, double a2) __asm__("copysign");
__attribute__((sysv_abi)) double __face_copysign (double a1, double a2)
{ return __body_copysign (a1, a2); }

extern float __body_copysignf (float a1, float a2) __asm__("copysignf");
__attribute__((sysv_abi)) float __face_copysignf (float a1, float a2)
{ return __body_copysignf (a1, a2); }

extern long double __body_copysignl (long double a1, long double a2) __asm__("copysignl");
__attribute__((sysv_abi)) long double __face_copysignl (long double a1, long double a2)
{ return __body_copysignl (a1, a2); }

extern double __body_cos (double a1) __asm__("cos");
__attribute__((sysv_abi)) double __face_cos (double a1)
{ return __body_cos (a1); }

extern float __body_cosf (float a1) __asm__("cosf");
__attribute__((sysv_abi)) float __face_cosf (float a1)
{ return __body_cosf (a1); }

extern double __body_cosh (double a1) __asm__("cosh");
__attribute__((sysv_abi)) double __face_cosh (double a1)
{ return __body_cosh (a1); }

extern float __body_coshf (float a1) __asm__("coshf");
__attribute__((sysv_abi)) float __face_coshf (float a1)
{ return __body_coshf (a1); }

extern long double __body_coshl (long double a1) __asm__("coshl");
__attribute__((sysv_abi)) long double __face_coshl (long double a1)
{ return __body_coshl (a1); }

extern long double __body_cosl (long double a1) __asm__("cosl");
__attribute__((sysv_abi)) long double __face_cosl (long double a1)
{ return __body_cosl (a1); }

extern complex double __body_cpow (complex double a1, complex double a2) __asm__("cpow");
__attribute__((sysv_abi)) complex double __face_cpow (complex double a1, complex double a2)
{ return __body_cpow (a1, a2); }

extern complex float __body_cpowf (complex float a1, complex float a2) __asm__("cpowf");
__attribute__((sysv_abi)) complex float __face_cpowf (complex float a1, complex float a2)
{ return __body_cpowf (a1, a2); }

extern complex long double __body_cpowl (complex long double a1, complex long double a2) __asm__("cpowl");
__attribute__((sysv_abi)) complex long double __face_cpowl (complex long double a1, complex long double a2)
{ return __body_cpowl (a1, a2); }

extern complex double __body_cproj (complex double a1) __asm__("cproj");
__attribute__((sysv_abi)) complex double __face_cproj (complex double a1)
{ return __body_cproj (a1); }

extern complex float __body_cprojf (complex float a1) __asm__("cprojf");
__attribute__((sysv_abi)) complex float __face_cprojf (complex float a1)
{ return __body_cprojf (a1); }

extern complex long double __body_cprojl (complex long double a1) __asm__("cprojl");
__attribute__((sysv_abi)) complex long double __face_cprojl (complex long double a1)
{ return __body_cprojl (a1); }

extern double __body_creal (complex double a1) __asm__("creal");
__attribute__((sysv_abi)) double __face_creal (complex double a1)
{ return __body_creal (a1); }

extern float __body_crealf (complex float a1) __asm__("crealf");
__attribute__((sysv_abi)) float __face_crealf (complex float a1)
{ return __body_crealf (a1); }

extern long double __body_creall (complex long double a1) __asm__("creall");
__attribute__((sysv_abi)) long double __face_creall (complex long double a1)
{ return __body_creall (a1); }

extern complex double __body_csin (complex double a1) __asm__("csin");
__attribute__((sysv_abi)) complex double __face_csin (complex double a1)
{ return __body_csin (a1); }

extern complex float __body_csinf (complex float a1) __asm__("csinf");
__attribute__((sysv_abi)) complex float __face_csinf (complex float a1)
{ return __body_csinf (a1); }

extern complex double __body_csinh (complex double a1) __asm__("csinh");
__attribute__((sysv_abi)) complex double __face_csinh (complex double a1)
{ return __body_csinh (a1); }

extern complex float __body_csinhf (complex float a1) __asm__("csinhf");
__attribute__((sysv_abi)) complex float __face_csinhf (complex float a1)
{ return __body_csinhf (a1); }

extern complex long double __body_csinhl (complex long double a1) __asm__("csinhl");
__attribute__((sysv_abi)) complex long double __face_csinhl (complex long double a1)
{ return __body_csinhl (a1); }

extern complex long double __body_csinl (complex long double a1) __asm__("csinl");
__attribute__((sysv_abi)) complex long double __face_csinl (complex long double a1)
{ return __body_csinl (a1); }

extern complex double __body_csqrt (complex double a1) __asm__("csqrt");
__attribute__((sysv_abi)) complex double __face_csqrt (complex double a1)
{ return __body_csqrt (a1); }

extern complex float __body_csqrtf (complex float a1) __asm__("csqrtf");
__attribute__((sysv_abi)) complex float __face_csqrtf (complex float a1)
{ return __body_csqrtf (a1); }

extern complex long double __body_csqrtl (complex long double a1) __asm__("csqrtl");
__attribute__((sysv_abi)) complex long double __face_csqrtl (complex long double a1)
{ return __body_csqrtl (a1); }

extern complex double __body_ctan (complex double a1) __asm__("ctan");
__attribute__((sysv_abi)) complex double __face_ctan (complex double a1)
{ return __body_ctan (a1); }

extern complex float __body_ctanf (complex float a1) __asm__("ctanf");
__attribute__((sysv_abi)) complex float __face_ctanf (complex float a1)
{ return __body_ctanf (a1); }

extern complex double __body_ctanh (complex double a1) __asm__("ctanh");
__attribute__((sysv_abi)) complex double __face_ctanh (complex double a1)
{ return __body_ctanh (a1); }

extern complex float __body_ctanhf (complex float a1) __asm__("ctanhf");
__attribute__((sysv_abi)) complex float __face_ctanhf (complex float a1)
{ return __body_ctanhf (a1); }

extern complex long double __body_ctanhl (complex long double a1) __asm__("ctanhl");
__attribute__((sysv_abi)) complex long double __face_ctanhl (complex long double a1)
{ return __body_ctanhl (a1); }

extern complex long double __body_ctanl (complex long double a1) __asm__("ctanl");
__attribute__((sysv_abi)) complex long double __face_ctanl (complex long double a1)
{ return __body_ctanl (a1); }

extern double __body_difftime (time_t a1, time_t a2) __asm__("difftime");
__attribute__((sysv_abi)) double __face_difftime (time_t a1, time_t a2)
{ return __body_difftime (a1, a2); }

extern div_t __body_div (int a1, int a2) __asm__("div");
__attribute__((sysv_abi)) div_t __face_div (int a1, int a2)
{ return __body_div (a1, a2); }

extern double __body_drand48 (void) __asm__("drand48");
__attribute__((sysv_abi)) double __face_drand48 (void)
{ return __body_drand48 (); }

extern double __body_drem (double a1, double a2) __asm__("remainder");
__attribute__((sysv_abi)) double __face_drem (double a1, double a2)
{ return __body_drem (a1, a2); }

extern float __body_dremf (float a1, float a2) __asm__("remainderf");
__attribute__((sysv_abi)) float __face_dremf (float a1, float a2)
{ return __body_dremf (a1, a2); }

extern float __body_dreml (long double a1, long double a2) __asm__("remainderl");
__attribute__((sysv_abi)) float __face_dreml (long double a1, long double a2)
{ return __body_dreml (a1, a2); }

extern double __body_erand48 (short unsigned int * a1) __asm__("erand48");
__attribute__((sysv_abi)) double __face_erand48 (short unsigned int * a1)
{ return __body_erand48 (a1); }

extern double __body_erf (double a1) __asm__("erf");
__attribute__((sysv_abi)) double __face_erf (double a1)
{ return __body_erf (a1); }

extern double __body_erfc (double a1) __asm__("erfc");
__attribute__((sysv_abi)) double __face_erfc (double a1)
{ return __body_erfc (a1); }

extern float __body_erfcf (float a1) __asm__("erfcf");
__attribute__((sysv_abi)) float __face_erfcf (float a1)
{ return __body_erfcf (a1); }

extern long double __body_erfcl (long double a1) __asm__("erfcl");
__attribute__((sysv_abi)) long double __face_erfcl (long double a1)
{ return __body_erfcl (a1); }

extern float __body_erff (float a1) __asm__("erff");
__attribute__((sysv_abi)) float __face_erff (float a1)
{ return __body_erff (a1); }

extern long double __body_erfl (long double a1) __asm__("erfl");
__attribute__((sysv_abi)) long double __face_erfl (long double a1)
{ return __body_erfl (a1); }

extern double __body_exp (double a1) __asm__("exp");
__attribute__((sysv_abi)) double __face_exp (double a1)
{ return __body_exp (a1); }

extern double __body_exp10 (double a1) __asm__("exp10");
__attribute__((sysv_abi)) double __face_exp10 (double a1)
{ return __body_exp10 (a1); }

extern float __body_exp10f (float a1) __asm__("exp10f");
__attribute__((sysv_abi)) float __face_exp10f (float a1)
{ return __body_exp10f (a1); }

extern float __body_exp10l (float a1) __asm__("exp10l");
__attribute__((sysv_abi)) float __face_exp10l (float a1)
{ return __body_exp10l (a1); }

extern double __body_exp2 (double a1) __asm__("exp2");
__attribute__((sysv_abi)) double __face_exp2 (double a1)
{ return __body_exp2 (a1); }

extern float __body_exp2f (float a1) __asm__("exp2f");
__attribute__((sysv_abi)) float __face_exp2f (float a1)
{ return __body_exp2f (a1); }

extern long double __body_exp2l (long double a1) __asm__("exp2l");
__attribute__((sysv_abi)) long double __face_exp2l (long double a1)
{ return __body_exp2l (a1); }

extern float __body_expf (float a1) __asm__("expf");
__attribute__((sysv_abi)) float __face_expf (float a1)
{ return __body_expf (a1); }

extern long double __body_expl (long double a1) __asm__("expl");
__attribute__((sysv_abi)) long double __face_expl (long double a1)
{ return __body_expl (a1); }

extern double __body_expm1 (double a1) __asm__("expm1");
__attribute__((sysv_abi)) double __face_expm1 (double a1)
{ return __body_expm1 (a1); }

extern float __body_expm1f (float a1) __asm__("expm1f");
__attribute__((sysv_abi)) float __face_expm1f (float a1)
{ return __body_expm1f (a1); }

extern long double __body_expm1l (long double a1) __asm__("expm1l");
__attribute__((sysv_abi)) long double __face_expm1l (long double a1)
{ return __body_expm1l (a1); }

extern double __body_fabs (double a1) __asm__("fabs");
__attribute__((sysv_abi)) double __face_fabs (double a1)
{ return __body_fabs (a1); }

extern float __body_fabsf (float a1) __asm__("fabsf");
__attribute__((sysv_abi)) float __face_fabsf (float a1)
{ return __body_fabsf (a1); }

extern long double __body_fabsl (long double a1) __asm__("fabsl");
__attribute__((sysv_abi)) long double __face_fabsl (long double a1)
{ return __body_fabsl (a1); }

extern double __body_fdim (double a1, double a2) __asm__("fdim");
__attribute__((sysv_abi)) double __face_fdim (double a1, double a2)
{ return __body_fdim (a1, a2); }

extern float __body_fdimf (float a1, float a2) __asm__("fdimf");
__attribute__((sysv_abi)) float __face_fdimf (float a1, float a2)
{ return __body_fdimf (a1, a2); }

extern long double __body_fdiml (long double a1, long double a2) __asm__("fdiml");
__attribute__((sysv_abi)) long double __face_fdiml (long double a1, long double a2)
{ return __body_fdiml (a1, a2); }

extern int __body_finite (double a1) __asm__("finite");
__attribute__((sysv_abi)) int __face_finite (double a1)
{ return __body_finite (a1); }

extern int __body_finitef (float a1) __asm__("finitef");
__attribute__((sysv_abi)) int __face_finitef (float a1)
{ return __body_finitef (a1); }

extern int __body_finitel (long double a1) __asm__("finitel");
__attribute__((sysv_abi)) int __face_finitel (long double a1)
{ return __body_finitel (a1); }

extern double __body_floor (double a1) __asm__("floor");
__attribute__((sysv_abi)) double __face_floor (double a1)
{ return __body_floor (a1); }

extern float __body_floorf (float a1) __asm__("floorf");
__attribute__((sysv_abi)) float __face_floorf (float a1)
{ return __body_floorf (a1); }

extern long double __body_floorl (long double a1) __asm__("floorl");
__attribute__((sysv_abi)) long double __face_floorl (long double a1)
{ return __body_floorl (a1); }

extern double __body_fma (double a1, double a2, double a3) __asm__("fma");
__attribute__((sysv_abi)) double __face_fma (double a1, double a2, double a3)
{ return __body_fma (a1, a2, a3); }

extern float __body_fmaf (float a1, float a2, float a3) __asm__("fmaf");
__attribute__((sysv_abi)) float __face_fmaf (float a1, float a2, float a3)
{ return __body_fmaf (a1, a2, a3); }

extern long double __body_fmal (long double a1, long double a2, long double a3) __asm__("fmal");
__attribute__((sysv_abi)) long double __face_fmal (long double a1, long double a2, long double a3)
{ return __body_fmal (a1, a2, a3); }

extern double __body_fmax (double a1, double a2) __asm__("fmax");
__attribute__((sysv_abi)) double __face_fmax (double a1, double a2)
{ return __body_fmax (a1, a2); }

extern float __body_fmaxf (float a1, float a2) __asm__("fmaxf");
__attribute__((sysv_abi)) float __face_fmaxf (float a1, float a2)
{ return __body_fmaxf (a1, a2); }

extern long double __body_fmaxl (long double a1, long double a2) __asm__("fmaxl");
__attribute__((sysv_abi)) long double __face_fmaxl (long double a1, long double a2)
{ return __body_fmaxl (a1, a2); }

extern double __body_fmin (double a1, double a2) __asm__("fmin");
__attribute__((sysv_abi)) double __face_fmin (double a1, double a2)
{ return __body_fmin (a1, a2); }

extern float __body_fminf (float a1, float a2) __asm__("fminf");
__attribute__((sysv_abi)) float __face_fminf (float a1, float a2)
{ return __body_fminf (a1, a2); }

extern long double __body_fminl (long double a1, long double a2) __asm__("fminl");
__attribute__((sysv_abi)) long double __face_fminl (long double a1, long double a2)
{ return __body_fminl (a1, a2); }

extern double __body_fmod (double a1, double a2) __asm__("fmod");
__attribute__((sysv_abi)) double __face_fmod (double a1, double a2)
{ return __body_fmod (a1, a2); }

extern float __body_fmodf (float a1, float a2) __asm__("fmodf");
__attribute__((sysv_abi)) float __face_fmodf (float a1, float a2)
{ return __body_fmodf (a1, a2); }

extern long double __body_fmodl (long double a1, long double a2) __asm__("fmodl");
__attribute__((sysv_abi)) long double __face_fmodl (long double a1, long double a2)
{ return __body_fmodl (a1, a2); }

extern double __body_frexp (double a1, int * a2) __asm__("frexp");
__attribute__((sysv_abi)) double __face_frexp (double a1, int * a2)
{ return __body_frexp (a1, a2); }

extern float __body_frexpf (float a1, int * a2) __asm__("frexpf");
__attribute__((sysv_abi)) float __face_frexpf (float a1, int * a2)
{ return __body_frexpf (a1, a2); }

extern long double __body_frexpl (long double a1, int * a2) __asm__("frexpl");
__attribute__((sysv_abi)) long double __face_frexpl (long double a1, int * a2)
{ return __body_frexpl (a1, a2); }

extern double __body_gamma (double a1) __asm__("gamma");
__attribute__((sysv_abi)) double __face_gamma (double a1)
{ return __body_gamma (a1); }

extern double __body_gamma_r (double a1, int * a2) __asm__("gamma_r");
__attribute__((sysv_abi)) double __face_gamma_r (double a1, int * a2)
{ return __body_gamma_r (a1, a2); }

extern float __body_gammaf (float a1) __asm__("gammaf");
__attribute__((sysv_abi)) float __face_gammaf (float a1)
{ return __body_gammaf (a1); }

extern float __body_gammaf_r (float a1, int * a2) __asm__("gammaf_r");
__attribute__((sysv_abi)) float __face_gammaf_r (float a1, int * a2)
{ return __body_gammaf_r (a1, a2); }

extern int __body_getloadavg (double * a1, int a2) __asm__("getloadavg");
__attribute__((sysv_abi)) int __face_getloadavg (double * a1, int a2)
{ return __body_getloadavg (a1, a2); }

extern double __body_hypot (double a1, double a2) __asm__("hypot");
__attribute__((sysv_abi)) double __face_hypot (double a1, double a2)
{ return __body_hypot (a1, a2); }

extern float __body_hypotf (float a1, float a2) __asm__("hypotf");
__attribute__((sysv_abi)) float __face_hypotf (float a1, float a2)
{ return __body_hypotf (a1, a2); }

extern long double __body_hypotl (long double a1, long double a2) __asm__("hypotl");
__attribute__((sysv_abi)) long double __face_hypotl (long double a1, long double a2)
{ return __body_hypotl (a1, a2); }

extern int __body_ilogb (double a1) __asm__("ilogb");
__attribute__((sysv_abi)) int __face_ilogb (double a1)
{ return __body_ilogb (a1); }

extern int __body_ilogbf (float a1) __asm__("ilogbf");
__attribute__((sysv_abi)) int __face_ilogbf (float a1)
{ return __body_ilogbf (a1); }

extern int __body_ilogbl (long double a1) __asm__("ilogbl");
__attribute__((sysv_abi)) int __face_ilogbl (long double a1)
{ return __body_ilogbl (a1); }

extern imaxdiv_t __body_imaxdiv (intmax_t a1, intmax_t a2) __asm__("lldiv");
__attribute__((sysv_abi)) imaxdiv_t __face_imaxdiv (intmax_t a1, intmax_t a2)
{ return __body_imaxdiv (a1, a2); }

extern struct in_addr __body_inet_makeaddr (long unsigned int a1, long unsigned int a2) __asm__("inet_makeaddr");
__attribute__((sysv_abi)) struct in_addr __face_inet_makeaddr (long unsigned int a1, long unsigned int a2)
{ return __body_inet_makeaddr (a1, a2); }

extern in_addr_t __body_inet_netof (struct in_addr a1) __asm__("inet_netof");
__attribute__((sysv_abi)) in_addr_t __face_inet_netof (struct in_addr a1)
{ return __body_inet_netof (a1); }

extern char * __body_inet_ntoa (struct in_addr a1) __asm__("cygwin_inet_ntoa");
__attribute__((sysv_abi)) char * __face_inet_ntoa (struct in_addr a1)
{ return __body_inet_ntoa (a1); }

extern double __body_infinity (void) __asm__("infinity");
__attribute__((sysv_abi)) double __face_infinity (void)
{ return __body_infinity (); }

extern float __body_infinityf (void) __asm__("infinityf");
__attribute__((sysv_abi)) float __face_infinityf (void)
{ return __body_infinityf (); }

extern int __body_isinf (double a1) __asm__("isinf");
__attribute__((sysv_abi)) int __face_isinf (double a1)
{ return __body_isinf (a1); }

extern int __body_isinff (float a1) __asm__("isinff");
__attribute__((sysv_abi)) int __face_isinff (float a1)
{ return __body_isinff (a1); }

extern int __body_isinfl (long double a1) __asm__("isinfl");
__attribute__((sysv_abi)) int __face_isinfl (long double a1)
{ return __body_isinfl (a1); }

extern int __body_isnan (double a1) __asm__("isnan");
__attribute__((sysv_abi)) int __face_isnan (double a1)
{ return __body_isnan (a1); }

extern int __body_isnanf (float a1) __asm__("isnanf");
__attribute__((sysv_abi)) int __face_isnanf (float a1)
{ return __body_isnanf (a1); }

extern int __body_isnanl (long double a1) __asm__("isnanl");
__attribute__((sysv_abi)) int __face_isnanl (long double a1)
{ return __body_isnanl (a1); }

extern double __body_j0 (double a1) __asm__("j0");
__attribute__((sysv_abi)) double __face_j0 (double a1)
{ return __body_j0 (a1); }

extern float __body_j0f (float a1) __asm__("j0f");
__attribute__((sysv_abi)) float __face_j0f (float a1)
{ return __body_j0f (a1); }

extern double __body_j1 (double a1) __asm__("j1");
__attribute__((sysv_abi)) double __face_j1 (double a1)
{ return __body_j1 (a1); }

extern float __body_j1f (float a1) __asm__("j1f");
__attribute__((sysv_abi)) float __face_j1f (float a1)
{ return __body_j1f (a1); }

extern double __body_jn (int a1, double a2) __asm__("jn");
__attribute__((sysv_abi)) double __face_jn (int a1, double a2)
{ return __body_jn (a1, a2); }

extern float __body_jnf (int a1, float a2) __asm__("jnf");
__attribute__((sysv_abi)) float __face_jnf (int a1, float a2)
{ return __body_jnf (a1, a2); }

extern double __body_ldexp (double a1, int a2) __asm__("ldexp");
__attribute__((sysv_abi)) double __face_ldexp (double a1, int a2)
{ return __body_ldexp (a1, a2); }

extern float __body_ldexpf (float a1, int a2) __asm__("ldexpf");
__attribute__((sysv_abi)) float __face_ldexpf (float a1, int a2)
{ return __body_ldexpf (a1, a2); }

extern long double __body_ldexpl (long double a1, int a2) __asm__("ldexpl");
__attribute__((sysv_abi)) long double __face_ldexpl (long double a1, int a2)
{ return __body_ldexpl (a1, a2); }

extern ldiv_t __body_ldiv (long int a1, long int a2) __asm__("ldiv");
__attribute__((sysv_abi)) ldiv_t __face_ldiv (long int a1, long int a2)
{ return __body_ldiv (a1, a2); }

extern double __body_lgamma (double a1) __asm__("lgamma");
__attribute__((sysv_abi)) double __face_lgamma (double a1)
{ return __body_lgamma (a1); }

extern double __body_lgamma_r (double a1, int * a2) __asm__("lgamma_r");
__attribute__((sysv_abi)) double __face_lgamma_r (double a1, int * a2)
{ return __body_lgamma_r (a1, a2); }

extern float __body_lgammaf (float a1) __asm__("lgammaf");
__attribute__((sysv_abi)) float __face_lgammaf (float a1)
{ return __body_lgammaf (a1); }

extern float __body_lgammaf_r (float a1, int * a2) __asm__("lgammaf_r");
__attribute__((sysv_abi)) float __face_lgammaf_r (float a1, int * a2)
{ return __body_lgammaf_r (a1, a2); }

extern long double __body_lgammal (long double a1) __asm__("lgammal");
__attribute__((sysv_abi)) long double __face_lgammal (long double a1)
{ return __body_lgammal (a1); }

extern lldiv_t __body_lldiv (long long int a1, long long int a2) __asm__("lldiv");
__attribute__((sysv_abi)) lldiv_t __face_lldiv (long long int a1, long long int a2)
{ return __body_lldiv (a1, a2); }

extern long long int __body_llrint (double a1) __asm__("llrint");
__attribute__((sysv_abi)) long long int __face_llrint (double a1)
{ return __body_llrint (a1); }

extern long long int __body_llrintf (float a1) __asm__("llrintf");
__attribute__((sysv_abi)) long long int __face_llrintf (float a1)
{ return __body_llrintf (a1); }

extern long long int __body_llrintl (long double a1) __asm__("llrintl");
__attribute__((sysv_abi)) long long int __face_llrintl (long double a1)
{ return __body_llrintl (a1); }

extern long long int __body_llround (double a1) __asm__("llround");
__attribute__((sysv_abi)) long long int __face_llround (double a1)
{ return __body_llround (a1); }

extern long long int __body_llroundf (float a1) __asm__("llroundf");
__attribute__((sysv_abi)) long long int __face_llroundf (float a1)
{ return __body_llroundf (a1); }

extern long long int __body_llroundl (long double a1) __asm__("llroundl");
__attribute__((sysv_abi)) long long int __face_llroundl (long double a1)
{ return __body_llroundl (a1); }

extern double __body_log (double a1) __asm__("log");
__attribute__((sysv_abi)) double __face_log (double a1)
{ return __body_log (a1); }

extern double __body_log10 (double a1) __asm__("log10");
__attribute__((sysv_abi)) double __face_log10 (double a1)
{ return __body_log10 (a1); }

extern float __body_log10f (float a1) __asm__("log10f");
__attribute__((sysv_abi)) float __face_log10f (float a1)
{ return __body_log10f (a1); }

extern long double __body_log10l (long double a1) __asm__("log10l");
__attribute__((sysv_abi)) long double __face_log10l (long double a1)
{ return __body_log10l (a1); }

extern double __body_log1p (double a1) __asm__("log1p");
__attribute__((sysv_abi)) double __face_log1p (double a1)
{ return __body_log1p (a1); }

extern float __body_log1pf (float a1) __asm__("log1pf");
__attribute__((sysv_abi)) float __face_log1pf (float a1)
{ return __body_log1pf (a1); }

extern long double __body_log1pl (long double a1) __asm__("log1pl");
__attribute__((sysv_abi)) long double __face_log1pl (long double a1)
{ return __body_log1pl (a1); }

extern double __body_log2 (double a1) __asm__("log2");
__attribute__((sysv_abi)) double __face_log2 (double a1)
{ return __body_log2 (a1); }

extern float __body_log2f (float a1) __asm__("log2f");
__attribute__((sysv_abi)) float __face_log2f (float a1)
{ return __body_log2f (a1); }

extern long double __body_log2l (long double a1) __asm__("log2l");
__attribute__((sysv_abi)) long double __face_log2l (long double a1)
{ return __body_log2l (a1); }

extern double __body_logb (double a1) __asm__("logb");
__attribute__((sysv_abi)) double __face_logb (double a1)
{ return __body_logb (a1); }

extern float __body_logbf (float a1) __asm__("logbf");
__attribute__((sysv_abi)) float __face_logbf (float a1)
{ return __body_logbf (a1); }

extern long double __body_logbl (long double a1) __asm__("logbl");
__attribute__((sysv_abi)) long double __face_logbl (long double a1)
{ return __body_logbl (a1); }

extern float __body_logf (float a1) __asm__("logf");
__attribute__((sysv_abi)) float __face_logf (float a1)
{ return __body_logf (a1); }

extern long double __body_logl (long double a1) __asm__("logl");
__attribute__((sysv_abi)) long double __face_logl (long double a1)
{ return __body_logl (a1); }

extern long int __body_lrint (double a1) __asm__("lrint");
__attribute__((sysv_abi)) long int __face_lrint (double a1)
{ return __body_lrint (a1); }

extern long int __body_lrintf (float a1) __asm__("lrintf");
__attribute__((sysv_abi)) long int __face_lrintf (float a1)
{ return __body_lrintf (a1); }

extern long int __body_lrintl (long double a1) __asm__("lrintl");
__attribute__((sysv_abi)) long int __face_lrintl (long double a1)
{ return __body_lrintl (a1); }

extern long int __body_lround (double a1) __asm__("lround");
__attribute__((sysv_abi)) long int __face_lround (double a1)
{ return __body_lround (a1); }

extern long int __body_lroundf (float a1) __asm__("lroundf");
__attribute__((sysv_abi)) long int __face_lroundf (float a1)
{ return __body_lroundf (a1); }

extern long int __body_lroundl (long double a1) __asm__("lroundl");
__attribute__((sysv_abi)) long int __face_lroundl (long double a1)
{ return __body_lroundl (a1); }

extern struct mallinfo __body_mallinfo (void) __asm__("mallinfo");
__attribute__((sysv_abi)) struct mallinfo __face_mallinfo (void)
{ return __body_mallinfo (); }

extern double __body_modf (double a1, double * a2) __asm__("modf");
__attribute__((sysv_abi)) double __face_modf (double a1, double * a2)
{ return __body_modf (a1, a2); }

extern float __body_modff (float a1, float * a2) __asm__("modff");
__attribute__((sysv_abi)) float __face_modff (float a1, float * a2)
{ return __body_modff (a1, a2); }

extern long double __body_modfl (long double a1, long double * a2) __asm__("modfl");
__attribute__((sysv_abi)) long double __face_modfl (long double a1, long double * a2)
{ return __body_modfl (a1, a2); }

extern double __body_nan (const char * a1) __asm__("nan");
__attribute__((sysv_abi)) double __face_nan (const char * a1)
{ return __body_nan (a1); }

extern float __body_nanf (const char * a1) __asm__("nanf");
__attribute__((sysv_abi)) float __face_nanf (const char * a1)
{ return __body_nanf (a1); }

extern long double __body_nanl (const char * a1) __asm__("nanl");
__attribute__((sysv_abi)) long double __face_nanl (const char * a1)
{ return __body_nanl (a1); }

extern double __body_nearbyint (double a1) __asm__("nearbyint");
__attribute__((sysv_abi)) double __face_nearbyint (double a1)
{ return __body_nearbyint (a1); }

extern float __body_nearbyintf (float a1) __asm__("nearbyintf");
__attribute__((sysv_abi)) float __face_nearbyintf (float a1)
{ return __body_nearbyintf (a1); }

extern long double __body_nearbyintl (long double a1) __asm__("nearbyintl");
__attribute__((sysv_abi)) long double __face_nearbyintl (long double a1)
{ return __body_nearbyintl (a1); }

extern double __body_nextafter (double a1, double a2) __asm__("nextafter");
__attribute__((sysv_abi)) double __face_nextafter (double a1, double a2)
{ return __body_nextafter (a1, a2); }

extern float __body_nextafterf (float a1, float a2) __asm__("nextafterf");
__attribute__((sysv_abi)) float __face_nextafterf (float a1, float a2)
{ return __body_nextafterf (a1, a2); }

extern long double __body_nextafterl (long double a1, long double a2) __asm__("nextafterl");
__attribute__((sysv_abi)) long double __face_nextafterl (long double a1, long double a2)
{ return __body_nextafterl (a1, a2); }

extern double __body_nexttoward (double a1, long double a2) __asm__("nexttoward");
__attribute__((sysv_abi)) double __face_nexttoward (double a1, long double a2)
{ return __body_nexttoward (a1, a2); }

extern float __body_nexttowardf (float a1, long double a2) __asm__("nexttowardf");
__attribute__((sysv_abi)) float __face_nexttowardf (float a1, long double a2)
{ return __body_nexttowardf (a1, a2); }

extern long double __body_nexttowardl (long double a1, long double a2) __asm__("nexttowardl");
__attribute__((sysv_abi)) long double __face_nexttowardl (long double a1, long double a2)
{ return __body_nexttowardl (a1, a2); }

extern double __body_pow (double a1, double a2) __asm__("pow");
__attribute__((sysv_abi)) double __face_pow (double a1, double a2)
{ return __body_pow (a1, a2); }

extern double __body_pow10 (double a1) __asm__("pow10");
__attribute__((sysv_abi)) double __face_pow10 (double a1)
{ return __body_pow10 (a1); }

extern float __body_pow10f (float a1) __asm__("pow10f");
__attribute__((sysv_abi)) float __face_pow10f (float a1)
{ return __body_pow10f (a1); }

extern float __body_pow10l (float a1) __asm__("pow10l");
__attribute__((sysv_abi)) float __face_pow10l (float a1)
{ return __body_pow10l (a1); }

extern float __body_powf (float a1, float a2) __asm__("powf");
__attribute__((sysv_abi)) float __face_powf (float a1, float a2)
{ return __body_powf (a1, a2); }

extern long double __body_powl (long double a1, long double a2) __asm__("powl");
__attribute__((sysv_abi)) long double __face_powl (long double a1, long double a2)
{ return __body_powl (a1, a2); }

extern int __body_pthread_sigqueue (pthread_t a1, int a2, const union sigval a3) __asm__("pthread_sigqueue");
__attribute__((sysv_abi)) int __face_pthread_sigqueue (pthread_t a1, int a2, const union sigval a3)
{ return __body_pthread_sigqueue (a1, a2, a3); }

extern double __body_remainder (double a1, double a2) __asm__("remainder");
__attribute__((sysv_abi)) double __face_remainder (double a1, double a2)
{ return __body_remainder (a1, a2); }

extern float __body_remainderf (float a1, float a2) __asm__("remainderf");
__attribute__((sysv_abi)) float __face_remainderf (float a1, float a2)
{ return __body_remainderf (a1, a2); }

extern long double __body_remainderl (long double a1, long double a2) __asm__("remainderl");
__attribute__((sysv_abi)) long double __face_remainderl (long double a1, long double a2)
{ return __body_remainderl (a1, a2); }

extern double __body_remquo (double a1, double a2, int * a3) __asm__("remquo");
__attribute__((sysv_abi)) double __face_remquo (double a1, double a2, int * a3)
{ return __body_remquo (a1, a2, a3); }

extern float __body_remquof (float a1, float a2, int * a3) __asm__("remquof");
__attribute__((sysv_abi)) float __face_remquof (float a1, float a2, int * a3)
{ return __body_remquof (a1, a2, a3); }

extern long double __body_remquol (long double a1, long double a2, int * a3) __asm__("remquol");
__attribute__((sysv_abi)) long double __face_remquol (long double a1, long double a2, int * a3)
{ return __body_remquol (a1, a2, a3); }

extern double __body_rint (double a1) __asm__("rint");
__attribute__((sysv_abi)) double __face_rint (double a1)
{ return __body_rint (a1); }

extern float __body_rintf (float a1) __asm__("rintf");
__attribute__((sysv_abi)) float __face_rintf (float a1)
{ return __body_rintf (a1); }

extern long double __body_rintl (long double a1) __asm__("rintl");
__attribute__((sysv_abi)) long double __face_rintl (long double a1)
{ return __body_rintl (a1); }

extern double __body_round (double a1) __asm__("round");
__attribute__((sysv_abi)) double __face_round (double a1)
{ return __body_round (a1); }

extern float __body_roundf (float a1) __asm__("roundf");
__attribute__((sysv_abi)) float __face_roundf (float a1)
{ return __body_roundf (a1); }

extern long double __body_roundl (long double a1) __asm__("roundl");
__attribute__((sysv_abi)) long double __face_roundl (long double a1)
{ return __body_roundl (a1); }

extern double __body_scalbln (double a1, long int a2) __asm__("scalbln");
__attribute__((sysv_abi)) double __face_scalbln (double a1, long int a2)
{ return __body_scalbln (a1, a2); }

extern float __body_scalblnf (float a1, long int a2) __asm__("scalblnf");
__attribute__((sysv_abi)) float __face_scalblnf (float a1, long int a2)
{ return __body_scalblnf (a1, a2); }

extern long double __body_scalblnl (long double a1, long int a2) __asm__("scalblnl");
__attribute__((sysv_abi)) long double __face_scalblnl (long double a1, long int a2)
{ return __body_scalblnl (a1, a2); }

extern double __body_scalbn (double a1, int a2) __asm__("scalbn");
__attribute__((sysv_abi)) double __face_scalbn (double a1, int a2)
{ return __body_scalbn (a1, a2); }

extern float __body_scalbnf (float a1, int a2) __asm__("scalbnf");
__attribute__((sysv_abi)) float __face_scalbnf (float a1, int a2)
{ return __body_scalbnf (a1, a2); }

extern long double __body_scalbnl (long double a1, int a2) __asm__("scalbnl");
__attribute__((sysv_abi)) long double __face_scalbnl (long double a1, int a2)
{ return __body_scalbnl (a1, a2); }

extern int __body_sigqueue (pid_t a1, int a2, const union sigval a3) __asm__("sigqueue");
__attribute__((sysv_abi)) int __face_sigqueue (pid_t a1, int a2, const union sigval a3)
{ return __body_sigqueue (a1, a2, a3); }

extern double __body_sin (double a1) __asm__("sin");
__attribute__((sysv_abi)) double __face_sin (double a1)
{ return __body_sin (a1); }

extern void __body_sincos (double a1, double * a2, double * a3) __asm__("sincos");
__attribute__((sysv_abi)) void __face_sincos (double a1, double * a2, double * a3)
{ __body_sincos (a1, a2, a3); }

extern void __body_sincosf (float a1, float * a2, float * a3) __asm__("sincosf");
__attribute__((sysv_abi)) void __face_sincosf (float a1, float * a2, float * a3)
{ __body_sincosf (a1, a2, a3); }

extern void __body_sincosl (long double a1, long double * a2, long double * a3) __asm__("sincosl");
__attribute__((sysv_abi)) void __face_sincosl (long double a1, long double * a2, long double * a3)
{ __body_sincosl (a1, a2, a3); }

extern float __body_sinf (float a1) __asm__("sinf");
__attribute__((sysv_abi)) float __face_sinf (float a1)
{ return __body_sinf (a1); }

extern double __body_sinh (double a1) __asm__("sinh");
__attribute__((sysv_abi)) double __face_sinh (double a1)
{ return __body_sinh (a1); }

extern float __body_sinhf (float a1) __asm__("sinhf");
__attribute__((sysv_abi)) float __face_sinhf (float a1)
{ return __body_sinhf (a1); }

extern long double __body_sinhl (long double a1) __asm__("sinhl");
__attribute__((sysv_abi)) long double __face_sinhl (long double a1)
{ return __body_sinhl (a1); }

extern long double __body_sinl (long double a1) __asm__("sinl");
__attribute__((sysv_abi)) long double __face_sinl (long double a1)
{ return __body_sinl (a1); }

extern double __body_sqrt (double a1) __asm__("sqrt");
__attribute__((sysv_abi)) double __face_sqrt (double a1)
{ return __body_sqrt (a1); }

extern float __body_sqrtf (float a1) __asm__("sqrtf");
__attribute__((sysv_abi)) float __face_sqrtf (float a1)
{ return __body_sqrtf (a1); }

extern long double __body_sqrtl (long double a1) __asm__("sqrtl");
__attribute__((sysv_abi)) long double __face_sqrtl (long double a1)
{ return __body_sqrtl (a1); }

extern double __body_strtod (const char * a1, char ** a2) __asm__("strtod");
__attribute__((sysv_abi)) double __face_strtod (const char * a1, char ** a2)
{ return __body_strtod (a1, a2); }

extern double __body_strtod_l (const char * a1, char ** a2, locale_t a3) __asm__("strtod_l");
__attribute__((sysv_abi)) double __face_strtod_l (const char * a1, char ** a2, locale_t a3)
{ return __body_strtod_l (a1, a2, a3); }

extern float __body_strtof (const char * a1, char ** a2) __asm__("strtof");
__attribute__((sysv_abi)) float __face_strtof (const char * a1, char ** a2)
{ return __body_strtof (a1, a2); }

extern float __body_strtof_l (const char * a1, char ** a2, locale_t a3) __asm__("strtof_l");
__attribute__((sysv_abi)) float __face_strtof_l (const char * a1, char ** a2, locale_t a3)
{ return __body_strtof_l (a1, a2, a3); }

extern long double __body_strtold (const char * a1, char ** a2) __asm__("strtold");
__attribute__((sysv_abi)) long double __face_strtold (const char * a1, char ** a2)
{ return __body_strtold (a1, a2); }

extern long double __body_strtold_l (const char * a1, char ** a2, locale_t a3) __asm__("strtold_l");
__attribute__((sysv_abi)) long double __face_strtold_l (const char * a1, char ** a2, locale_t a3)
{ return __body_strtold_l (a1, a2, a3); }

extern double __body_tan (double a1) __asm__("tan");
__attribute__((sysv_abi)) double __face_tan (double a1)
{ return __body_tan (a1); }

extern float __body_tanf (float a1) __asm__("tanf");
__attribute__((sysv_abi)) float __face_tanf (float a1)
{ return __body_tanf (a1); }

extern double __body_tanh (double a1) __asm__("tanh");
__attribute__((sysv_abi)) double __face_tanh (double a1)
{ return __body_tanh (a1); }

extern float __body_tanhf (float a1) __asm__("tanhf");
__attribute__((sysv_abi)) float __face_tanhf (float a1)
{ return __body_tanhf (a1); }

extern long double __body_tanhl (long double a1) __asm__("tanhl");
__attribute__((sysv_abi)) long double __face_tanhl (long double a1)
{ return __body_tanhl (a1); }

extern long double __body_tanl (long double a1) __asm__("tanl");
__attribute__((sysv_abi)) long double __face_tanl (long double a1)
{ return __body_tanl (a1); }

extern double __body_tgamma (double a1) __asm__("tgamma");
__attribute__((sysv_abi)) double __face_tgamma (double a1)
{ return __body_tgamma (a1); }

extern float __body_tgammaf (float a1) __asm__("tgammaf");
__attribute__((sysv_abi)) float __face_tgammaf (float a1)
{ return __body_tgammaf (a1); }

extern long double __body_tgammal (long double a1) __asm__("tgammal");
__attribute__((sysv_abi)) long double __face_tgammal (long double a1)
{ return __body_tgammal (a1); }

extern double __body_trunc (double a1) __asm__("trunc");
__attribute__((sysv_abi)) double __face_trunc (double a1)
{ return __body_trunc (a1); }

extern float __body_truncf (float a1) __asm__("truncf");
__attribute__((sysv_abi)) float __face_truncf (float a1)
{ return __body_truncf (a1); }

extern long double __body_truncl (long double a1) __asm__("truncl");
__attribute__((sysv_abi)) long double __face_truncl (long double a1)
{ return __body_truncl (a1); }

extern double __body_wcstod (const wchar_t * a1, wchar_t ** a2) __asm__("wcstod");
__attribute__((sysv_abi)) double __face_wcstod (const wchar_t * a1, wchar_t ** a2)
{ return __body_wcstod (a1, a2); }

extern double __body_wcstod_l (const wchar_t * a1, wchar_t ** a2, locale_t a3) __asm__("wcstod_l");
__attribute__((sysv_abi)) double __face_wcstod_l (const wchar_t * a1, wchar_t ** a2, locale_t a3)
{ return __body_wcstod_l (a1, a2, a3); }

extern float __body_wcstof (const wchar_t * a1, wchar_t ** a2) __asm__("wcstof");
__attribute__((sysv_abi)) float __face_wcstof (const wchar_t * a1, wchar_t ** a2)
{ return __body_wcstof (a1, a2); }

extern float __body_wcstof_l (const wchar_t * a1, wchar_t ** a2, locale_t a3) __asm__("wcstof_l");
__attribute__((sysv_abi)) float __face_wcstof_l (const wchar_t * a1, wchar_t ** a2, locale_t a3)
{ return __body_wcstof_l (a1, a2, a3); }

extern long double __body_wcstold (const wchar_t * a1, wchar_t ** a2) __asm__("wcstold");
__attribute__((sysv_abi)) long double __face_wcstold (const wchar_t * a1, wchar_t ** a2)
{ return __body_wcstold (a1, a2); }

extern long double __body_wcstold_l (const wchar_t * a1, wchar_t ** a2, locale_t a3) __asm__("wcstold_l");
__attribute__((sysv_abi)) long double __face_wcstold_l (const wchar_t * a1, wchar_t ** a2, locale_t a3)
{ return __body_wcstold_l (a1, a2, a3); }

extern double __body_y0 (double a1) __asm__("y0");
__attribute__((sysv_abi)) double __face_y0 (double a1)
{ return __body_y0 (a1); }

extern float __body_y0f (float a1) __asm__("y0f");
__attribute__((sysv_abi)) float __face_y0f (float a1)
{ return __body_y0f (a1); }

extern double __body_y1 (double a1) __asm__("y1");
__attribute__((sysv_abi)) double __face_y1 (double a1)
{ return __body_y1 (a1); }

extern float __body_y1f (float a1) __asm__("y1f");
__attribute__((sysv_abi)) float __face_y1f (float a1)
{ return __body_y1f (a1); }

extern double __body_yn (int a1, double a2) __asm__("yn");
__attribute__((sysv_abi)) double __face_yn (int a1, double a2)
{ return __body_yn (a1, a2); }

extern float __body_ynf (int a1, float a2) __asm__("ynf");
__attribute__((sysv_abi)) float __face_ynf (int a1, float a2)
{ return __body_ynf (a1, a2); }
