#!/usr/bin/env python3
"""Write the assembly for a stand-in vendor binary.

WP-54's exit criterion talks about a vendor binary. Reproducing it against a
real one would want a network, an el8 mirror and a Linux host, so the check is
reimplemented the way WP-53 reimplemented elfdeps: build a binary that carries
exactly the shape an el8 binary carries — a DT_NEEDED entry for each of the
nine libraries and a verneed entry against each — and read the requirements
back out of the file.

This script writes that binary's source: a `_start` and, per library, one call
to a symbol picked from the library's forward map. The pick is programmatic so
no symbol name is written down here to rot: the first default-binding,
non-scaffold function whose name no other of the nine libraries exports, which
pins each verneed entry to its intended library whatever the link order.

Arguments are SONAME=FORWARD_MAP pairs; the assembly goes to --out, and the
picks come out on stdout as soname<TAB>symbol lines.
"""
import argparse
import sys


def read_forward(path):
    """[(symbol, version, binding, type, disposition)] from a forward map."""
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            f = line.rstrip("\n").split("\t")
            if len(f) != 8:
                sys.exit("%s: %d fields, want 8" % (path, len(f)))
            rows.append((f[0], f[1], f[2], f[3], f[6]))
    return rows


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("pairs", nargs="+", metavar="SONAME=FORWARD_MAP")
    ap.add_argument("--out", required=True, help="assembly output")
    args = ap.parse_args()

    libs = []
    for pair in args.pairs:
        if "=" not in pair:
            sys.exit("argument %r is not SONAME=FORWARD_MAP" % pair)
        soname, path = pair.split("=", 1)
        libs.append((soname, read_forward(path)))

    exporters = {}
    for soname, rows in libs:
        for symbol, _v, _b, _t, disp in rows:
            if disp != "scaffold":
                exporters.setdefault(symbol, set()).add(soname)

    # Prefer a default-binding function referenced by bare name, the way a
    # fresh link binds. el8's libnsl.so.1 exports nothing at a default
    # binding — its whole surface is hidden-versioned at GLIBC_PRIVATE — so
    # the fallback is an explicit symbol@version reference, which is the form
    # every el8 binary that needs that library carries anyway.
    picks = []
    for soname, rows in libs:
        pick = None
        for want_default in (True, False):
            for symbol, version, binding, styp, disp in rows:
                if (disp != "scaffold" and styp in ("func", "ifunc")
                        and (binding == "default") == want_default
                        and exporters[symbol] == {soname}):
                    pick = (symbol, version if not want_default else None)
                    break
            if pick:
                break
        if pick is None:
            sys.exit("%s: no unique function to call" % soname)
        picks.append((soname,) + pick)

    asm = ['\t.file\t"standin.s"',
           "# generated by veneer/companions/t/mk-standin.py -- do not edit",
           "\t.text"]
    for i, (_soname, symbol, version) in enumerate(picks):
        if version is not None:
            asm.append("\t.symver\tref%d, %s@%s" % (i, symbol, version))
    asm += ["\t.globl\t_start", "\t.type\t_start, @function", "_start:"]
    for i, (_soname, symbol, version) in enumerate(picks):
        asm.append("\tcall\t%s" % (symbol if version is None else "ref%d" % i))
    asm.append("\tret")
    asm.append("\t.size\t_start, .-_start")
    asm.append('\t.section\t.note.GNU-stack,"",@progbits')

    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(asm) + "\n")
    for soname, symbol, version in picks:
        print("%s\t%s%s" % (soname, symbol,
                            "" if version is None else "@" + version))


if __name__ == "__main__":
    main()
