#!/usr/bin/env python3
"""Generate one slice's wiring from the forward map (WP-56).

Reads WP-53's forward map (symbol, version, binding, type, bind, bucket,
disposition, target) and the slice map, selects the requested slice's
function rows, and writes three files:

  - wire-<slice>.gen.c: the slice's bind table, one esn_wire_ent per wired
    row, export names taken from the map's target column. Hidden: the
    table is an implementation detail of the DSO that carries it.
  - wire-<slice>.gen.s: one thunk per wired row, a rip-relative tail jump
    through the row's fn slot, bound to its symbol@node by .symver exactly
    as WP-53 binds the stubs it replaces.
  - wire-<slice>.shims.tsv: the slice's bucket-3 rows, the hand-work
    worklist; a shim body translates through xlat-core and calls through
    the same table, so its rows are in the table too.

Only dispositions forward-same, forward-alias and shim are wired; stubs
stay WP-53's ret bodies and scaffold rows belong to the linker. Row order
is the forward map's, so the generation is deterministic and the committed
output re-derives byte-identical.
"""
import argparse
import sys

ENT_SIZE = 16   # sizeof(struct esn_wire_ent) on LP64: two pointers
FN_OFF = 8      # offsetof fn

WIRED = ("forward-same", "forward-alias", "shim")


def read_slice_map(path):
    m = {}
    with open(path, encoding="utf-8") as fh:
        for ln in fh:
            ln = ln.rstrip("\n")
            if not ln or ln.startswith("#"):
                continue
            f = ln.split("\t")
            m[f[0]] = f[1]
    return m


def read_forward_map(path):
    rows = []
    with open(path, encoding="utf-8") as fh:
        for i, ln in enumerate(fh):
            ln = ln.rstrip("\n")
            if not ln or ln.startswith("#"):
                continue
            f = ln.split("\t")
            if len(f) != 8:
                sys.exit("%s:%d: want 8 columns, got %d" % (path, i + 1, len(f)))
            rows.append(f)
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--forward-map", required=True)
    ap.add_argument("--slice-map", required=True)
    ap.add_argument("--slice", required=True)
    ap.add_argument("--table", required=True)
    ap.add_argument("--thunks", required=True)
    ap.add_argument("--shims", required=True)
    args = ap.parse_args()

    sl = read_slice_map(args.slice_map)
    picked = []
    for f in read_forward_map(args.forward_map):
        symbol, version, binding, styp, sbind, bucket, disp, target = f
        if styp != "func" or disp not in WIRED:
            continue
        if sl.get(symbol) != args.slice:
            continue
        if disp != "shim" and (not target or target == "-"):
            sys.exit("row %s@%s: %s with no target" % (symbol, version, disp))
        picked.append(f)
    if not picked:
        sys.exit("slice %s: nothing to wire" % args.slice)

    tab = "__esn_wire_" + args.slice.replace("-", "_")
    banner = ("generated by gen-wire.py from %s + %s, slice %s; do not edit"
              % (args.forward_map.split("/")[-1],
                 args.slice_map.split("/")[-1], args.slice))

    c = ["/* %s */" % banner,
         '#include "wire.h"', "",
         "ESN_WIRE_LOCAL struct esn_wire_ent %s[] = {" % tab]
    for f in picked:
        symbol, version, _, _, _, _, disp, target = f
        name = symbol if (disp == "shim" and (not target or target == "-")) \
            else target
        c.append('    { "%s", 0 },   /* %s@%s %s */'
                 % (name, symbol, version, disp))
    c += ["};", "",
          "ESN_WIRE_LOCAL const unsigned long %s_n = sizeof %s / sizeof *%s;"
          % (tab, tab, tab), ""]

    s = ["/* %s */" % banner, "\t.text"]
    shims = ["# %s" % banner,
             "# symbol\tversion\tbinding\ttarget\ttable-index"]
    for i, f in enumerate(picked):
        symbol, version, binding, _, sbind, _, disp, target = f
        if disp == "shim":
            shims.append("\t".join((symbol, version, binding, target or "-",
                                    str(i))))
            continue
        label = "w%05d" % i
        decl = ".weak" if sbind == "weak" else ".globl"
        sep = "@@" if binding == "default" else "@"
        s += ["\t%s\t%s" % (decl, label),
              "\t.type\t%s,@function" % label,
              "%s:" % label,
              "\tjmp\t*%s+%d(%%rip)" % (tab, i * ENT_SIZE + FN_OFF),
              "\t.size\t%s, .-%s" % (label, label),
              "\t.symver\t%s, %s%s%s" % (label, symbol, sep, version), ""]
    s.append('\t.section\t.note.GNU-stack,"",@progbits')

    for path, lines in ((args.table, c), (args.thunks, s),
                        (args.shims, shims)):
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(lines) + "\n")
    n = sum(1 for f in picked if f[6] != "shim")
    sys.stderr.write("slice %s: %d rows wired (%d thunks, %d shims)\n"
                     % (args.slice, len(picked), n, len(picked) - n))


if __name__ == "__main__":
    main()
