#!/usr/bin/env python3
"""Generate the C-locale ctype tables el8 keeps behind __ctype_b_loc and kin.

WP-56. glibc programs read character classes and case maps through three
accessors -- __ctype_b_loc, __ctype_tolower_loc, __ctype_toupper_loc -- each
returning a pointer to a table indexed [-128..255]. Cygwin exports none of
them (they are glibc-internal; newlib classifies through a differently laid
out _ctype_ table), so WP-52 files all three, and the hidden data object
__ctype_b they front, in bucket 4 as stubs "absent from runtime export
surface". They are not shims over a divergent Cygwin export; there is nothing
to translate. The veneer fills the stub instead, with the table synthesized
from the C standard's own class definitions.

The scope is the C/POSIX locale, which is what every el8 build tool this
harness targets runs in. A non-C locale would need Cygwin's per-locale ctype
data translated into glibc's bit layout at the bind, downstream of this
static body; that is left for whoever first needs a localized package.

The bit layout is el8's ctype.h enum read through _ISbit on a little-endian
x86_64: bits 0..7 land in the high byte (1<<bit)<<8, bits 8..11 in the low
byte (1<<bit)>>8, so the whole short is byte-swapped from the natural order.
t/ctype-table.sh pins this file byte-identical and, where WSL supplies the
pinned el8 image, dumps glibc's real three tables and asserts these match
them entry for entry across all 384 indices.
"""
import argparse
import os

# el8 ctype.h: _ISbit(bit) is (bit<8)?((1<<bit)<<8):((1<<bit)>>8) on LE.
def isbit(bit):
    return (1 << bit) << 8 if bit < 8 else (1 << bit) >> 8

UPPER, LOWER, ALPHA, DIGIT = isbit(0), isbit(1), isbit(2), isbit(3)
XDIGIT, SPACE, PRINT, GRAPH = isbit(4), isbit(5), isbit(6), isbit(7)
BLANK, CNTRL, PUNCT, ALNUM = isbit(8), isbit(9), isbit(10), isbit(11)


def class_mask(c):
    """The C-locale class bits for byte value c in 0..255."""
    if not 0 <= c < 128:
        return 0
    up = 65 <= c <= 90
    lo = 97 <= c <= 122
    dig = 48 <= c <= 57
    xdig = dig or 65 <= c <= 70 or 97 <= c <= 102
    alpha = up or lo
    alnum = alpha or dig
    space = c in (32, 9, 10, 11, 12, 13)
    blank = c in (32, 9)
    cntrl = c < 32 or c == 127
    printable = 32 <= c <= 126
    graph = 33 <= c <= 126
    punct = graph and not alnum
    m = 0
    for cond, bit in ((up, UPPER), (lo, LOWER), (alpha, ALPHA), (dig, DIGIT),
                      (xdig, XDIGIT), (space, SPACE), (printable, PRINT),
                      (graph, GRAPH), (blank, BLANK), (cntrl, CNTRL),
                      (punct, PUNCT), (alnum, ALNUM)):
        if cond:
            m |= bit
    return m


def case_map(c, lowering):
    """glibc's tolower/toupper table entry at signed index c in -128..255.

    EOF (-1) returns -1; the rest of the negative region returns the unsigned
    byte value c+256 unchanged; 128..255 pass through; only ASCII letters fold.
    """
    if c == -1:
        return -1
    if c < 0:
        return c + 256
    if lowering and 65 <= c <= 90:
        return c + 32
    if not lowering and 97 <= c <= 122:
        return c - 32
    return c


def fmt_row(vals):
    """Eight values per line, indented, for a readable committed table."""
    out, line = [], []
    for v in vals:
        line.append(v)
        if len(line) == 8:
            out.append("    " + " ".join("%d," % x for x in line))
            line = []
    if line:
        out.append("    " + " ".join("%d," % x for x in line))
    return "\n".join(out)


def render():
    idx = range(-128, 256)
    b = [class_mask(c) if 0 <= c < 256 else 0 for c in idx]
    lo = [case_map(c, True) for c in idx]
    up = [case_map(c, False) for c in idx]
    L = []
    L.append("/* Generated by gen-ctype-table.py -- do not edit. */")
    L.append("/* The C-locale ctype tables el8 keeps behind __ctype_b_loc and")
    L.append("   its two case-map kin; a filled stub, not a shim (WP-56). */")
    L.append("")
    L.append("/* Indexed [-128..255]; the exported pointer is biased +128 so a")
    L.append("   caller's signed char, and EOF, index the same table glibc's do. */")
    L.append("static const unsigned short __esn_ctype_b[384] = {")
    L.append(fmt_row(b))
    L.append("};")
    L.append("static const int __esn_ctype_tolower[384] = {")
    L.append(fmt_row(lo))
    L.append("};")
    L.append("static const int __esn_ctype_toupper[384] = {")
    L.append(fmt_row(up))
    L.append("};")
    L.append("")
    L.append("static const unsigned short *const __esn_ctype_b_ptr =")
    L.append("    __esn_ctype_b + 128;")
    L.append("static const int *const __esn_ctype_tolower_ptr =")
    L.append("    __esn_ctype_tolower + 128;")
    L.append("static const int *const __esn_ctype_toupper_ptr =")
    L.append("    __esn_ctype_toupper + 128;")
    L.append("")
    L.append("const unsigned short **__esn_ctype_b_loc(void)")
    L.append("{ return (const unsigned short **)&__esn_ctype_b_ptr; }")
    L.append("const int **__esn_ctype_tolower_loc(void)")
    L.append("{ return (const int **)&__esn_ctype_tolower_ptr; }")
    L.append("const int **__esn_ctype_toupper_loc(void)")
    L.append("{ return (const int **)&__esn_ctype_toupper_ptr; }")
    L.append("")
    L.append("/* Bind each body to the glibc version node the map records. */")
    L.append('__asm__(".symver __esn_ctype_b_loc,__ctype_b_loc@@GLIBC_2.3");')
    L.append('__asm__(".symver __esn_ctype_tolower_loc,'
             '__ctype_tolower_loc@@GLIBC_2.3");')
    L.append('__asm__(".symver __esn_ctype_toupper_loc,'
             '__ctype_toupper_loc@@GLIBC_2.3");')
    L.append("")
    return "\n".join(L) + "\n"


# The filled bucket-4 stubs this body answers, and where each is certified.
# Emitted beside the .c so the manifest and the .symver bindings share one
# source and cannot drift; the acceptance harness reads it to tell a stub the
# veneer fills from a stub that fails (DR-0052).
FILLED = (
    ("__ctype_b_loc", "GLIBC_2.3"),
    ("__ctype_tolower_loc", "GLIBC_2.3"),
    ("__ctype_toupper_loc", "GLIBC_2.3"),
)

BODY = "veneer/wiring/ctype-table.gen.c"
CERT = "veneer/wiring/t/ctype-table.sh"


def render_manifest():
    L = [
        "# Filled bucket-4 stubs: names absent from the export surface that the",
        "# veneer answers with a synthesized, certified body rather than a body",
        "# that only reports its own absence (DR-0052). Generated by",
        "# gen-ctype-table.py -- do not edit.",
        "#",
        "# symbol\tversion\tbody\tcertified-by",
    ]
    for sym, ver in FILLED:
        L.append("\t".join((sym, ver, BODY, CERT)))
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    text = render()
    if a.out:
        path = os.path.join(a.out, "ctype-table.gen.c")
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        mpath = os.path.join(a.out, "ctype-filled.tsv")
        with open(mpath, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(render_manifest())
    else:
        import sys
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
