#!/usr/bin/env bash
#
# WP-56: emit the runtime slice's jmp_buf frameless faces from the
# curated jmpbuf.tsv, cross-referenced against the generated
# wire-runtime.shims.tsv for each row's version, binding, target and
# bind-table index -- the same split gen-ctx-faces.sh uses one layer
# down (a curated table naming what a body promises, generated data
# naming where it lives). See wire-jmpbuf-face.inc and the
# jmp_buf-frameless-face decision record.
#
# Usage:
#   gen-jmpbuf-face.sh [-o FILE] [--curated FILE] [--shims FILE]
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
curated=$here/jmpbuf.tsv
shims=$here/wire-runtime.shims.tsv
out=$here/wire-jmpbuf-faces.gen.S
prog=gen-jmpbuf-face.sh

while [ $# -gt 0 ]; do
  case $1 in
    -o) out=$2; shift 2;;
    --curated) curated=$2; shift 2;;
    --shims) shims=$2; shift 2;;
    *) echo "$prog: unknown option: $1" >&2; exit 2;;
  esac
done

table=__esn_wire_runtime
ent_size=16
fn_off=8

gen() {
  printf '/* generated by gen-jmpbuf-face.sh from %s + %s; do not edit */\n' \
    "$(basename "$curated")" "$(basename "$shims")"
  printf '#include "wire-jmpbuf-face.inc"\n'

  # every curated row must still be a shim row in wire-runtime.shims.tsv,
  # and vice versa -- a drift in either is a conscious re-pin, not a
  # silent partial face.
  local cur_syms shim_syms
  cur_syms=$(awk -F'\t' '!/^#/{print $1}' "$curated" | sort)
  shim_syms=$(awk -F'\t' '!/^#/{print $1}' "$shims" | sort)
  if [ "$cur_syms" != "$shim_syms" ]; then
    echo "$prog: $curated and $shims disagree on membership:" >&2
    diff <(echo "$cur_syms") <(echo "$shim_syms") >&2 || true
    exit 1
  fi

  awk -F'\t' -v table="$table" -v ent_size="$ent_size" -v fn_off="$fn_off" \
    'FNR==NR { if ($0 !~ /^#/ && NF) { dir[$1]=$2; sbind[$1]=$3 }; next }
     $0 !~ /^#/ && NF {
       sym=$1; ver=$2; binding=$3; idx=$5
       off = idx * ent_size + fn_off
       decl = (sbind[sym] == "weak") ? ".weak" : ".globl"
       macro = (dir[sym] == "save") ? "wire_jmpbuf_save" : "wire_jmpbuf_restore"
       sep = (binding == "default") ? "@@" : "@"
       printf "\t%s\t__jmpbuf_%s, %s, %s, %d\n", macro, sym, decl, table, off
       printf "\t.symver\t__jmpbuf_%s, %s%s%s\n\n", sym, sym, sep, ver
     }' "$curated" "$shims"

  printf '\t.section\t.note.GNU-stack,"",@progbits\n'
}

if [ "$out" = - ]; then gen; else gen > "$out"; fi
