#!/usr/bin/env python3
"""Generate the errno and signal translation core from WP-55's tables.

WP-56. Reads veneer/xlat/errno-map.tsv and signal-map.tsv and writes
xlat-core.gen.c and xlat-core.gen.h: dense value-to-value arrays in both
directions behind four functions. Every down-call wrapper shares this one
translation; no shim reads the tables directly.

"Up" is toward Linux (the numbers an el8 binary sees), "down" toward
Cygwin, following the xlat README: Linux numbers upstairs, Cygwin numbers
downstairs. A value no table row claims passes through unchanged, which
is right for the shared low range and honest for the rest: inventing a
number would hide the gap the differential exists to find.

A row whose cygwin side is `-` names something Cygwin lacks; it gets no
entry. Two names sharing a value must agree on where it maps
(EAGAIN/EWOULDBLOCK do, EDEADLK/EDEADLOCK do); a conflict aborts the
generation rather than picking a winner.
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def read_map(path):
    """Rows of (name, linux, cygwin); a `-` cygwin side becomes None."""
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            name, lin, cyg = line.split("\t")
            rows.append((name, int(lin), None if cyg == "-" else int(cyg)))
    return rows


ALIAS_PREF = {
    # Linux treats these pairs as one value; Cygwin keeps them apart, so
    # the down direction must pick one target. EDEADLK is the POSIX name
    # and the value Cygwin's own calls return. ENOTSUP/EOPNOTSUPP (95)
    # resolves itself through the identity rule below.
    "errno down": {35: "EDEADLK"},
}


def value_map(rows, src, dst, what):
    cands = {}
    for name, lin, cyg in rows:
        side = {"linux": lin, "cygwin": cyg}
        s, d = side[src], side[dst]
        if s is None or d is None:
            continue
        cands.setdefault(s, []).append((name, d))
    m = {}
    for s, pairs in cands.items():
        dsts = {d for _, d in pairs}
        if len(dsts) == 1:
            m[s] = dsts.pop()
            continue
        # aliased names diverge: prefer the side-agreeing value, else the
        # explicitly named winner, else refuse to guess
        if s in dsts:
            m[s] = s
        elif s in ALIAS_PREF.get(what, {}):
            want = ALIAS_PREF[what][s]
            m[s] = dict((n, d) for n, d in pairs)[want]
        else:
            sys.exit("%s: value %d maps to %s; name a winner in ALIAS_PREF"
                     % (what, s, sorted(dsts)))
    return m


def emit_array(out, cname, m):
    """Dense short array; index 0 stays 0 and reads as "no entry", which
    is safe because no errno or signal maps to 0."""
    hi = max(m) + 1
    out.append("static const short %s[%d] = {" % (cname, hi))
    line = "    "
    for v in sorted(m):
        piece = "[%d] = %d," % (v, m[v])
        if len(line) + len(piece) > 78:
            out.append(line.rstrip())
            line = "    "
        line += piece + " "
    out.append(line.rstrip())
    out.append("};")
    return hi


def emit_func(out, fname, cname, hi):
    out.append("")
    out.append("int %s(int v)" % fname)
    out.append("{")
    out.append("    if (v > 0 && v < %d && %s[v])" % (hi, cname))
    out.append("        return %s[v];" % cname)
    out.append("    return v;")
    out.append("}")


BANNER = "/* Generated by gen-xlat.py from WP-55's tables -- do not edit. */"

FUNCS = [
    ("__esn_errno_up",    "xl_errno_up"),
    ("__esn_errno_down",  "xl_errno_down"),
    ("__esn_signal_up",   "xl_signal_up"),
    ("__esn_signal_down", "xl_signal_down"),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--xlat", default=os.path.join(HERE, os.pardir, "xlat"))
    ap.add_argument("--out", default=HERE)
    a = ap.parse_args()

    err = read_map(os.path.join(a.xlat, "errno-map.tsv"))
    sig = read_map(os.path.join(a.xlat, "signal-map.tsv"))
    maps = [
        value_map(err, "cygwin", "linux", "errno up"),
        value_map(err, "linux", "cygwin", "errno down"),
        value_map(sig, "cygwin", "linux", "signal up"),
        value_map(sig, "linux", "cygwin", "signal down"),
    ]

    c = [BANNER, '#include "xlat-core.gen.h"', ""]
    for (fname, cname), m in zip(FUNCS, maps):
        hi = emit_array(c, cname, m)
        emit_func(c, fname, cname, hi)
        c.append("")
    while c and c[-1] == "":
        c.pop()

    h = [BANNER,
         "#ifndef ESN_XLAT_CORE_H",
         "#define ESN_XLAT_CORE_H",
         ""]
    h += ["int %s(int v);" % fname for fname, _ in FUNCS]
    h += ["", "#endif"]

    for name, body in (("xlat-core.gen.c", c), ("xlat-core.gen.h", h)):
        path = os.path.join(a.out, name)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(body) + "\n")
        print("wrote %s" % path)


if __name__ == "__main__":
    main()
