/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice io; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_io[] = {
    { "readv", 0 },   /* readv@GLIBC_2.2.5 forward-same */
    { "writev", 0 },   /* writev@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_io_n = sizeof __esn_wire_io / sizeof *__esn_wire_io;

