/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice terminal; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_terminal[] = {
    { "cfgetispeed", 0 },   /* cfgetispeed@GLIBC_2.2.5 forward-same */
    { "cfgetospeed", 0 },   /* cfgetospeed@GLIBC_2.2.5 forward-same */
    { "cfmakeraw", 0 },   /* cfmakeraw@GLIBC_2.2.5 forward-same */
    { "cfsetispeed", 0 },   /* cfsetispeed@GLIBC_2.2.5 forward-same */
    { "cfsetospeed", 0 },   /* cfsetospeed@GLIBC_2.2.5 forward-same */
    { "cfsetspeed", 0 },   /* cfsetspeed@GLIBC_2.2.5 forward-same */
    { "endutent", 0 },   /* endutent@GLIBC_2.2.5 forward-same */
    { "endutxent", 0 },   /* endutxent@GLIBC_2.2.5 forward-same */
    { "getutent", 0 },   /* getutent@GLIBC_2.2.5 forward-same */
    { "getutid", 0 },   /* getutid@GLIBC_2.2.5 forward-same */
    { "getutline", 0 },   /* getutline@GLIBC_2.2.5 forward-same */
    { "getutxent", 0 },   /* getutxent@GLIBC_2.2.5 forward-same */
    { "getutxid", 0 },   /* getutxid@GLIBC_2.2.5 forward-same */
    { "getutxline", 0 },   /* getutxline@GLIBC_2.2.5 forward-same */
    { "ioctl", 0 },   /* ioctl@GLIBC_2.2.5 shim */
    { "pututline", 0 },   /* pututline@GLIBC_2.2.5 forward-same */
    { "pututxline", 0 },   /* pututxline@GLIBC_2.2.5 forward-same */
    { "setutent", 0 },   /* setutent@GLIBC_2.2.5 forward-same */
    { "setutxent", 0 },   /* setutxent@GLIBC_2.2.5 forward-same */
    { "tcdrain", 0 },   /* tcdrain@GLIBC_2.2.5 forward-same */
    { "tcflow", 0 },   /* tcflow@GLIBC_2.2.5 forward-same */
    { "tcflush", 0 },   /* tcflush@GLIBC_2.2.5 forward-same */
    { "tcgetattr", 0 },   /* tcgetattr@GLIBC_2.2.5 forward-same */
    { "tcgetsid", 0 },   /* tcgetsid@GLIBC_2.2.5 forward-same */
    { "tcsendbreak", 0 },   /* tcsendbreak@GLIBC_2.2.5 forward-same */
    { "tcsetattr", 0 },   /* tcsetattr@GLIBC_2.2.5 forward-same */
    { "updwtmp", 0 },   /* updwtmp@GLIBC_2.2.5 forward-same */
    { "updwtmpx", 0 },   /* updwtmpx@GLIBC_2.2.5 forward-same */
    { "utmpname", 0 },   /* utmpname@GLIBC_2.2.5 forward-same */
    { "utmpxname", 0 },   /* utmpxname@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_terminal_n = sizeof __esn_wire_terminal / sizeof *__esn_wire_terminal;

