/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice sysv-ipc; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_sysv_ipc[] = {
    { "__getpagesize", 0 },   /* __getpagesize@GLIBC_2.2.5 forward-same */
    { "ftok", 0 },   /* ftok@GLIBC_2.2.5 forward-same */
    { "msgctl", 0 },   /* msgctl@GLIBC_2.2.5 forward-same */
    { "msgget", 0 },   /* msgget@GLIBC_2.2.5 forward-same */
    { "msgrcv", 0 },   /* msgrcv@GLIBC_2.2.5 forward-same */
    { "msgsnd", 0 },   /* msgsnd@GLIBC_2.2.5 forward-same */
    { "semctl", 0 },   /* semctl@GLIBC_2.2.5 forward-same */
    { "semget", 0 },   /* semget@GLIBC_2.2.5 forward-same */
    { "semop", 0 },   /* semop@GLIBC_2.2.5 forward-same */
    { "shmat", 0 },   /* shmat@GLIBC_2.2.5 forward-same */
    { "shmctl", 0 },   /* shmctl@GLIBC_2.2.5 forward-same */
    { "shmdt", 0 },   /* shmdt@GLIBC_2.2.5 forward-same */
    { "shmget", 0 },   /* shmget@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_sysv_ipc_n = sizeof __esn_wire_sysv_ipc / sizeof *__esn_wire_sysv_ipc;

