/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice terminal; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_terminal+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, cfgetispeed@@GLIBC_2.2.5

	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_terminal+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, cfgetospeed@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_terminal+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, cfmakeraw@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_terminal+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, cfsetispeed@@GLIBC_2.2.5

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_terminal+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, cfsetospeed@@GLIBC_2.2.5

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_terminal+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, cfsetspeed@@GLIBC_2.2.5

	.weak	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_terminal+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, endutent@@GLIBC_2.2.5

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_terminal+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, endutxent@@GLIBC_2.2.5

	.weak	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_terminal+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, getutent@@GLIBC_2.2.5

	.weak	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_terminal+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, getutid@@GLIBC_2.2.5

	.weak	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_terminal+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, getutline@@GLIBC_2.2.5

	.globl	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_terminal+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, getutxent@@GLIBC_2.2.5

	.globl	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_terminal+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, getutxid@@GLIBC_2.2.5

	.globl	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_terminal+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, getutxline@@GLIBC_2.2.5

	.weak	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_terminal+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, pututline@@GLIBC_2.2.5

	.globl	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_terminal+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, pututxline@@GLIBC_2.2.5

	.weak	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_terminal+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, setutent@@GLIBC_2.2.5

	.globl	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_terminal+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, setutxent@@GLIBC_2.2.5

	.weak	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_terminal+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, tcdrain@@GLIBC_2.2.5

	.globl	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_terminal+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, tcflow@@GLIBC_2.2.5

	.globl	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_terminal+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, tcflush@@GLIBC_2.2.5

	.weak	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_terminal+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, tcgetattr@@GLIBC_2.2.5

	.globl	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_terminal+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, tcgetsid@@GLIBC_2.2.5

	.globl	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_terminal+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, tcsendbreak@@GLIBC_2.2.5

	.globl	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_terminal+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, tcsetattr@@GLIBC_2.2.5

	.weak	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_terminal+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, updwtmp@@GLIBC_2.2.5

	.globl	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_terminal+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, updwtmpx@@GLIBC_2.2.5

	.weak	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_terminal+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, utmpname@@GLIBC_2.2.5

	.globl	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_terminal+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, utmpxname@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
