/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice runtime; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_runtime+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, __assert@@GLIBC_2.2.5

	.weak	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_runtime+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, getcontext@@GLIBC_2.2.5

	.weak	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_runtime+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, makecontext@@GLIBC_2.2.5

	.weak	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_runtime+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, setcontext@@GLIBC_2.2.5

	.weak	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_runtime+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, swapcontext@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
