/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice misc; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_misc[] = {
    { "dirname", 0 },   /* dirname@GLIBC_2.2.5 forward-same */
    { "err", 0 },   /* err@GLIBC_2.2.5 forward-same */
    { "error", 0 },   /* error@GLIBC_2.2.5 forward-same */
    { "error_at_line", 0 },   /* error_at_line@GLIBC_2.2.5 forward-same */
    { "errx", 0 },   /* errx@GLIBC_2.2.5 forward-same */
    { "getentropy", 0 },   /* getentropy@GLIBC_2.25 forward-same */
    { "getopt", 0 },   /* getopt@GLIBC_2.2.5 forward-same */
    { "getopt_long", 0 },   /* getopt_long@GLIBC_2.2.5 forward-same */
    { "getopt_long_only", 0 },   /* getopt_long_only@GLIBC_2.2.5 forward-same */
    { "getrandom", 0 },   /* getrandom@GLIBC_2.25 forward-same */
    { "hcreate", 0 },   /* hcreate@GLIBC_2.2.5 forward-same */
    { "hcreate_r", 0 },   /* hcreate_r@GLIBC_2.2.5 forward-same */
    { "hdestroy", 0 },   /* hdestroy@GLIBC_2.2.5 forward-same */
    { "hdestroy_r", 0 },   /* hdestroy_r@GLIBC_2.2.5 forward-same */
    { "hsearch", 0 },   /* hsearch@GLIBC_2.2.5 forward-same */
    { "hsearch_r", 0 },   /* hsearch_r@GLIBC_2.2.5 forward-same */
    { "insque", 0 },   /* insque@GLIBC_2.2.5 forward-same */
    { "lfind", 0 },   /* lfind@GLIBC_2.2.5 forward-same */
    { "lsearch", 0 },   /* lsearch@GLIBC_2.2.5 forward-same */
    { "remque", 0 },   /* remque@GLIBC_2.2.5 forward-same */
    { "tdelete", 0 },   /* tdelete@GLIBC_2.2.5 forward-same */
    { "tdestroy", 0 },   /* tdestroy@GLIBC_2.2.5 forward-same */
    { "tfind", 0 },   /* tfind@GLIBC_2.2.5 forward-same */
    { "tsearch", 0 },   /* tsearch@GLIBC_2.2.5 forward-same */
    { "twalk", 0 },   /* twalk@GLIBC_2.2.5 forward-same */
    { "verr", 0 },   /* verr@GLIBC_2.2.5 forward-same */
    { "verrx", 0 },   /* verrx@GLIBC_2.2.5 forward-same */
    { "vwarn", 0 },   /* vwarn@GLIBC_2.2.5 forward-same */
    { "vwarnx", 0 },   /* vwarnx@GLIBC_2.2.5 forward-same */
    { "warn", 0 },   /* warn@GLIBC_2.2.5 forward-same */
    { "warnx", 0 },   /* warnx@GLIBC_2.2.5 forward-same */
    { "wordexp", 0 },   /* wordexp@GLIBC_2.2.5 forward-same */
    { "wordfree", 0 },   /* wordfree@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_misc_n = sizeof __esn_wire_misc / sizeof *__esn_wire_misc;

