/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice threads; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_threads[] = {
    { "sigsetjmp", 0 },   /* __sigsetjmp@GLIBC_2.2.5 shim */
    { "pthread_attr_destroy", 0 },   /* pthread_attr_destroy@GLIBC_2.2.5 forward-same */
    { "pthread_attr_getdetachstate", 0 },   /* pthread_attr_getdetachstate@GLIBC_2.2.5 forward-same */
    { "pthread_attr_getinheritsched", 0 },   /* pthread_attr_getinheritsched@GLIBC_2.2.5 forward-same */
    { "pthread_attr_getschedparam", 0 },   /* pthread_attr_getschedparam@GLIBC_2.2.5 forward-same */
    { "pthread_attr_getschedpolicy", 0 },   /* pthread_attr_getschedpolicy@GLIBC_2.2.5 forward-same */
    { "pthread_attr_getscope", 0 },   /* pthread_attr_getscope@GLIBC_2.2.5 forward-same */
    { "pthread_attr_init", 0 },   /* pthread_attr_init@GLIBC_2.2.5 forward-same */
    { "pthread_attr_setdetachstate", 0 },   /* pthread_attr_setdetachstate@GLIBC_2.2.5 forward-same */
    { "pthread_attr_setinheritsched", 0 },   /* pthread_attr_setinheritsched@GLIBC_2.2.5 forward-same */
    { "pthread_attr_setschedparam", 0 },   /* pthread_attr_setschedparam@GLIBC_2.2.5 forward-same */
    { "pthread_attr_setschedpolicy", 0 },   /* pthread_attr_setschedpolicy@GLIBC_2.2.5 forward-same */
    { "pthread_attr_setscope", 0 },   /* pthread_attr_setscope@GLIBC_2.2.5 forward-same */
    { "pthread_cond_broadcast", 0 },   /* pthread_cond_broadcast@GLIBC_2.2.5 forward-same */
    { "pthread_cond_broadcast", 0 },   /* pthread_cond_broadcast@GLIBC_2.3.2 forward-same */
    { "pthread_cond_destroy", 0 },   /* pthread_cond_destroy@GLIBC_2.2.5 forward-same */
    { "pthread_cond_destroy", 0 },   /* pthread_cond_destroy@GLIBC_2.3.2 forward-same */
    { "pthread_cond_init", 0 },   /* pthread_cond_init@GLIBC_2.2.5 forward-same */
    { "pthread_cond_init", 0 },   /* pthread_cond_init@GLIBC_2.3.2 forward-same */
    { "pthread_cond_signal", 0 },   /* pthread_cond_signal@GLIBC_2.2.5 forward-same */
    { "pthread_cond_signal", 0 },   /* pthread_cond_signal@GLIBC_2.3.2 forward-same */
    { "pthread_cond_timedwait", 0 },   /* pthread_cond_timedwait@GLIBC_2.2.5 forward-same */
    { "pthread_cond_timedwait", 0 },   /* pthread_cond_timedwait@GLIBC_2.3.2 forward-same */
    { "pthread_cond_wait", 0 },   /* pthread_cond_wait@GLIBC_2.2.5 forward-same */
    { "pthread_cond_wait", 0 },   /* pthread_cond_wait@GLIBC_2.3.2 forward-same */
    { "pthread_condattr_destroy", 0 },   /* pthread_condattr_destroy@GLIBC_2.2.5 forward-same */
    { "pthread_condattr_init", 0 },   /* pthread_condattr_init@GLIBC_2.2.5 forward-same */
    { "pthread_equal", 0 },   /* pthread_equal@GLIBC_2.2.5 forward-same */
    { "pthread_exit", 0 },   /* pthread_exit@GLIBC_2.2.5 forward-same */
    { "pthread_getschedparam", 0 },   /* pthread_getschedparam@GLIBC_2.2.5 forward-same */
    { "pthread_mutex_destroy", 0 },   /* pthread_mutex_destroy@GLIBC_2.2.5 forward-same */
    { "pthread_mutex_init", 0 },   /* pthread_mutex_init@GLIBC_2.2.5 forward-same */
    { "pthread_mutex_lock", 0 },   /* pthread_mutex_lock@GLIBC_2.2.5 forward-same */
    { "pthread_mutex_unlock", 0 },   /* pthread_mutex_unlock@GLIBC_2.2.5 forward-same */
    { "pthread_self", 0 },   /* pthread_self@GLIBC_2.2.5 forward-same */
    { "pthread_setcancelstate", 0 },   /* pthread_setcancelstate@GLIBC_2.2.5 forward-same */
    { "pthread_setcanceltype", 0 },   /* pthread_setcanceltype@GLIBC_2.2.5 forward-same */
    { "pthread_setschedparam", 0 },   /* pthread_setschedparam@GLIBC_2.2.5 forward-same */
    { "thrd_current", 0 },   /* thrd_current@GLIBC_2.28 forward-same */
    { "thrd_equal", 0 },   /* thrd_equal@GLIBC_2.28 forward-same */
    { "thrd_sleep", 0 },   /* thrd_sleep@GLIBC_2.28 forward-same */
    { "thrd_yield", 0 },   /* thrd_yield@GLIBC_2.28 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_threads_n = sizeof __esn_wire_threads / sizeof *__esn_wire_threads;

