/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice filesystem; do not edit */
	.text
	.weak	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_filesystem+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, alphasort@@GLIBC_2.2.5

	.weak	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_filesystem+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, alphasort64@@GLIBC_2.2.5

	.weak	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_filesystem+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, chmod@@GLIBC_2.2.5

	.weak	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_filesystem+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, closedir@@GLIBC_2.2.5

	.weak	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_filesystem+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, creat@@GLIBC_2.2.5

	.weak	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_filesystem+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, creat64@@GLIBC_2.2.5

	.globl	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_filesystem+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, dirfd@@GLIBC_2.2.5

	.weak	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_filesystem+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, endmntent@@GLIBC_2.2.5

	.weak	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_filesystem+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, fallocate@@GLIBC_2.10

	.globl	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_filesystem+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, fallocate64@@GLIBC_2.10

	.weak	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_filesystem+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, fchmod@@GLIBC_2.2.5

	.globl	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_filesystem+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, fchmodat@@GLIBC_2.4

	.weak	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_filesystem+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, fdopendir@@GLIBC_2.4

	.globl	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_filesystem+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, fgetxattr@@GLIBC_2.3

	.globl	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_filesystem+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, flistxattr@@GLIBC_2.3

	.weak	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_filesystem+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, flock@@GLIBC_2.2.5

	.globl	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_filesystem+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, fnmatch@@GLIBC_2.2.5

	.globl	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_filesystem+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, fremovexattr@@GLIBC_2.3

	.globl	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_filesystem+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, fsetxattr@@GLIBC_2.3

	.globl	w00035
	.type	w00035,@function
w00035:
	jmp	*__esn_wire_filesystem+568(%rip)
	.size	w00035, .-w00035
	.symver	w00035, fts_children@@GLIBC_2.2.5

	.globl	w00036
	.type	w00036,@function
w00036:
	jmp	*__esn_wire_filesystem+584(%rip)
	.size	w00036, .-w00036
	.symver	w00036, fts_close@@GLIBC_2.2.5

	.globl	w00037
	.type	w00037,@function
w00037:
	jmp	*__esn_wire_filesystem+600(%rip)
	.size	w00037, .-w00037
	.symver	w00037, fts_open@@GLIBC_2.2.5

	.globl	w00038
	.type	w00038,@function
w00038:
	jmp	*__esn_wire_filesystem+616(%rip)
	.size	w00038, .-w00038
	.symver	w00038, fts_read@@GLIBC_2.2.5

	.globl	w00039
	.type	w00039,@function
w00039:
	jmp	*__esn_wire_filesystem+632(%rip)
	.size	w00039, .-w00039
	.symver	w00039, fts_set@@GLIBC_2.2.5

	.globl	w00040
	.type	w00040,@function
w00040:
	jmp	*__esn_wire_filesystem+648(%rip)
	.size	w00040, .-w00040
	.symver	w00040, ftw@@GLIBC_2.2.5

	.weak	w00041
	.type	w00041,@function
w00041:
	jmp	*__esn_wire_filesystem+664(%rip)
	.size	w00041, .-w00041
	.symver	w00041, ftw64@@GLIBC_2.2.5

	.globl	w00042
	.type	w00042,@function
w00042:
	jmp	*__esn_wire_filesystem+680(%rip)
	.size	w00042, .-w00042
	.symver	w00042, futimens@@GLIBC_2.6

	.globl	w00044
	.type	w00044,@function
w00044:
	jmp	*__esn_wire_filesystem+712(%rip)
	.size	w00044, .-w00044
	.symver	w00044, getmntent@@GLIBC_2.2.5

	.weak	w00045
	.type	w00045,@function
w00045:
	jmp	*__esn_wire_filesystem+728(%rip)
	.size	w00045, .-w00045
	.symver	w00045, getmntent_r@@GLIBC_2.2.5

	.globl	w00046
	.type	w00046,@function
w00046:
	jmp	*__esn_wire_filesystem+744(%rip)
	.size	w00046, .-w00046
	.symver	w00046, getxattr@@GLIBC_2.3

	.weak	w00051
	.type	w00051,@function
w00051:
	jmp	*__esn_wire_filesystem+824(%rip)
	.size	w00051, .-w00051
	.symver	w00051, glob_pattern_p@@GLIBC_2.2.5

	.globl	w00054
	.type	w00054,@function
w00054:
	jmp	*__esn_wire_filesystem+872(%rip)
	.size	w00054, .-w00054
	.symver	w00054, lgetxattr@@GLIBC_2.3

	.globl	w00055
	.type	w00055,@function
w00055:
	jmp	*__esn_wire_filesystem+888(%rip)
	.size	w00055, .-w00055
	.symver	w00055, listxattr@@GLIBC_2.3

	.globl	w00056
	.type	w00056,@function
w00056:
	jmp	*__esn_wire_filesystem+904(%rip)
	.size	w00056, .-w00056
	.symver	w00056, llistxattr@@GLIBC_2.3

	.globl	w00057
	.type	w00057,@function
w00057:
	jmp	*__esn_wire_filesystem+920(%rip)
	.size	w00057, .-w00057
	.symver	w00057, lockf@@GLIBC_2.2.5

	.weak	w00058
	.type	w00058,@function
w00058:
	jmp	*__esn_wire_filesystem+936(%rip)
	.size	w00058, .-w00058
	.symver	w00058, lockf64@@GLIBC_2.2.5

	.globl	w00059
	.type	w00059,@function
w00059:
	jmp	*__esn_wire_filesystem+952(%rip)
	.size	w00059, .-w00059
	.symver	w00059, lremovexattr@@GLIBC_2.3

	.globl	w00060
	.type	w00060,@function
w00060:
	jmp	*__esn_wire_filesystem+968(%rip)
	.size	w00060, .-w00060
	.symver	w00060, lsetxattr@@GLIBC_2.3

	.weak	w00061
	.type	w00061,@function
w00061:
	jmp	*__esn_wire_filesystem+984(%rip)
	.size	w00061, .-w00061
	.symver	w00061, mkdir@@GLIBC_2.2.5

	.globl	w00062
	.type	w00062,@function
w00062:
	jmp	*__esn_wire_filesystem+1000(%rip)
	.size	w00062, .-w00062
	.symver	w00062, mkdirat@@GLIBC_2.4

	.globl	w00063
	.type	w00063,@function
w00063:
	jmp	*__esn_wire_filesystem+1016(%rip)
	.size	w00063, .-w00063
	.symver	w00063, mkfifo@@GLIBC_2.2.5

	.globl	w00064
	.type	w00064,@function
w00064:
	jmp	*__esn_wire_filesystem+1032(%rip)
	.size	w00064, .-w00064
	.symver	w00064, mkfifoat@@GLIBC_2.4

	.weak	w00065
	.type	w00065,@function
w00065:
	jmp	*__esn_wire_filesystem+1048(%rip)
	.size	w00065, .-w00065
	.symver	w00065, mount@@GLIBC_2.2.5

	.globl	w00066
	.type	w00066,@function
w00066:
	jmp	*__esn_wire_filesystem+1064(%rip)
	.size	w00066, .-w00066
	.symver	w00066, nftw@GLIBC_2.2.5

	.globl	w00067
	.type	w00067,@function
w00067:
	jmp	*__esn_wire_filesystem+1080(%rip)
	.size	w00067, .-w00067
	.symver	w00067, nftw@@GLIBC_2.3.3

	.globl	w00068
	.type	w00068,@function
w00068:
	jmp	*__esn_wire_filesystem+1096(%rip)
	.size	w00068, .-w00068
	.symver	w00068, nftw64@GLIBC_2.2.5

	.globl	w00069
	.type	w00069,@function
w00069:
	jmp	*__esn_wire_filesystem+1112(%rip)
	.size	w00069, .-w00069
	.symver	w00069, nftw64@@GLIBC_2.3.3

	.weak	w00074
	.type	w00074,@function
w00074:
	jmp	*__esn_wire_filesystem+1192(%rip)
	.size	w00074, .-w00074
	.symver	w00074, opendir@@GLIBC_2.2.5

	.globl	w00075
	.type	w00075,@function
w00075:
	jmp	*__esn_wire_filesystem+1208(%rip)
	.size	w00075, .-w00075
	.symver	w00075, posix_fadvise@@GLIBC_2.2.5

	.weak	w00076
	.type	w00076,@function
w00076:
	jmp	*__esn_wire_filesystem+1224(%rip)
	.size	w00076, .-w00076
	.symver	w00076, posix_fadvise64@@GLIBC_2.2.5

	.globl	w00077
	.type	w00077,@function
w00077:
	jmp	*__esn_wire_filesystem+1240(%rip)
	.size	w00077, .-w00077
	.symver	w00077, posix_fallocate@@GLIBC_2.2.5

	.globl	w00078
	.type	w00078,@function
w00078:
	jmp	*__esn_wire_filesystem+1256(%rip)
	.size	w00078, .-w00078
	.symver	w00078, posix_fallocate64@@GLIBC_2.2.5

	.globl	w00079
	.type	w00079,@function
w00079:
	jmp	*__esn_wire_filesystem+1272(%rip)
	.size	w00079, .-w00079
	.symver	w00079, quotactl@@GLIBC_2.2.5

	.globl	w00083
	.type	w00083,@function
w00083:
	jmp	*__esn_wire_filesystem+1336(%rip)
	.size	w00083, .-w00083
	.symver	w00083, removexattr@@GLIBC_2.3

	.weak	w00084
	.type	w00084,@function
w00084:
	jmp	*__esn_wire_filesystem+1352(%rip)
	.size	w00084, .-w00084
	.symver	w00084, rewinddir@@GLIBC_2.2.5

	.weak	w00087
	.type	w00087,@function
w00087:
	jmp	*__esn_wire_filesystem+1400(%rip)
	.size	w00087, .-w00087
	.symver	w00087, scandirat@@GLIBC_2.15

	.globl	w00088
	.type	w00088,@function
w00088:
	jmp	*__esn_wire_filesystem+1416(%rip)
	.size	w00088, .-w00088
	.symver	w00088, scandirat64@@GLIBC_2.15

	.globl	w00089
	.type	w00089,@function
w00089:
	jmp	*__esn_wire_filesystem+1432(%rip)
	.size	w00089, .-w00089
	.symver	w00089, seekdir@@GLIBC_2.2.5

	.weak	w00090
	.type	w00090,@function
w00090:
	jmp	*__esn_wire_filesystem+1448(%rip)
	.size	w00090, .-w00090
	.symver	w00090, setmntent@@GLIBC_2.2.5

	.globl	w00091
	.type	w00091,@function
w00091:
	jmp	*__esn_wire_filesystem+1464(%rip)
	.size	w00091, .-w00091
	.symver	w00091, setxattr@@GLIBC_2.3

	.globl	w00096
	.type	w00096,@function
w00096:
	jmp	*__esn_wire_filesystem+1544(%rip)
	.size	w00096, .-w00096
	.symver	w00096, telldir@@GLIBC_2.2.5

	.weak	w00097
	.type	w00097,@function
w00097:
	jmp	*__esn_wire_filesystem+1560(%rip)
	.size	w00097, .-w00097
	.symver	w00097, umask@@GLIBC_2.2.5

	.weak	w00098
	.type	w00098,@function
w00098:
	jmp	*__esn_wire_filesystem+1576(%rip)
	.size	w00098, .-w00098
	.symver	w00098, umount@@GLIBC_2.2.5

	.globl	w00099
	.type	w00099,@function
w00099:
	jmp	*__esn_wire_filesystem+1592(%rip)
	.size	w00099, .-w00099
	.symver	w00099, utime@@GLIBC_2.2.5

	.globl	w00100
	.type	w00100,@function
w00100:
	jmp	*__esn_wire_filesystem+1608(%rip)
	.size	w00100, .-w00100
	.symver	w00100, utimensat@@GLIBC_2.6

	.weak	w00101
	.type	w00101,@function
w00101:
	jmp	*__esn_wire_filesystem+1624(%rip)
	.size	w00101, .-w00101
	.symver	w00101, versionsort@@GLIBC_2.2.5

	.weak	w00102
	.type	w00102,@function
w00102:
	jmp	*__esn_wire_filesystem+1640(%rip)
	.size	w00102, .-w00102
	.symver	w00102, versionsort64@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
