/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice process; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_process[] = {
    { "getpriority", 0 },   /* getpriority@GLIBC_2.2.5 forward-same */
    { "getrlimit", 0 },   /* getrlimit@GLIBC_2.2.5 shim */
    { "getrlimit", 0 },   /* getrlimit64@GLIBC_2.2.5 shim */
    { "getrusage", 0 },   /* getrusage@GLIBC_2.2.5 forward-same */
    { "posix_spawn", 0 },   /* posix_spawn@GLIBC_2.15 forward-same */
    { "posix_spawn", 0 },   /* posix_spawn@GLIBC_2.2.5 forward-same */
    { "posix_spawn_file_actions_addclose", 0 },   /* posix_spawn_file_actions_addclose@GLIBC_2.2.5 forward-same */
    { "posix_spawn_file_actions_adddup2", 0 },   /* posix_spawn_file_actions_adddup2@GLIBC_2.2.5 forward-same */
    { "posix_spawn_file_actions_addopen", 0 },   /* posix_spawn_file_actions_addopen@GLIBC_2.2.5 forward-same */
    { "posix_spawn_file_actions_destroy", 0 },   /* posix_spawn_file_actions_destroy@GLIBC_2.2.5 forward-same */
    { "posix_spawn_file_actions_init", 0 },   /* posix_spawn_file_actions_init@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_destroy", 0 },   /* posix_spawnattr_destroy@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_getflags", 0 },   /* posix_spawnattr_getflags@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_getpgroup", 0 },   /* posix_spawnattr_getpgroup@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_getschedparam", 0 },   /* posix_spawnattr_getschedparam@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_getschedpolicy", 0 },   /* posix_spawnattr_getschedpolicy@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_getsigdefault", 0 },   /* posix_spawnattr_getsigdefault@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_getsigmask", 0 },   /* posix_spawnattr_getsigmask@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_init", 0 },   /* posix_spawnattr_init@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_setflags", 0 },   /* posix_spawnattr_setflags@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_setpgroup", 0 },   /* posix_spawnattr_setpgroup@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_setschedparam", 0 },   /* posix_spawnattr_setschedparam@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_setschedpolicy", 0 },   /* posix_spawnattr_setschedpolicy@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_setsigdefault", 0 },   /* posix_spawnattr_setsigdefault@GLIBC_2.2.5 forward-same */
    { "posix_spawnattr_setsigmask", 0 },   /* posix_spawnattr_setsigmask@GLIBC_2.2.5 forward-same */
    { "posix_spawnp", 0 },   /* posix_spawnp@GLIBC_2.15 forward-same */
    { "posix_spawnp", 0 },   /* posix_spawnp@GLIBC_2.2.5 forward-same */
    { "sched_get_priority_max", 0 },   /* sched_get_priority_max@GLIBC_2.2.5 forward-same */
    { "sched_get_priority_min", 0 },   /* sched_get_priority_min@GLIBC_2.2.5 forward-same */
    { "sched_getaffinity", 0 },   /* sched_getaffinity@GLIBC_2.3.3 forward-same */
    { "sched_getaffinity", 0 },   /* sched_getaffinity@GLIBC_2.3.4 forward-same */
    { "sched_getcpu", 0 },   /* sched_getcpu@GLIBC_2.6 forward-same */
    { "sched_getparam", 0 },   /* sched_getparam@GLIBC_2.2.5 forward-same */
    { "sched_getscheduler", 0 },   /* sched_getscheduler@GLIBC_2.2.5 forward-same */
    { "sched_rr_get_interval", 0 },   /* sched_rr_get_interval@GLIBC_2.2.5 forward-same */
    { "sched_setaffinity", 0 },   /* sched_setaffinity@GLIBC_2.3.3 forward-same */
    { "sched_setaffinity", 0 },   /* sched_setaffinity@GLIBC_2.3.4 forward-same */
    { "sched_setparam", 0 },   /* sched_setparam@GLIBC_2.2.5 forward-same */
    { "sched_setscheduler", 0 },   /* sched_setscheduler@GLIBC_2.2.5 forward-same */
    { "sched_yield", 0 },   /* sched_yield@GLIBC_2.2.5 forward-same */
    { "setpriority", 0 },   /* setpriority@GLIBC_2.2.5 forward-same */
    { "setrlimit", 0 },   /* setrlimit@GLIBC_2.2.5 shim */
    { "setrlimit", 0 },   /* setrlimit64@GLIBC_2.2.5 shim */
    { "wait", 0 },   /* wait@GLIBC_2.2.5 forward-same */
    { "wait3", 0 },   /* wait3@GLIBC_2.2.5 forward-same */
    { "wait4", 0 },   /* wait4@GLIBC_2.2.5 forward-same */
    { "waitpid", 0 },   /* waitpid@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_process_n = sizeof __esn_wire_process / sizeof *__esn_wire_process;

