/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice posix; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_posix+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, __getpgid@@GLIBC_2.2.5

	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_posix+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, _exit@@GLIBC_2.2.5

	.weak	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_posix+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, access@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_posix+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, alarm@@GLIBC_2.2.5

	.weak	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_posix+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, chdir@@GLIBC_2.2.5

	.weak	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_posix+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, chown@@GLIBC_2.2.5

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_posix+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, chroot@@GLIBC_2.2.5

	.weak	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_posix+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, close@@GLIBC_2.2.5

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_posix+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, confstr@@GLIBC_2.2.5

	.globl	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_posix+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, daemon@@GLIBC_2.2.5

	.weak	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_posix+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, dup@@GLIBC_2.2.5

	.weak	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_posix+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, dup2@@GLIBC_2.2.5

	.weak	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_posix+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, dup3@@GLIBC_2.9

	.weak	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_posix+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, eaccess@@GLIBC_2.4

	.globl	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_posix+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, endusershell@@GLIBC_2.2.5

	.weak	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_posix+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, euidaccess@@GLIBC_2.2.5

	.globl	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_posix+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, execl@@GLIBC_2.2.5

	.globl	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_posix+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, execle@@GLIBC_2.2.5

	.globl	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_posix+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, execlp@@GLIBC_2.2.5

	.globl	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_posix+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, execv@@GLIBC_2.2.5

	.weak	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_posix+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, execve@@GLIBC_2.2.5

	.globl	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_posix+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, execvp@@GLIBC_2.2.5

	.weak	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_posix+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, execvpe@@GLIBC_2.11

	.globl	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_posix+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, faccessat@@GLIBC_2.4

	.weak	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_posix+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, fchdir@@GLIBC_2.2.5

	.weak	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_posix+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, fchown@@GLIBC_2.2.5

	.globl	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_posix+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, fchownat@@GLIBC_2.4

	.globl	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_posix+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, fdatasync@@GLIBC_2.2.5

	.globl	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_posix+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, fexecve@@GLIBC_2.2.5

	.weak	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_posix+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, fork@@GLIBC_2.2.5

	.weak	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_posix+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, fpathconf@@GLIBC_2.2.5

	.globl	w00031
	.type	w00031,@function
w00031:
	jmp	*__esn_wire_posix+504(%rip)
	.size	w00031, .-w00031
	.symver	w00031, fsync@@GLIBC_2.2.5

	.weak	w00032
	.type	w00032,@function
w00032:
	jmp	*__esn_wire_posix+520(%rip)
	.size	w00032, .-w00032
	.symver	w00032, ftruncate@@GLIBC_2.2.5

	.weak	w00033
	.type	w00033,@function
w00033:
	jmp	*__esn_wire_posix+536(%rip)
	.size	w00033, .-w00033
	.symver	w00033, ftruncate64@@GLIBC_2.2.5

	.globl	w00034
	.type	w00034,@function
w00034:
	jmp	*__esn_wire_posix+552(%rip)
	.size	w00034, .-w00034
	.symver	w00034, get_current_dir_name@@GLIBC_2.2.5

	.weak	w00035
	.type	w00035,@function
w00035:
	jmp	*__esn_wire_posix+568(%rip)
	.size	w00035, .-w00035
	.symver	w00035, getcwd@@GLIBC_2.2.5

	.globl	w00036
	.type	w00036,@function
w00036:
	jmp	*__esn_wire_posix+584(%rip)
	.size	w00036, .-w00036
	.symver	w00036, getdomainname@@GLIBC_2.2.5

	.weak	w00037
	.type	w00037,@function
w00037:
	jmp	*__esn_wire_posix+600(%rip)
	.size	w00037, .-w00037
	.symver	w00037, getdtablesize@@GLIBC_2.2.5

	.weak	w00038
	.type	w00038,@function
w00038:
	jmp	*__esn_wire_posix+616(%rip)
	.size	w00038, .-w00038
	.symver	w00038, getegid@@GLIBC_2.2.5

	.weak	w00039
	.type	w00039,@function
w00039:
	jmp	*__esn_wire_posix+632(%rip)
	.size	w00039, .-w00039
	.symver	w00039, geteuid@@GLIBC_2.2.5

	.weak	w00040
	.type	w00040,@function
w00040:
	jmp	*__esn_wire_posix+648(%rip)
	.size	w00040, .-w00040
	.symver	w00040, getgid@@GLIBC_2.2.5

	.weak	w00041
	.type	w00041,@function
w00041:
	jmp	*__esn_wire_posix+664(%rip)
	.size	w00041, .-w00041
	.symver	w00041, getgroups@@GLIBC_2.2.5

	.globl	w00042
	.type	w00042,@function
w00042:
	jmp	*__esn_wire_posix+680(%rip)
	.size	w00042, .-w00042
	.symver	w00042, gethostid@@GLIBC_2.2.5

	.weak	w00043
	.type	w00043,@function
w00043:
	jmp	*__esn_wire_posix+696(%rip)
	.size	w00043, .-w00043
	.symver	w00043, gethostname@@GLIBC_2.2.5

	.globl	w00044
	.type	w00044,@function
w00044:
	jmp	*__esn_wire_posix+712(%rip)
	.size	w00044, .-w00044
	.symver	w00044, getlogin@@GLIBC_2.2.5

	.weak	w00045
	.type	w00045,@function
w00045:
	jmp	*__esn_wire_posix+728(%rip)
	.size	w00045, .-w00045
	.symver	w00045, getlogin_r@@GLIBC_2.2.5

	.weak	w00046
	.type	w00046,@function
w00046:
	jmp	*__esn_wire_posix+744(%rip)
	.size	w00046, .-w00046
	.symver	w00046, getpagesize@@GLIBC_2.2.5

	.globl	w00047
	.type	w00047,@function
w00047:
	jmp	*__esn_wire_posix+760(%rip)
	.size	w00047, .-w00047
	.symver	w00047, getpass@@GLIBC_2.2.5

	.weak	w00048
	.type	w00048,@function
w00048:
	jmp	*__esn_wire_posix+776(%rip)
	.size	w00048, .-w00048
	.symver	w00048, getpgid@@GLIBC_2.2.5

	.globl	w00049
	.type	w00049,@function
w00049:
	jmp	*__esn_wire_posix+792(%rip)
	.size	w00049, .-w00049
	.symver	w00049, getpgrp@@GLIBC_2.2.5

	.weak	w00050
	.type	w00050,@function
w00050:
	jmp	*__esn_wire_posix+808(%rip)
	.size	w00050, .-w00050
	.symver	w00050, getpid@@GLIBC_2.2.5

	.weak	w00051
	.type	w00051,@function
w00051:
	jmp	*__esn_wire_posix+824(%rip)
	.size	w00051, .-w00051
	.symver	w00051, getppid@@GLIBC_2.2.5

	.globl	w00052
	.type	w00052,@function
w00052:
	jmp	*__esn_wire_posix+840(%rip)
	.size	w00052, .-w00052
	.symver	w00052, getsid@@GLIBC_2.2.5

	.weak	w00053
	.type	w00053,@function
w00053:
	jmp	*__esn_wire_posix+856(%rip)
	.size	w00053, .-w00053
	.symver	w00053, getuid@@GLIBC_2.2.5

	.globl	w00054
	.type	w00054,@function
w00054:
	jmp	*__esn_wire_posix+872(%rip)
	.size	w00054, .-w00054
	.symver	w00054, getusershell@@GLIBC_2.2.5

	.globl	w00055
	.type	w00055,@function
w00055:
	jmp	*__esn_wire_posix+888(%rip)
	.size	w00055, .-w00055
	.symver	w00055, getwd@@GLIBC_2.2.5

	.weak	w00056
	.type	w00056,@function
w00056:
	jmp	*__esn_wire_posix+904(%rip)
	.size	w00056, .-w00056
	.symver	w00056, isatty@@GLIBC_2.2.5

	.weak	w00057
	.type	w00057,@function
w00057:
	jmp	*__esn_wire_posix+920(%rip)
	.size	w00057, .-w00057
	.symver	w00057, lchown@@GLIBC_2.2.5

	.weak	w00058
	.type	w00058,@function
w00058:
	jmp	*__esn_wire_posix+936(%rip)
	.size	w00058, .-w00058
	.symver	w00058, link@@GLIBC_2.2.5

	.globl	w00059
	.type	w00059,@function
w00059:
	jmp	*__esn_wire_posix+952(%rip)
	.size	w00059, .-w00059
	.symver	w00059, linkat@@GLIBC_2.4

	.weak	w00060
	.type	w00060,@function
w00060:
	jmp	*__esn_wire_posix+968(%rip)
	.size	w00060, .-w00060
	.symver	w00060, lseek@@GLIBC_2.2.5

	.weak	w00061
	.type	w00061,@function
w00061:
	jmp	*__esn_wire_posix+984(%rip)
	.size	w00061, .-w00061
	.symver	w00061, lseek64@@GLIBC_2.2.5

	.globl	w00062
	.type	w00062,@function
w00062:
	jmp	*__esn_wire_posix+1000(%rip)
	.size	w00062, .-w00062
	.symver	w00062, nice@@GLIBC_2.2.5

	.weak	w00063
	.type	w00063,@function
w00063:
	jmp	*__esn_wire_posix+1016(%rip)
	.size	w00063, .-w00063
	.symver	w00063, pathconf@@GLIBC_2.2.5

	.weak	w00064
	.type	w00064,@function
w00064:
	jmp	*__esn_wire_posix+1032(%rip)
	.size	w00064, .-w00064
	.symver	w00064, pause@@GLIBC_2.2.5

	.weak	w00065
	.type	w00065,@function
w00065:
	jmp	*__esn_wire_posix+1048(%rip)
	.size	w00065, .-w00065
	.symver	w00065, pipe@@GLIBC_2.2.5

	.weak	w00066
	.type	w00066,@function
w00066:
	jmp	*__esn_wire_posix+1064(%rip)
	.size	w00066, .-w00066
	.symver	w00066, pipe2@@GLIBC_2.9

	.weak	w00067
	.type	w00067,@function
w00067:
	jmp	*__esn_wire_posix+1080(%rip)
	.size	w00067, .-w00067
	.symver	w00067, pread@@GLIBC_2.2.5

	.weak	w00068
	.type	w00068,@function
w00068:
	jmp	*__esn_wire_posix+1096(%rip)
	.size	w00068, .-w00068
	.symver	w00068, pread64@@GLIBC_2.2.5

	.weak	w00069
	.type	w00069,@function
w00069:
	jmp	*__esn_wire_posix+1112(%rip)
	.size	w00069, .-w00069
	.symver	w00069, pwrite@@GLIBC_2.2.5

	.weak	w00070
	.type	w00070,@function
w00070:
	jmp	*__esn_wire_posix+1128(%rip)
	.size	w00070, .-w00070
	.symver	w00070, pwrite64@@GLIBC_2.2.5

	.globl	w00071
	.type	w00071,@function
w00071:
	jmp	*__esn_wire_posix+1144(%rip)
	.size	w00071, .-w00071
	.symver	w00071, read@@GLIBC_2.2.5

	.weak	w00072
	.type	w00072,@function
w00072:
	jmp	*__esn_wire_posix+1160(%rip)
	.size	w00072, .-w00072
	.symver	w00072, readlink@@GLIBC_2.2.5

	.globl	w00073
	.type	w00073,@function
w00073:
	jmp	*__esn_wire_posix+1176(%rip)
	.size	w00073, .-w00073
	.symver	w00073, readlinkat@@GLIBC_2.4

	.weak	w00074
	.type	w00074,@function
w00074:
	jmp	*__esn_wire_posix+1192(%rip)
	.size	w00074, .-w00074
	.symver	w00074, revoke@@GLIBC_2.2.5

	.weak	w00075
	.type	w00075,@function
w00075:
	jmp	*__esn_wire_posix+1208(%rip)
	.size	w00075, .-w00075
	.symver	w00075, rmdir@@GLIBC_2.2.5

	.weak	w00076
	.type	w00076,@function
w00076:
	jmp	*__esn_wire_posix+1224(%rip)
	.size	w00076, .-w00076
	.symver	w00076, sbrk@@GLIBC_2.2.5

	.globl	w00077
	.type	w00077,@function
w00077:
	jmp	*__esn_wire_posix+1240(%rip)
	.size	w00077, .-w00077
	.symver	w00077, setegid@@GLIBC_2.2.5

	.globl	w00078
	.type	w00078,@function
w00078:
	jmp	*__esn_wire_posix+1256(%rip)
	.size	w00078, .-w00078
	.symver	w00078, seteuid@@GLIBC_2.2.5

	.weak	w00079
	.type	w00079,@function
w00079:
	jmp	*__esn_wire_posix+1272(%rip)
	.size	w00079, .-w00079
	.symver	w00079, setgid@@GLIBC_2.2.5

	.globl	w00080
	.type	w00080,@function
w00080:
	jmp	*__esn_wire_posix+1288(%rip)
	.size	w00080, .-w00080
	.symver	w00080, sethostname@@GLIBC_2.2.5

	.weak	w00081
	.type	w00081,@function
w00081:
	jmp	*__esn_wire_posix+1304(%rip)
	.size	w00081, .-w00081
	.symver	w00081, setpgid@@GLIBC_2.2.5

	.globl	w00082
	.type	w00082,@function
w00082:
	jmp	*__esn_wire_posix+1320(%rip)
	.size	w00082, .-w00082
	.symver	w00082, setpgrp@@GLIBC_2.2.5

	.weak	w00083
	.type	w00083,@function
w00083:
	jmp	*__esn_wire_posix+1336(%rip)
	.size	w00083, .-w00083
	.symver	w00083, setregid@@GLIBC_2.2.5

	.weak	w00084
	.type	w00084,@function
w00084:
	jmp	*__esn_wire_posix+1352(%rip)
	.size	w00084, .-w00084
	.symver	w00084, setreuid@@GLIBC_2.2.5

	.weak	w00085
	.type	w00085,@function
w00085:
	jmp	*__esn_wire_posix+1368(%rip)
	.size	w00085, .-w00085
	.symver	w00085, setsid@@GLIBC_2.2.5

	.weak	w00086
	.type	w00086,@function
w00086:
	jmp	*__esn_wire_posix+1384(%rip)
	.size	w00086, .-w00086
	.symver	w00086, setuid@@GLIBC_2.2.5

	.globl	w00087
	.type	w00087,@function
w00087:
	jmp	*__esn_wire_posix+1400(%rip)
	.size	w00087, .-w00087
	.symver	w00087, setusershell@@GLIBC_2.2.5

	.weak	w00088
	.type	w00088,@function
w00088:
	jmp	*__esn_wire_posix+1416(%rip)
	.size	w00088, .-w00088
	.symver	w00088, sleep@@GLIBC_2.2.5

	.globl	w00089
	.type	w00089,@function
w00089:
	jmp	*__esn_wire_posix+1432(%rip)
	.size	w00089, .-w00089
	.symver	w00089, swab@@GLIBC_2.2.5

	.weak	w00090
	.type	w00090,@function
w00090:
	jmp	*__esn_wire_posix+1448(%rip)
	.size	w00090, .-w00090
	.symver	w00090, symlink@@GLIBC_2.2.5

	.globl	w00091
	.type	w00091,@function
w00091:
	jmp	*__esn_wire_posix+1464(%rip)
	.size	w00091, .-w00091
	.symver	w00091, symlinkat@@GLIBC_2.4

	.globl	w00092
	.type	w00092,@function
w00092:
	jmp	*__esn_wire_posix+1480(%rip)
	.size	w00092, .-w00092
	.symver	w00092, sync@@GLIBC_2.2.5

	.weak	w00093
	.type	w00093,@function
w00093:
	jmp	*__esn_wire_posix+1496(%rip)
	.size	w00093, .-w00093
	.symver	w00093, sysconf@@GLIBC_2.2.5

	.globl	w00094
	.type	w00094,@function
w00094:
	jmp	*__esn_wire_posix+1512(%rip)
	.size	w00094, .-w00094
	.symver	w00094, tcgetpgrp@@GLIBC_2.2.5

	.globl	w00095
	.type	w00095,@function
w00095:
	jmp	*__esn_wire_posix+1528(%rip)
	.size	w00095, .-w00095
	.symver	w00095, tcsetpgrp@@GLIBC_2.2.5

	.weak	w00096
	.type	w00096,@function
w00096:
	jmp	*__esn_wire_posix+1544(%rip)
	.size	w00096, .-w00096
	.symver	w00096, truncate@@GLIBC_2.2.5

	.weak	w00097
	.type	w00097,@function
w00097:
	jmp	*__esn_wire_posix+1560(%rip)
	.size	w00097, .-w00097
	.symver	w00097, truncate64@@GLIBC_2.2.5

	.globl	w00098
	.type	w00098,@function
w00098:
	jmp	*__esn_wire_posix+1576(%rip)
	.size	w00098, .-w00098
	.symver	w00098, ttyname@@GLIBC_2.2.5

	.weak	w00099
	.type	w00099,@function
w00099:
	jmp	*__esn_wire_posix+1592(%rip)
	.size	w00099, .-w00099
	.symver	w00099, ttyname_r@@GLIBC_2.2.5

	.globl	w00100
	.type	w00100,@function
w00100:
	jmp	*__esn_wire_posix+1608(%rip)
	.size	w00100, .-w00100
	.symver	w00100, ttyslot@@GLIBC_2.2.5

	.globl	w00101
	.type	w00101,@function
w00101:
	jmp	*__esn_wire_posix+1624(%rip)
	.size	w00101, .-w00101
	.symver	w00101, ualarm@@GLIBC_2.2.5

	.weak	w00102
	.type	w00102,@function
w00102:
	jmp	*__esn_wire_posix+1640(%rip)
	.size	w00102, .-w00102
	.symver	w00102, unlink@@GLIBC_2.2.5

	.globl	w00103
	.type	w00103,@function
w00103:
	jmp	*__esn_wire_posix+1656(%rip)
	.size	w00103, .-w00103
	.symver	w00103, unlinkat@@GLIBC_2.4

	.globl	w00104
	.type	w00104,@function
w00104:
	jmp	*__esn_wire_posix+1672(%rip)
	.size	w00104, .-w00104
	.symver	w00104, usleep@@GLIBC_2.2.5

	.weak	w00105
	.type	w00105,@function
w00105:
	jmp	*__esn_wire_posix+1688(%rip)
	.size	w00105, .-w00105
	.symver	w00105, vfork@@GLIBC_2.2.5

	.globl	w00106
	.type	w00106,@function
w00106:
	jmp	*__esn_wire_posix+1704(%rip)
	.size	w00106, .-w00106
	.symver	w00106, vhangup@@GLIBC_2.2.5

	.weak	w00107
	.type	w00107,@function
w00107:
	jmp	*__esn_wire_posix+1720(%rip)
	.size	w00107, .-w00107
	.symver	w00107, write@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
