/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice time; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_time+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, asctime@@GLIBC_2.2.5

	.weak	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_time+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, asctime_r@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_time+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, clock@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_time+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, clock_getcpuclockid@@GLIBC_2.17

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_time+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, clock_getcpuclockid@GLIBC_2.2.5

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_time+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, clock_getres@@GLIBC_2.17

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_time+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, clock_getres@GLIBC_2.2.5

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_time+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, clock_gettime@@GLIBC_2.17

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_time+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, clock_gettime@GLIBC_2.2.5

	.globl	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_time+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, clock_nanosleep@@GLIBC_2.17

	.globl	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_time+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, clock_nanosleep@GLIBC_2.2.5

	.globl	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_time+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, clock_settime@@GLIBC_2.17

	.globl	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_time+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, clock_settime@GLIBC_2.2.5

	.globl	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_time+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, ctime@@GLIBC_2.2.5

	.globl	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_time+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, ctime_r@@GLIBC_2.2.5

	.globl	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_time+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, difftime@@GLIBC_2.2.5

	.globl	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_time+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, ftime@@GLIBC_2.2.5

	.weak	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_time+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, futimes@@GLIBC_2.3

	.globl	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_time+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, futimesat@@GLIBC_2.4

	.weak	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_time+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, getitimer@@GLIBC_2.2.5

	.globl	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_time+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, gmtime@@GLIBC_2.2.5

	.weak	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_time+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, gmtime_r@@GLIBC_2.2.5

	.globl	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_time+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, localtime@@GLIBC_2.2.5

	.weak	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_time+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, localtime_r@@GLIBC_2.2.5

	.globl	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_time+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, lutimes@@GLIBC_2.3

	.globl	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_time+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, mktime@@GLIBC_2.2.5

	.weak	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_time+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, nanosleep@@GLIBC_2.2.5

	.weak	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_time+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, setitimer@@GLIBC_2.2.5

	.weak	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_time+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, settimeofday@@GLIBC_2.2.5

	.globl	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_time+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, stime@@GLIBC_2.2.5

	.globl	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_time+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, strftime@@GLIBC_2.2.5

	.weak	w00031
	.type	w00031,@function
w00031:
	jmp	*__esn_wire_time+504(%rip)
	.size	w00031, .-w00031
	.symver	w00031, strftime_l@@GLIBC_2.3

	.globl	w00032
	.type	w00032,@function
w00032:
	jmp	*__esn_wire_time+520(%rip)
	.size	w00032, .-w00032
	.symver	w00032, strptime@@GLIBC_2.2.5

	.weak	w00033
	.type	w00033,@function
w00033:
	jmp	*__esn_wire_time+536(%rip)
	.size	w00033, .-w00033
	.symver	w00033, strptime_l@@GLIBC_2.3.2

	.globl	w00034
	.type	w00034,@function
w00034:
	jmp	*__esn_wire_time+552(%rip)
	.size	w00034, .-w00034
	.symver	w00034, timegm@@GLIBC_2.2.5

	.weak	w00035
	.type	w00035,@function
w00035:
	jmp	*__esn_wire_time+568(%rip)
	.size	w00035, .-w00035
	.symver	w00035, timelocal@@GLIBC_2.2.5

	.weak	w00036
	.type	w00036,@function
w00036:
	jmp	*__esn_wire_time+584(%rip)
	.size	w00036, .-w00036
	.symver	w00036, times@@GLIBC_2.2.5

	.globl	w00037
	.type	w00037,@function
w00037:
	jmp	*__esn_wire_time+600(%rip)
	.size	w00037, .-w00037
	.symver	w00037, timespec_get@@GLIBC_2.16

	.weak	w00038
	.type	w00038,@function
w00038:
	jmp	*__esn_wire_time+616(%rip)
	.size	w00038, .-w00038
	.symver	w00038, tzset@@GLIBC_2.2.5

	.weak	w00039
	.type	w00039,@function
w00039:
	jmp	*__esn_wire_time+632(%rip)
	.size	w00039, .-w00039
	.symver	w00039, utimes@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
