/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice system; do not edit */
	.text
	.weak	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_system+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, get_avphys_pages@@GLIBC_2.2.5

	.weak	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_system+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, get_nprocs@@GLIBC_2.2.5

	.weak	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_system+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, get_nprocs_conf@@GLIBC_2.2.5

	.weak	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_system+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, get_phys_pages@@GLIBC_2.2.5

	.weak	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_system+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, sysinfo@@GLIBC_2.2.5

	.weak	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_system+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, uname@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
