/* generated by gen-wire.py from fwd-sockets.tsv + symbol-slice.tsv, slice sockets; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_sockets[] = {
    { "accept", 0 },   /* accept@GLIBC_2.2.5 forward-same */
    { "accept4", 0 },   /* accept4@GLIBC_2.10 forward-same */
    { "bind", 0 },   /* bind@GLIBC_2.2.5 forward-same */
    { "bindresvport", 0 },   /* bindresvport@GLIBC_2.2.5 forward-same */
    { "connect", 0 },   /* connect@GLIBC_2.2.5 forward-same */
    { "endhostent", 0 },   /* endhostent@GLIBC_2.2.5 forward-same */
    { "endprotoent", 0 },   /* endprotoent@GLIBC_2.2.5 forward-same */
    { "endservent", 0 },   /* endservent@GLIBC_2.2.5 forward-same */
    { "freeaddrinfo", 0 },   /* freeaddrinfo@GLIBC_2.2.5 forward-same */
    { "freeifaddrs", 0 },   /* freeifaddrs@GLIBC_2.3 forward-same */
    { "gai_strerror", 0 },   /* gai_strerror@GLIBC_2.2.5 forward-same */
    { "getaddrinfo", 0 },   /* getaddrinfo@GLIBC_2.2.5 forward-same */
    { "gethostbyaddr", 0 },   /* gethostbyaddr@GLIBC_2.2.5 forward-same */
    { "gethostbyname", 0 },   /* gethostbyname@GLIBC_2.2.5 forward-same */
    { "gethostbyname2", 0 },   /* gethostbyname2@GLIBC_2.2.5 forward-same */
    { "getifaddrs", 0 },   /* getifaddrs@GLIBC_2.3 forward-same */
    { "getnameinfo", 0 },   /* getnameinfo@GLIBC_2.2.5 forward-same */
    { "getpeername", 0 },   /* getpeername@GLIBC_2.2.5 forward-same */
    { "getprotobyname", 0 },   /* getprotobyname@GLIBC_2.2.5 forward-same */
    { "getprotobynumber", 0 },   /* getprotobynumber@GLIBC_2.2.5 forward-same */
    { "getprotoent", 0 },   /* getprotoent@GLIBC_2.2.5 forward-same */
    { "getservbyname", 0 },   /* getservbyname@GLIBC_2.2.5 forward-same */
    { "getservbyport", 0 },   /* getservbyport@GLIBC_2.2.5 forward-same */
    { "getservent", 0 },   /* getservent@GLIBC_2.2.5 forward-same */
    { "getsockname", 0 },   /* getsockname@GLIBC_2.2.5 forward-same */
    { "getsockopt", 0 },   /* getsockopt@GLIBC_2.2.5 forward-same */
    { "herror", 0 },   /* herror@GLIBC_2.2.5 forward-same */
    { "hstrerror", 0 },   /* hstrerror@GLIBC_2.2.5 forward-same */
    { "htonl", 0 },   /* htonl@GLIBC_2.2.5 forward-same */
    { "htons", 0 },   /* htons@GLIBC_2.2.5 forward-same */
    { "if_freenameindex", 0 },   /* if_freenameindex@GLIBC_2.2.5 forward-same */
    { "if_indextoname", 0 },   /* if_indextoname@GLIBC_2.2.5 forward-same */
    { "if_nameindex", 0 },   /* if_nameindex@GLIBC_2.2.5 forward-same */
    { "if_nametoindex", 0 },   /* if_nametoindex@GLIBC_2.2.5 forward-same */
    { "inet_addr", 0 },   /* inet_addr@GLIBC_2.2.5 forward-same */
    { "inet_aton", 0 },   /* inet_aton@GLIBC_2.2.5 forward-same */
    { "inet_makeaddr", 0 },   /* inet_makeaddr@GLIBC_2.2.5 forward-same */
    { "inet_netof", 0 },   /* inet_netof@GLIBC_2.2.5 forward-same */
    { "inet_network", 0 },   /* inet_network@GLIBC_2.2.5 forward-same */
    { "inet_ntoa", 0 },   /* inet_ntoa@GLIBC_2.2.5 forward-same */
    { "inet_ntop", 0 },   /* inet_ntop@GLIBC_2.2.5 forward-same */
    { "inet_pton", 0 },   /* inet_pton@GLIBC_2.2.5 forward-same */
    { "iruserok", 0 },   /* iruserok@GLIBC_2.2.5 forward-same */
    { "listen", 0 },   /* listen@GLIBC_2.2.5 forward-same */
    { "ntohl", 0 },   /* ntohl@GLIBC_2.2.5 forward-same */
    { "ntohs", 0 },   /* ntohs@GLIBC_2.2.5 forward-same */
    { "rcmd", 0 },   /* rcmd@GLIBC_2.2.5 forward-same */
    { "rcmd_af", 0 },   /* rcmd_af@GLIBC_2.2.5 forward-same */
    { "recv", 0 },   /* recv@GLIBC_2.2.5 forward-same */
    { "recvfrom", 0 },   /* recvfrom@GLIBC_2.2.5 forward-same */
    { "recvmsg", 0 },   /* recvmsg@GLIBC_2.2.5 forward-same */
    { "rexec", 0 },   /* rexec@GLIBC_2.2.5 forward-same */
    { "rresvport", 0 },   /* rresvport@GLIBC_2.2.5 forward-same */
    { "rresvport_af", 0 },   /* rresvport_af@GLIBC_2.2.5 forward-same */
    { "ruserok", 0 },   /* ruserok@GLIBC_2.2.5 forward-same */
    { "send", 0 },   /* send@GLIBC_2.2.5 forward-same */
    { "sendmsg", 0 },   /* sendmsg@GLIBC_2.2.5 forward-same */
    { "sendto", 0 },   /* sendto@GLIBC_2.2.5 forward-same */
    { "sethostent", 0 },   /* sethostent@GLIBC_2.2.5 forward-same */
    { "setprotoent", 0 },   /* setprotoent@GLIBC_2.2.5 forward-same */
    { "setservent", 0 },   /* setservent@GLIBC_2.2.5 forward-same */
    { "setsockopt", 0 },   /* setsockopt@GLIBC_2.2.5 forward-same */
    { "shutdown", 0 },   /* shutdown@GLIBC_2.2.5 forward-same */
    { "sockatmark", 0 },   /* sockatmark@GLIBC_2.2.5 forward-same */
    { "socket", 0 },   /* socket@GLIBC_2.2.5 forward-same */
    { "socketpair", 0 },   /* socketpair@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_sockets_n = sizeof __esn_wire_sockets / sizeof *__esn_wire_sockets;

