/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice memory; do not edit */
	.text
	.weak	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_memory+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, calloc@@GLIBC_2.2.5

	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_memory+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, free@@GLIBC_2.2.5

	.weak	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_memory+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, madvise@@GLIBC_2.2.5

	.weak	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_memory+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, mallinfo@@GLIBC_2.2.5

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_memory+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, malloc@@GLIBC_2.2.5

	.weak	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_memory+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, malloc_stats@@GLIBC_2.2.5

	.weak	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_memory+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, malloc_trim@@GLIBC_2.2.5

	.weak	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_memory+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, malloc_usable_size@@GLIBC_2.2.5

	.weak	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_memory+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, mallopt@@GLIBC_2.2.5

	.weak	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_memory+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, memalign@@GLIBC_2.2.5

	.globl	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_memory+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, mlock@@GLIBC_2.2.5

	.weak	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_memory+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, mmap@@GLIBC_2.2.5

	.weak	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_memory+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, mmap64@@GLIBC_2.2.5

	.weak	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_memory+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, mprotect@@GLIBC_2.2.5

	.globl	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_memory+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, msync@@GLIBC_2.2.5

	.globl	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_memory+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, munlock@@GLIBC_2.2.5

	.weak	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_memory+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, munmap@@GLIBC_2.2.5

	.globl	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_memory+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, posix_madvise@@GLIBC_2.2.5

	.globl	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_memory+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, realloc@@GLIBC_2.2.5

	.weak	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_memory+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, reallocarray@@GLIBC_2.26

	.weak	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_memory+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, valloc@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
