/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice regex; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_regex[] = {
    { "regcomp", 0 },   /* regcomp@GLIBC_2.2.5 forward-same */
    { "regerror", 0 },   /* regerror@GLIBC_2.2.5 forward-same */
    { "regexec", 0 },   /* regexec@GLIBC_2.2.5 forward-same */
    { "regexec", 0 },   /* regexec@GLIBC_2.3.4 forward-same */
    { "regfree", 0 },   /* regfree@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_regex_n = sizeof __esn_wire_regex / sizeof *__esn_wire_regex;

