/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice io; do not edit */
	.text
	.weak	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_io+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, readv@@GLIBC_2.2.5

	.weak	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_io+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, writev@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
