/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice process; do not edit */
	.text
	.weak	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_process+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, getpriority@@GLIBC_2.2.5

	.weak	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_process+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, getrusage@@GLIBC_2.2.5

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_process+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, posix_spawn@@GLIBC_2.15

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_process+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, posix_spawn@GLIBC_2.2.5

	.weak	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_process+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, posix_spawn_file_actions_addclose@@GLIBC_2.2.5

	.weak	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_process+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, posix_spawn_file_actions_adddup2@@GLIBC_2.2.5

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_process+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, posix_spawn_file_actions_addopen@@GLIBC_2.2.5

	.weak	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_process+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, posix_spawn_file_actions_destroy@@GLIBC_2.2.5

	.weak	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_process+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, posix_spawn_file_actions_init@@GLIBC_2.2.5

	.weak	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_process+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, posix_spawnattr_destroy@@GLIBC_2.2.5

	.globl	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_process+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, posix_spawnattr_getflags@@GLIBC_2.2.5

	.globl	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_process+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, posix_spawnattr_getpgroup@@GLIBC_2.2.5

	.globl	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_process+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, posix_spawnattr_getschedparam@@GLIBC_2.2.5

	.globl	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_process+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, posix_spawnattr_getschedpolicy@@GLIBC_2.2.5

	.globl	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_process+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, posix_spawnattr_getsigdefault@@GLIBC_2.2.5

	.globl	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_process+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, posix_spawnattr_getsigmask@@GLIBC_2.2.5

	.weak	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_process+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, posix_spawnattr_init@@GLIBC_2.2.5

	.weak	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_process+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, posix_spawnattr_setflags@@GLIBC_2.2.5

	.globl	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_process+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, posix_spawnattr_setpgroup@@GLIBC_2.2.5

	.globl	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_process+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, posix_spawnattr_setschedparam@@GLIBC_2.2.5

	.globl	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_process+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, posix_spawnattr_setschedpolicy@@GLIBC_2.2.5

	.weak	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_process+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, posix_spawnattr_setsigdefault@@GLIBC_2.2.5

	.weak	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_process+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, posix_spawnattr_setsigmask@@GLIBC_2.2.5

	.globl	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_process+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, posix_spawnp@@GLIBC_2.15

	.globl	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_process+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, posix_spawnp@GLIBC_2.2.5

	.weak	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_process+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, sched_get_priority_max@@GLIBC_2.2.5

	.weak	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_process+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, sched_get_priority_min@@GLIBC_2.2.5

	.globl	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_process+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, sched_getaffinity@GLIBC_2.3.3

	.globl	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_process+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, sched_getaffinity@@GLIBC_2.3.4

	.globl	w00031
	.type	w00031,@function
w00031:
	jmp	*__esn_wire_process+504(%rip)
	.size	w00031, .-w00031
	.symver	w00031, sched_getcpu@@GLIBC_2.6

	.weak	w00032
	.type	w00032,@function
w00032:
	jmp	*__esn_wire_process+520(%rip)
	.size	w00032, .-w00032
	.symver	w00032, sched_getparam@@GLIBC_2.2.5

	.weak	w00033
	.type	w00033,@function
w00033:
	jmp	*__esn_wire_process+536(%rip)
	.size	w00033, .-w00033
	.symver	w00033, sched_getscheduler@@GLIBC_2.2.5

	.weak	w00034
	.type	w00034,@function
w00034:
	jmp	*__esn_wire_process+552(%rip)
	.size	w00034, .-w00034
	.symver	w00034, sched_rr_get_interval@@GLIBC_2.2.5

	.globl	w00035
	.type	w00035,@function
w00035:
	jmp	*__esn_wire_process+568(%rip)
	.size	w00035, .-w00035
	.symver	w00035, sched_setaffinity@GLIBC_2.3.3

	.globl	w00036
	.type	w00036,@function
w00036:
	jmp	*__esn_wire_process+584(%rip)
	.size	w00036, .-w00036
	.symver	w00036, sched_setaffinity@@GLIBC_2.3.4

	.weak	w00037
	.type	w00037,@function
w00037:
	jmp	*__esn_wire_process+600(%rip)
	.size	w00037, .-w00037
	.symver	w00037, sched_setparam@@GLIBC_2.2.5

	.weak	w00038
	.type	w00038,@function
w00038:
	jmp	*__esn_wire_process+616(%rip)
	.size	w00038, .-w00038
	.symver	w00038, sched_setscheduler@@GLIBC_2.2.5

	.weak	w00039
	.type	w00039,@function
w00039:
	jmp	*__esn_wire_process+632(%rip)
	.size	w00039, .-w00039
	.symver	w00039, sched_yield@@GLIBC_2.2.5

	.weak	w00040
	.type	w00040,@function
w00040:
	jmp	*__esn_wire_process+648(%rip)
	.size	w00040, .-w00040
	.symver	w00040, setpriority@@GLIBC_2.2.5

	.weak	w00043
	.type	w00043,@function
w00043:
	jmp	*__esn_wire_process+696(%rip)
	.size	w00043, .-w00043
	.symver	w00043, wait@@GLIBC_2.2.5

	.weak	w00044
	.type	w00044,@function
w00044:
	jmp	*__esn_wire_process+712(%rip)
	.size	w00044, .-w00044
	.symver	w00044, wait3@@GLIBC_2.2.5

	.weak	w00045
	.type	w00045,@function
w00045:
	jmp	*__esn_wire_process+728(%rip)
	.size	w00045, .-w00045
	.symver	w00045, wait4@@GLIBC_2.2.5

	.weak	w00046
	.type	w00046,@function
w00046:
	jmp	*__esn_wire_process+744(%rip)
	.size	w00046, .-w00046
	.symver	w00046, waitpid@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
