/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice memory; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_memory[] = {
    { "calloc", 0 },   /* calloc@GLIBC_2.2.5 forward-same */
    { "free", 0 },   /* free@GLIBC_2.2.5 forward-same */
    { "madvise", 0 },   /* madvise@GLIBC_2.2.5 forward-same */
    { "mallinfo", 0 },   /* mallinfo@GLIBC_2.2.5 forward-same */
    { "malloc", 0 },   /* malloc@GLIBC_2.2.5 forward-same */
    { "malloc_stats", 0 },   /* malloc_stats@GLIBC_2.2.5 forward-same */
    { "malloc_trim", 0 },   /* malloc_trim@GLIBC_2.2.5 forward-same */
    { "malloc_usable_size", 0 },   /* malloc_usable_size@GLIBC_2.2.5 forward-same */
    { "mallopt", 0 },   /* mallopt@GLIBC_2.2.5 forward-same */
    { "memalign", 0 },   /* memalign@GLIBC_2.2.5 forward-same */
    { "mlock", 0 },   /* mlock@GLIBC_2.2.5 forward-same */
    { "mmap", 0 },   /* mmap@GLIBC_2.2.5 forward-same */
    { "mmap", 0 },   /* mmap64@GLIBC_2.2.5 forward-alias */
    { "mprotect", 0 },   /* mprotect@GLIBC_2.2.5 forward-same */
    { "msync", 0 },   /* msync@GLIBC_2.2.5 forward-same */
    { "munlock", 0 },   /* munlock@GLIBC_2.2.5 forward-same */
    { "munmap", 0 },   /* munmap@GLIBC_2.2.5 forward-same */
    { "posix_madvise", 0 },   /* posix_madvise@GLIBC_2.2.5 forward-same */
    { "realloc", 0 },   /* realloc@GLIBC_2.2.5 forward-same */
    { "reallocarray", 0 },   /* reallocarray@GLIBC_2.26 forward-same */
    { "valloc", 0 },   /* valloc@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_memory_n = sizeof __esn_wire_memory / sizeof *__esn_wire_memory;

