/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice math; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_math+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, __finite@@GLIBC_2.2.5

	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_math+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, __finitef@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_math+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, __finitel@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_math+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, __isinf@@GLIBC_2.2.5

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_math+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, __isinff@@GLIBC_2.2.5

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_math+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, __isinfl@@GLIBC_2.2.5

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_math+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, __isnan@@GLIBC_2.2.5

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_math+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, __isnanf@@GLIBC_2.2.5

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_math+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, __isnanl@@GLIBC_2.2.5

	.globl	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_math+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, __signbitf@@GLIBC_2.2.5

	.weak	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_math+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, copysign@@GLIBC_2.2.5

	.weak	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_math+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, copysignf@@GLIBC_2.2.5

	.weak	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_math+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, copysignl@@GLIBC_2.2.5

	.weak	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_math+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, finite@@GLIBC_2.2.5

	.weak	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_math+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, finitef@@GLIBC_2.2.5

	.weak	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_math+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, finitel@@GLIBC_2.2.5

	.weak	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_math+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, frexp@@GLIBC_2.2.5

	.weak	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_math+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, frexpf@@GLIBC_2.2.5

	.weak	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_math+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, frexpl@@GLIBC_2.2.5

	.weak	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_math+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, isinf@@GLIBC_2.2.5

	.weak	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_math+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, isinff@@GLIBC_2.2.5

	.weak	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_math+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, isinfl@@GLIBC_2.2.5

	.weak	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_math+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, isnan@@GLIBC_2.2.5

	.weak	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_math+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, isnanf@@GLIBC_2.2.5

	.weak	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_math+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, isnanl@@GLIBC_2.2.5

	.weak	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_math+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, ldexp@@GLIBC_2.2.5

	.weak	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_math+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, ldexpf@@GLIBC_2.2.5

	.weak	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_math+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, ldexpl@@GLIBC_2.2.5

	.weak	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_math+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, modf@@GLIBC_2.2.5

	.weak	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_math+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, modff@@GLIBC_2.2.5

	.weak	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_math+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, modfl@@GLIBC_2.2.5

	.weak	w00031
	.type	w00031,@function
w00031:
	jmp	*__esn_wire_math+504(%rip)
	.size	w00031, .-w00031
	.symver	w00031, scalbn@@GLIBC_2.2.5

	.weak	w00032
	.type	w00032,@function
w00032:
	jmp	*__esn_wire_math+520(%rip)
	.size	w00032, .-w00032
	.symver	w00032, scalbnf@@GLIBC_2.2.5

	.weak	w00033
	.type	w00033,@function
w00033:
	jmp	*__esn_wire_math+536(%rip)
	.size	w00033, .-w00033
	.symver	w00033, scalbnl@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
