/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice signal; do not edit */
	.text
	.weak	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_signal+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, kill@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_signal+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, killpg@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_signal+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, psiginfo@@GLIBC_2.10

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_signal+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, psignal@@GLIBC_2.2.5

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_signal+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, raise@@GLIBC_2.2.5

	.globl	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_signal+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, sighold@@GLIBC_2.2.5

	.globl	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_signal+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, sigignore@@GLIBC_2.2.5

	.globl	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_signal+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, siginterrupt@@GLIBC_2.2.5

	.weak	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_signal+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, sigpause@@GLIBC_2.2.5

	.globl	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_signal+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, sigrelse@@GLIBC_2.2.5

	.globl	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_signal+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, sigset@@GLIBC_2.2.5

	.weak	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_signal+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, sigwait@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
