/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice math; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_math[] = {
    { "finite", 0 },   /* __finite@GLIBC_2.2.5 forward-alias */
    { "finitef", 0 },   /* __finitef@GLIBC_2.2.5 forward-alias */
    { "finitel", 0 },   /* __finitel@GLIBC_2.2.5 forward-alias */
    { "isinf", 0 },   /* __isinf@GLIBC_2.2.5 forward-alias */
    { "__isinff", 0 },   /* __isinff@GLIBC_2.2.5 forward-same */
    { "isinfl", 0 },   /* __isinfl@GLIBC_2.2.5 forward-alias */
    { "isnan", 0 },   /* __isnan@GLIBC_2.2.5 forward-alias */
    { "__isnanf", 0 },   /* __isnanf@GLIBC_2.2.5 forward-same */
    { "isnanl", 0 },   /* __isnanl@GLIBC_2.2.5 forward-alias */
    { "__signbitf", 0 },   /* __signbitf@GLIBC_2.2.5 forward-same */
    { "copysign", 0 },   /* copysign@GLIBC_2.2.5 forward-same */
    { "copysignf", 0 },   /* copysignf@GLIBC_2.2.5 forward-same */
    { "copysignl", 0 },   /* copysignl@GLIBC_2.2.5 forward-same */
    { "finite", 0 },   /* finite@GLIBC_2.2.5 forward-same */
    { "finitef", 0 },   /* finitef@GLIBC_2.2.5 forward-same */
    { "finitel", 0 },   /* finitel@GLIBC_2.2.5 forward-same */
    { "frexp", 0 },   /* frexp@GLIBC_2.2.5 forward-same */
    { "frexpf", 0 },   /* frexpf@GLIBC_2.2.5 forward-same */
    { "frexpl", 0 },   /* frexpl@GLIBC_2.2.5 forward-same */
    { "isinf", 0 },   /* isinf@GLIBC_2.2.5 forward-same */
    { "isinff", 0 },   /* isinff@GLIBC_2.2.5 forward-same */
    { "isinfl", 0 },   /* isinfl@GLIBC_2.2.5 forward-same */
    { "isnan", 0 },   /* isnan@GLIBC_2.2.5 forward-same */
    { "isnanf", 0 },   /* isnanf@GLIBC_2.2.5 forward-same */
    { "isnanl", 0 },   /* isnanl@GLIBC_2.2.5 forward-same */
    { "ldexp", 0 },   /* ldexp@GLIBC_2.2.5 forward-same */
    { "ldexpf", 0 },   /* ldexpf@GLIBC_2.2.5 forward-same */
    { "ldexpl", 0 },   /* ldexpl@GLIBC_2.2.5 forward-same */
    { "modf", 0 },   /* modf@GLIBC_2.2.5 forward-same */
    { "modff", 0 },   /* modff@GLIBC_2.2.5 forward-same */
    { "modfl", 0 },   /* modfl@GLIBC_2.2.5 forward-same */
    { "scalbn", 0 },   /* scalbn@GLIBC_2.2.5 forward-same */
    { "scalbnf", 0 },   /* scalbnf@GLIBC_2.2.5 forward-same */
    { "scalbnl", 0 },   /* scalbnl@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_math_n = sizeof __esn_wire_math / sizeof *__esn_wire_math;

