/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice signal; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_signal[] = {
    { "__sysv_signal", 0 },   /* __sysv_signal@GLIBC_2.2.5 shim */
    { "kill", 0 },   /* kill@GLIBC_2.2.5 forward-same */
    { "killpg", 0 },   /* killpg@GLIBC_2.2.5 forward-same */
    { "psiginfo", 0 },   /* psiginfo@GLIBC_2.10 forward-same */
    { "psignal", 0 },   /* psignal@GLIBC_2.2.5 forward-same */
    { "raise", 0 },   /* raise@GLIBC_2.2.5 forward-same */
    { "sigaction", 0 },   /* sigaction@GLIBC_2.2.5 shim */
    { "sigaddset", 0 },   /* sigaddset@GLIBC_2.2.5 shim */
    { "sigaltstack", 0 },   /* sigaltstack@GLIBC_2.2.5 shim */
    { "sigdelset", 0 },   /* sigdelset@GLIBC_2.2.5 shim */
    { "sigemptyset", 0 },   /* sigemptyset@GLIBC_2.2.5 shim */
    { "sigfillset", 0 },   /* sigfillset@GLIBC_2.2.5 shim */
    { "sighold", 0 },   /* sighold@GLIBC_2.2.5 forward-same */
    { "sigignore", 0 },   /* sigignore@GLIBC_2.2.5 forward-same */
    { "siginterrupt", 0 },   /* siginterrupt@GLIBC_2.2.5 forward-same */
    { "sigismember", 0 },   /* sigismember@GLIBC_2.2.5 shim */
    { "signal", 0 },   /* signal@GLIBC_2.2.5 shim */
    { "sigpause", 0 },   /* sigpause@GLIBC_2.2.5 forward-same */
    { "sigpending", 0 },   /* sigpending@GLIBC_2.2.5 shim */
    { "sigprocmask", 0 },   /* sigprocmask@GLIBC_2.2.5 shim */
    { "sigqueue", 0 },   /* sigqueue@GLIBC_2.2.5 shim */
    { "sigrelse", 0 },   /* sigrelse@GLIBC_2.2.5 forward-same */
    { "sigset", 0 },   /* sigset@GLIBC_2.2.5 forward-same */
    { "sigsuspend", 0 },   /* sigsuspend@GLIBC_2.2.5 shim */
    { "sigtimedwait", 0 },   /* sigtimedwait@GLIBC_2.2.5 shim */
    { "sigwait", 0 },   /* sigwait@GLIBC_2.2.5 forward-same */
    { "sigwaitinfo", 0 },   /* sigwaitinfo@GLIBC_2.2.5 shim */
    { "sysv_signal", 0 },   /* sysv_signal@GLIBC_2.2.5 shim */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_signal_n = sizeof __esn_wire_signal / sizeof *__esn_wire_signal;

