/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice regex; do not edit */
	.text
	.weak	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_regex+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, regcomp@@GLIBC_2.2.5

	.weak	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_regex+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, regerror@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_regex+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, regexec@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_regex+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, regexec@@GLIBC_2.3.4

	.weak	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_regex+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, regfree@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
