/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice threads; do not edit */
	.text
	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_threads+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, pthread_attr_destroy@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_threads+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, pthread_attr_getdetachstate@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_threads+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, pthread_attr_getinheritsched@@GLIBC_2.2.5

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_threads+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, pthread_attr_getschedparam@@GLIBC_2.2.5

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_threads+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, pthread_attr_getschedpolicy@@GLIBC_2.2.5

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_threads+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, pthread_attr_getscope@@GLIBC_2.2.5

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_threads+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, pthread_attr_init@@GLIBC_2.2.5

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_threads+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, pthread_attr_setdetachstate@@GLIBC_2.2.5

	.globl	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_threads+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, pthread_attr_setinheritsched@@GLIBC_2.2.5

	.globl	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_threads+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, pthread_attr_setschedparam@@GLIBC_2.2.5

	.globl	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_threads+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, pthread_attr_setschedpolicy@@GLIBC_2.2.5

	.globl	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_threads+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, pthread_attr_setscope@@GLIBC_2.2.5

	.globl	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_threads+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, pthread_cond_broadcast@GLIBC_2.2.5

	.globl	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_threads+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, pthread_cond_broadcast@@GLIBC_2.3.2

	.globl	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_threads+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, pthread_cond_destroy@GLIBC_2.2.5

	.globl	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_threads+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, pthread_cond_destroy@@GLIBC_2.3.2

	.globl	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_threads+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, pthread_cond_init@GLIBC_2.2.5

	.globl	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_threads+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, pthread_cond_init@@GLIBC_2.3.2

	.globl	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_threads+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, pthread_cond_signal@GLIBC_2.2.5

	.globl	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_threads+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, pthread_cond_signal@@GLIBC_2.3.2

	.globl	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_threads+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, pthread_cond_timedwait@GLIBC_2.2.5

	.globl	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_threads+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, pthread_cond_timedwait@@GLIBC_2.3.2

	.globl	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_threads+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, pthread_cond_wait@GLIBC_2.2.5

	.globl	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_threads+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, pthread_cond_wait@@GLIBC_2.3.2

	.globl	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_threads+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, pthread_condattr_destroy@@GLIBC_2.2.5

	.globl	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_threads+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, pthread_condattr_init@@GLIBC_2.2.5

	.globl	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_threads+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, pthread_equal@@GLIBC_2.2.5

	.globl	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_threads+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, pthread_exit@@GLIBC_2.2.5

	.globl	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_threads+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, pthread_getschedparam@@GLIBC_2.2.5

	.globl	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_threads+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, pthread_mutex_destroy@@GLIBC_2.2.5

	.globl	w00031
	.type	w00031,@function
w00031:
	jmp	*__esn_wire_threads+504(%rip)
	.size	w00031, .-w00031
	.symver	w00031, pthread_mutex_init@@GLIBC_2.2.5

	.globl	w00032
	.type	w00032,@function
w00032:
	jmp	*__esn_wire_threads+520(%rip)
	.size	w00032, .-w00032
	.symver	w00032, pthread_mutex_lock@@GLIBC_2.2.5

	.globl	w00033
	.type	w00033,@function
w00033:
	jmp	*__esn_wire_threads+536(%rip)
	.size	w00033, .-w00033
	.symver	w00033, pthread_mutex_unlock@@GLIBC_2.2.5

	.globl	w00034
	.type	w00034,@function
w00034:
	jmp	*__esn_wire_threads+552(%rip)
	.size	w00034, .-w00034
	.symver	w00034, pthread_self@@GLIBC_2.2.5

	.globl	w00035
	.type	w00035,@function
w00035:
	jmp	*__esn_wire_threads+568(%rip)
	.size	w00035, .-w00035
	.symver	w00035, pthread_setcancelstate@@GLIBC_2.2.5

	.globl	w00036
	.type	w00036,@function
w00036:
	jmp	*__esn_wire_threads+584(%rip)
	.size	w00036, .-w00036
	.symver	w00036, pthread_setcanceltype@@GLIBC_2.2.5

	.globl	w00037
	.type	w00037,@function
w00037:
	jmp	*__esn_wire_threads+600(%rip)
	.size	w00037, .-w00037
	.symver	w00037, pthread_setschedparam@@GLIBC_2.2.5

	.globl	w00038
	.type	w00038,@function
w00038:
	jmp	*__esn_wire_threads+616(%rip)
	.size	w00038, .-w00038
	.symver	w00038, thrd_current@@GLIBC_2.28

	.globl	w00039
	.type	w00039,@function
w00039:
	jmp	*__esn_wire_threads+632(%rip)
	.size	w00039, .-w00039
	.symver	w00039, thrd_equal@@GLIBC_2.28

	.globl	w00040
	.type	w00040,@function
w00040:
	jmp	*__esn_wire_threads+648(%rip)
	.size	w00040, .-w00040
	.symver	w00040, thrd_sleep@@GLIBC_2.28

	.globl	w00041
	.type	w00041,@function
w00041:
	jmp	*__esn_wire_threads+664(%rip)
	.size	w00041, .-w00041
	.symver	w00041, thrd_yield@@GLIBC_2.28

	.section	.note.GNU-stack,"",@progbits
