/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice sysv-ipc; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_sysv_ipc+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, __getpagesize@@GLIBC_2.2.5

	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_sysv_ipc+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, ftok@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_sysv_ipc+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, msgctl@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_sysv_ipc+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, msgget@@GLIBC_2.2.5

	.weak	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_sysv_ipc+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, msgrcv@@GLIBC_2.2.5

	.weak	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_sysv_ipc+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, msgsnd@@GLIBC_2.2.5

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_sysv_ipc+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, semctl@@GLIBC_2.2.5

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_sysv_ipc+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, semget@@GLIBC_2.2.5

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_sysv_ipc+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, semop@@GLIBC_2.2.5

	.globl	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_sysv_ipc+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, shmat@@GLIBC_2.2.5

	.globl	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_sysv_ipc+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, shmctl@@GLIBC_2.2.5

	.globl	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_sysv_ipc+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, shmdt@@GLIBC_2.2.5

	.globl	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_sysv_ipc+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, shmget@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
