/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice io-mux; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_io_mux[] = {
    { "poll", 0 },   /* poll@GLIBC_2.2.5 forward-same */
    { "ppoll", 0 },   /* ppoll@GLIBC_2.4 forward-same */
    { "pselect", 0 },   /* pselect@GLIBC_2.2.5 forward-same */
    { "select", 0 },   /* select@GLIBC_2.2.5 forward-same */
    { "signalfd", 0 },   /* signalfd@GLIBC_2.7 forward-same */
    { "timerfd_create", 0 },   /* timerfd_create@GLIBC_2.8 forward-same */
    { "timerfd_gettime", 0 },   /* timerfd_gettime@GLIBC_2.8 forward-same */
    { "timerfd_settime", 0 },   /* timerfd_settime@GLIBC_2.8 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_io_mux_n = sizeof __esn_wire_io_mux / sizeof *__esn_wire_io_mux;

