/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice identity; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_identity+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, endgrent@@GLIBC_2.2.5

	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_identity+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, endpwent@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_identity+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, getgrent@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_identity+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, getgrgid@@GLIBC_2.2.5

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_identity+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, getgrgid_r@@GLIBC_2.2.5

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_identity+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, getgrnam@@GLIBC_2.2.5

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_identity+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, getgrnam_r@@GLIBC_2.2.5

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_identity+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, getgrouplist@@GLIBC_2.2.5

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_identity+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, getpwent@@GLIBC_2.2.5

	.globl	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_identity+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, getpwnam@@GLIBC_2.2.5

	.globl	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_identity+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, getpwnam_r@@GLIBC_2.2.5

	.globl	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_identity+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, getpwuid@@GLIBC_2.2.5

	.globl	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_identity+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, getpwuid_r@@GLIBC_2.2.5

	.globl	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_identity+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, initgroups@@GLIBC_2.2.5

	.globl	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_identity+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, setgrent@@GLIBC_2.2.5

	.globl	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_identity+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, setgroups@@GLIBC_2.2.5

	.globl	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_identity+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, setpwent@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
