/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice identity; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_identity[] = {
    { "endgrent", 0 },   /* endgrent@GLIBC_2.2.5 forward-same */
    { "endpwent", 0 },   /* endpwent@GLIBC_2.2.5 forward-same */
    { "getgrent", 0 },   /* getgrent@GLIBC_2.2.5 forward-same */
    { "getgrgid", 0 },   /* getgrgid@GLIBC_2.2.5 forward-same */
    { "getgrgid_r", 0 },   /* getgrgid_r@GLIBC_2.2.5 forward-same */
    { "getgrnam", 0 },   /* getgrnam@GLIBC_2.2.5 forward-same */
    { "getgrnam_r", 0 },   /* getgrnam_r@GLIBC_2.2.5 forward-same */
    { "getgrouplist", 0 },   /* getgrouplist@GLIBC_2.2.5 forward-same */
    { "getpwent", 0 },   /* getpwent@GLIBC_2.2.5 forward-same */
    { "getpwnam", 0 },   /* getpwnam@GLIBC_2.2.5 forward-same */
    { "getpwnam_r", 0 },   /* getpwnam_r@GLIBC_2.2.5 forward-same */
    { "getpwuid", 0 },   /* getpwuid@GLIBC_2.2.5 forward-same */
    { "getpwuid_r", 0 },   /* getpwuid_r@GLIBC_2.2.5 forward-same */
    { "initgroups", 0 },   /* initgroups@GLIBC_2.2.5 forward-same */
    { "setgrent", 0 },   /* setgrent@GLIBC_2.2.5 forward-same */
    { "setgroups", 0 },   /* setgroups@GLIBC_2.2.5 forward-same */
    { "setpwent", 0 },   /* setpwent@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_identity_n = sizeof __esn_wire_identity / sizeof *__esn_wire_identity;

