/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice runtime; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_runtime[] = {
    { "__assert", 0 },   /* __assert@GLIBC_2.2.5 forward-same */
    { "_longjmp", 0 },   /* _longjmp@GLIBC_2.2.5 shim */
    { "_setjmp", 0 },   /* _setjmp@GLIBC_2.2.5 shim */
    { "getcontext", 0 },   /* getcontext@GLIBC_2.2.5 forward-same */
    { "longjmp", 0 },   /* longjmp@GLIBC_2.2.5 shim */
    { "makecontext", 0 },   /* makecontext@GLIBC_2.2.5 forward-same */
    { "setcontext", 0 },   /* setcontext@GLIBC_2.2.5 forward-same */
    { "setjmp", 0 },   /* setjmp@GLIBC_2.2.5 shim */
    { "siglongjmp", 0 },   /* siglongjmp@GLIBC_2.2.5 shim */
    { "swapcontext", 0 },   /* swapcontext@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_runtime_n = sizeof __esn_wire_runtime / sizeof *__esn_wire_runtime;

