/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice string; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_string+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, __argz_count@@GLIBC_2.2.5

	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_string+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, __argz_next@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_string+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, __argz_stringify@@GLIBC_2.2.5

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_string+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, __strtok_r@@GLIBC_2.2.5

	.weak	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_string+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, argz_add@@GLIBC_2.2.5

	.weak	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_string+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, argz_add_sep@@GLIBC_2.2.5

	.weak	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_string+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, argz_append@@GLIBC_2.2.5

	.weak	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_string+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, argz_count@@GLIBC_2.2.5

	.weak	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_string+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, argz_create@@GLIBC_2.2.5

	.weak	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_string+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, argz_create_sep@@GLIBC_2.2.5

	.globl	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_string+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, argz_delete@@GLIBC_2.2.5

	.weak	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_string+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, argz_extract@@GLIBC_2.2.5

	.weak	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_string+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, argz_insert@@GLIBC_2.2.5

	.weak	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_string+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, argz_next@@GLIBC_2.2.5

	.weak	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_string+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, argz_replace@@GLIBC_2.2.5

	.weak	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_string+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, argz_stringify@@GLIBC_2.2.5

	.weak	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_string+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, basename@@GLIBC_2.2.5

	.globl	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_string+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, bcopy@@GLIBC_2.2.5

	.globl	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_string+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, envz_add@@GLIBC_2.2.5

	.globl	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_string+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, envz_entry@@GLIBC_2.2.5

	.globl	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_string+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, envz_get@@GLIBC_2.2.5

	.globl	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_string+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, envz_merge@@GLIBC_2.2.5

	.globl	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_string+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, envz_remove@@GLIBC_2.2.5

	.globl	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_string+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, envz_strip@@GLIBC_2.2.5

	.globl	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_string+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, explicit_bzero@@GLIBC_2.25

	.globl	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_string+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, ffs@@GLIBC_2.2.5

	.weak	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_string+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, ffsl@@GLIBC_2.2.5

	.globl	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_string+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, ffsll@@GLIBC_2.2.5

	.weak	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_string+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, memccpy@@GLIBC_2.2.5

	.globl	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_string+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, memcpy@GLIBC_2.2.5

	.weak	w00031
	.type	w00031,@function
w00031:
	jmp	*__esn_wire_string+504(%rip)
	.size	w00031, .-w00031
	.symver	w00031, memmem@@GLIBC_2.2.5

	.weak	w00032
	.type	w00032,@function
w00032:
	jmp	*__esn_wire_string+520(%rip)
	.size	w00032, .-w00032
	.symver	w00032, strcasestr@@GLIBC_2.2.5

	.globl	w00033
	.type	w00033,@function
w00033:
	jmp	*__esn_wire_string+536(%rip)
	.size	w00033, .-w00033
	.symver	w00033, strcoll@@GLIBC_2.2.5

	.weak	w00034
	.type	w00034,@function
w00034:
	jmp	*__esn_wire_string+552(%rip)
	.size	w00034, .-w00034
	.symver	w00034, strcoll_l@@GLIBC_2.3

	.weak	w00035
	.type	w00035,@function
w00035:
	jmp	*__esn_wire_string+568(%rip)
	.size	w00035, .-w00035
	.symver	w00035, strdup@@GLIBC_2.2.5

	.globl	w00036
	.type	w00036,@function
w00036:
	jmp	*__esn_wire_string+584(%rip)
	.size	w00036, .-w00036
	.symver	w00036, strerror@@GLIBC_2.2.5

	.weak	w00037
	.type	w00037,@function
w00037:
	jmp	*__esn_wire_string+600(%rip)
	.size	w00037, .-w00037
	.symver	w00037, strerror_l@@GLIBC_2.6

	.weak	w00038
	.type	w00038,@function
w00038:
	jmp	*__esn_wire_string+616(%rip)
	.size	w00038, .-w00038
	.symver	w00038, strerror_r@@GLIBC_2.2.5

	.weak	w00039
	.type	w00039,@function
w00039:
	jmp	*__esn_wire_string+632(%rip)
	.size	w00039, .-w00039
	.symver	w00039, strndup@@GLIBC_2.2.5

	.weak	w00040
	.type	w00040,@function
w00040:
	jmp	*__esn_wire_string+648(%rip)
	.size	w00040, .-w00040
	.symver	w00040, strsep@@GLIBC_2.2.5

	.globl	w00041
	.type	w00041,@function
w00041:
	jmp	*__esn_wire_string+664(%rip)
	.size	w00041, .-w00041
	.symver	w00041, strsignal@@GLIBC_2.2.5

	.globl	w00042
	.type	w00042,@function
w00042:
	jmp	*__esn_wire_string+680(%rip)
	.size	w00042, .-w00042
	.symver	w00042, strtok@@GLIBC_2.2.5

	.weak	w00043
	.type	w00043,@function
w00043:
	jmp	*__esn_wire_string+696(%rip)
	.size	w00043, .-w00043
	.symver	w00043, strtok_r@@GLIBC_2.2.5

	.weak	w00044
	.type	w00044,@function
w00044:
	jmp	*__esn_wire_string+712(%rip)
	.size	w00044, .-w00044
	.symver	w00044, strverscmp@@GLIBC_2.2.5

	.globl	w00045
	.type	w00045,@function
w00045:
	jmp	*__esn_wire_string+728(%rip)
	.size	w00045, .-w00045
	.symver	w00045, strxfrm@@GLIBC_2.2.5

	.weak	w00046
	.type	w00046,@function
w00046:
	jmp	*__esn_wire_string+744(%rip)
	.size	w00046, .-w00046
	.symver	w00046, strxfrm_l@@GLIBC_2.3

	.section	.note.GNU-stack,"",@progbits
