/* generated by gen-wire.py from fwd-sockets.tsv + symbol-slice.tsv, slice sockets; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_sockets+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, accept@@GLIBC_2.2.5

	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_sockets+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, accept4@@GLIBC_2.10

	.weak	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_sockets+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, bind@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_sockets+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, bindresvport@@GLIBC_2.2.5

	.weak	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_sockets+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, connect@@GLIBC_2.2.5

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_sockets+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, endhostent@@GLIBC_2.2.5

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_sockets+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, endprotoent@@GLIBC_2.2.5

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_sockets+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, endservent@@GLIBC_2.2.5

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_sockets+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, freeaddrinfo@@GLIBC_2.2.5

	.weak	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_sockets+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, freeifaddrs@@GLIBC_2.3

	.globl	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_sockets+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, gai_strerror@@GLIBC_2.2.5

	.globl	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_sockets+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, getaddrinfo@@GLIBC_2.2.5

	.globl	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_sockets+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, gethostbyaddr@@GLIBC_2.2.5

	.globl	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_sockets+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, gethostbyname@@GLIBC_2.2.5

	.globl	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_sockets+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, gethostbyname2@@GLIBC_2.2.5

	.weak	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_sockets+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, getifaddrs@@GLIBC_2.3

	.globl	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_sockets+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, getnameinfo@@GLIBC_2.2.5

	.weak	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_sockets+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, getpeername@@GLIBC_2.2.5

	.globl	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_sockets+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, getprotobyname@@GLIBC_2.2.5

	.globl	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_sockets+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, getprotobynumber@@GLIBC_2.2.5

	.globl	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_sockets+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, getprotoent@@GLIBC_2.2.5

	.globl	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_sockets+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, getservbyname@@GLIBC_2.2.5

	.globl	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_sockets+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, getservbyport@@GLIBC_2.2.5

	.globl	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_sockets+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, getservent@@GLIBC_2.2.5

	.weak	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_sockets+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, getsockname@@GLIBC_2.2.5

	.weak	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_sockets+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, getsockopt@@GLIBC_2.2.5

	.globl	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_sockets+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, herror@@GLIBC_2.2.5

	.globl	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_sockets+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, hstrerror@@GLIBC_2.2.5

	.globl	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_sockets+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, htonl@@GLIBC_2.2.5

	.globl	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_sockets+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, htons@@GLIBC_2.2.5

	.weak	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_sockets+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, if_freenameindex@@GLIBC_2.2.5

	.weak	w00031
	.type	w00031,@function
w00031:
	jmp	*__esn_wire_sockets+504(%rip)
	.size	w00031, .-w00031
	.symver	w00031, if_indextoname@@GLIBC_2.2.5

	.weak	w00032
	.type	w00032,@function
w00032:
	jmp	*__esn_wire_sockets+520(%rip)
	.size	w00032, .-w00032
	.symver	w00032, if_nameindex@@GLIBC_2.2.5

	.weak	w00033
	.type	w00033,@function
w00033:
	jmp	*__esn_wire_sockets+536(%rip)
	.size	w00033, .-w00033
	.symver	w00033, if_nametoindex@@GLIBC_2.2.5

	.weak	w00034
	.type	w00034,@function
w00034:
	jmp	*__esn_wire_sockets+552(%rip)
	.size	w00034, .-w00034
	.symver	w00034, inet_addr@@GLIBC_2.2.5

	.weak	w00035
	.type	w00035,@function
w00035:
	jmp	*__esn_wire_sockets+568(%rip)
	.size	w00035, .-w00035
	.symver	w00035, inet_aton@@GLIBC_2.2.5

	.weak	w00036
	.type	w00036,@function
w00036:
	jmp	*__esn_wire_sockets+584(%rip)
	.size	w00036, .-w00036
	.symver	w00036, inet_makeaddr@@GLIBC_2.2.5

	.globl	w00037
	.type	w00037,@function
w00037:
	jmp	*__esn_wire_sockets+600(%rip)
	.size	w00037, .-w00037
	.symver	w00037, inet_netof@@GLIBC_2.2.5

	.globl	w00038
	.type	w00038,@function
w00038:
	jmp	*__esn_wire_sockets+616(%rip)
	.size	w00038, .-w00038
	.symver	w00038, inet_network@@GLIBC_2.2.5

	.globl	w00039
	.type	w00039,@function
w00039:
	jmp	*__esn_wire_sockets+632(%rip)
	.size	w00039, .-w00039
	.symver	w00039, inet_ntoa@@GLIBC_2.2.5

	.globl	w00040
	.type	w00040,@function
w00040:
	jmp	*__esn_wire_sockets+648(%rip)
	.size	w00040, .-w00040
	.symver	w00040, inet_ntop@@GLIBC_2.2.5

	.weak	w00041
	.type	w00041,@function
w00041:
	jmp	*__esn_wire_sockets+664(%rip)
	.size	w00041, .-w00041
	.symver	w00041, inet_pton@@GLIBC_2.2.5

	.globl	w00042
	.type	w00042,@function
w00042:
	jmp	*__esn_wire_sockets+680(%rip)
	.size	w00042, .-w00042
	.symver	w00042, iruserok@@GLIBC_2.2.5

	.weak	w00043
	.type	w00043,@function
w00043:
	jmp	*__esn_wire_sockets+696(%rip)
	.size	w00043, .-w00043
	.symver	w00043, listen@@GLIBC_2.2.5

	.weak	w00044
	.type	w00044,@function
w00044:
	jmp	*__esn_wire_sockets+712(%rip)
	.size	w00044, .-w00044
	.symver	w00044, ntohl@@GLIBC_2.2.5

	.weak	w00045
	.type	w00045,@function
w00045:
	jmp	*__esn_wire_sockets+728(%rip)
	.size	w00045, .-w00045
	.symver	w00045, ntohs@@GLIBC_2.2.5

	.globl	w00046
	.type	w00046,@function
w00046:
	jmp	*__esn_wire_sockets+744(%rip)
	.size	w00046, .-w00046
	.symver	w00046, rcmd@@GLIBC_2.2.5

	.globl	w00047
	.type	w00047,@function
w00047:
	jmp	*__esn_wire_sockets+760(%rip)
	.size	w00047, .-w00047
	.symver	w00047, rcmd_af@@GLIBC_2.2.5

	.weak	w00048
	.type	w00048,@function
w00048:
	jmp	*__esn_wire_sockets+776(%rip)
	.size	w00048, .-w00048
	.symver	w00048, recv@@GLIBC_2.2.5

	.weak	w00049
	.type	w00049,@function
w00049:
	jmp	*__esn_wire_sockets+792(%rip)
	.size	w00049, .-w00049
	.symver	w00049, recvfrom@@GLIBC_2.2.5

	.weak	w00050
	.type	w00050,@function
w00050:
	jmp	*__esn_wire_sockets+808(%rip)
	.size	w00050, .-w00050
	.symver	w00050, recvmsg@@GLIBC_2.2.5

	.globl	w00051
	.type	w00051,@function
w00051:
	jmp	*__esn_wire_sockets+824(%rip)
	.size	w00051, .-w00051
	.symver	w00051, rexec@@GLIBC_2.2.5

	.globl	w00052
	.type	w00052,@function
w00052:
	jmp	*__esn_wire_sockets+840(%rip)
	.size	w00052, .-w00052
	.symver	w00052, rresvport@@GLIBC_2.2.5

	.globl	w00053
	.type	w00053,@function
w00053:
	jmp	*__esn_wire_sockets+856(%rip)
	.size	w00053, .-w00053
	.symver	w00053, rresvport_af@@GLIBC_2.2.5

	.globl	w00054
	.type	w00054,@function
w00054:
	jmp	*__esn_wire_sockets+872(%rip)
	.size	w00054, .-w00054
	.symver	w00054, ruserok@@GLIBC_2.2.5

	.weak	w00055
	.type	w00055,@function
w00055:
	jmp	*__esn_wire_sockets+888(%rip)
	.size	w00055, .-w00055
	.symver	w00055, send@@GLIBC_2.2.5

	.weak	w00056
	.type	w00056,@function
w00056:
	jmp	*__esn_wire_sockets+904(%rip)
	.size	w00056, .-w00056
	.symver	w00056, sendmsg@@GLIBC_2.2.5

	.weak	w00057
	.type	w00057,@function
w00057:
	jmp	*__esn_wire_sockets+920(%rip)
	.size	w00057, .-w00057
	.symver	w00057, sendto@@GLIBC_2.2.5

	.globl	w00058
	.type	w00058,@function
w00058:
	jmp	*__esn_wire_sockets+936(%rip)
	.size	w00058, .-w00058
	.symver	w00058, sethostent@@GLIBC_2.2.5

	.globl	w00059
	.type	w00059,@function
w00059:
	jmp	*__esn_wire_sockets+952(%rip)
	.size	w00059, .-w00059
	.symver	w00059, setprotoent@@GLIBC_2.2.5

	.globl	w00060
	.type	w00060,@function
w00060:
	jmp	*__esn_wire_sockets+968(%rip)
	.size	w00060, .-w00060
	.symver	w00060, setservent@@GLIBC_2.2.5

	.weak	w00061
	.type	w00061,@function
w00061:
	jmp	*__esn_wire_sockets+984(%rip)
	.size	w00061, .-w00061
	.symver	w00061, setsockopt@@GLIBC_2.2.5

	.weak	w00062
	.type	w00062,@function
w00062:
	jmp	*__esn_wire_sockets+1000(%rip)
	.size	w00062, .-w00062
	.symver	w00062, shutdown@@GLIBC_2.2.5

	.globl	w00063
	.type	w00063,@function
w00063:
	jmp	*__esn_wire_sockets+1016(%rip)
	.size	w00063, .-w00063
	.symver	w00063, sockatmark@@GLIBC_2.2.5

	.weak	w00064
	.type	w00064,@function
w00064:
	jmp	*__esn_wire_sockets+1032(%rip)
	.size	w00064, .-w00064
	.symver	w00064, socket@@GLIBC_2.2.5

	.weak	w00065
	.type	w00065,@function
w00065:
	jmp	*__esn_wire_sockets+1048(%rip)
	.size	w00065, .-w00065
	.symver	w00065, socketpair@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
