/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice time; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_time[] = {
    { "asctime", 0 },   /* asctime@GLIBC_2.2.5 forward-same */
    { "asctime_r", 0 },   /* asctime_r@GLIBC_2.2.5 forward-same */
    { "clock", 0 },   /* clock@GLIBC_2.2.5 forward-same */
    { "clock_getcpuclockid", 0 },   /* clock_getcpuclockid@GLIBC_2.17 forward-same */
    { "clock_getcpuclockid", 0 },   /* clock_getcpuclockid@GLIBC_2.2.5 forward-same */
    { "clock_getres", 0 },   /* clock_getres@GLIBC_2.17 forward-same */
    { "clock_getres", 0 },   /* clock_getres@GLIBC_2.2.5 forward-same */
    { "clock_gettime", 0 },   /* clock_gettime@GLIBC_2.17 forward-same */
    { "clock_gettime", 0 },   /* clock_gettime@GLIBC_2.2.5 forward-same */
    { "clock_nanosleep", 0 },   /* clock_nanosleep@GLIBC_2.17 forward-same */
    { "clock_nanosleep", 0 },   /* clock_nanosleep@GLIBC_2.2.5 forward-same */
    { "clock_settime", 0 },   /* clock_settime@GLIBC_2.17 forward-same */
    { "clock_settime", 0 },   /* clock_settime@GLIBC_2.2.5 forward-same */
    { "ctime", 0 },   /* ctime@GLIBC_2.2.5 forward-same */
    { "ctime_r", 0 },   /* ctime_r@GLIBC_2.2.5 forward-same */
    { "difftime", 0 },   /* difftime@GLIBC_2.2.5 forward-same */
    { "ftime", 0 },   /* ftime@GLIBC_2.2.5 forward-same */
    { "futimes", 0 },   /* futimes@GLIBC_2.3 forward-same */
    { "futimesat", 0 },   /* futimesat@GLIBC_2.4 forward-same */
    { "getitimer", 0 },   /* getitimer@GLIBC_2.2.5 forward-same */
    { "gmtime", 0 },   /* gmtime@GLIBC_2.2.5 forward-same */
    { "gmtime_r", 0 },   /* gmtime_r@GLIBC_2.2.5 forward-same */
    { "localtime", 0 },   /* localtime@GLIBC_2.2.5 forward-same */
    { "localtime_r", 0 },   /* localtime_r@GLIBC_2.2.5 forward-same */
    { "lutimes", 0 },   /* lutimes@GLIBC_2.3 forward-same */
    { "mktime", 0 },   /* mktime@GLIBC_2.2.5 forward-same */
    { "nanosleep", 0 },   /* nanosleep@GLIBC_2.2.5 forward-same */
    { "setitimer", 0 },   /* setitimer@GLIBC_2.2.5 forward-same */
    { "settimeofday", 0 },   /* settimeofday@GLIBC_2.2.5 forward-same */
    { "stime", 0 },   /* stime@GLIBC_2.2.5 forward-same */
    { "strftime", 0 },   /* strftime@GLIBC_2.2.5 forward-same */
    { "strftime_l", 0 },   /* strftime_l@GLIBC_2.3 forward-same */
    { "strptime", 0 },   /* strptime@GLIBC_2.2.5 forward-same */
    { "strptime_l", 0 },   /* strptime_l@GLIBC_2.3.2 forward-same */
    { "timegm", 0 },   /* timegm@GLIBC_2.2.5 forward-same */
    { "timelocal", 0 },   /* timelocal@GLIBC_2.2.5 forward-same */
    { "times", 0 },   /* times@GLIBC_2.2.5 forward-same */
    { "timespec_get", 0 },   /* timespec_get@GLIBC_2.16 forward-same */
    { "tzset", 0 },   /* tzset@GLIBC_2.2.5 forward-same */
    { "utimes", 0 },   /* utimes@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_time_n = sizeof __esn_wire_time / sizeof *__esn_wire_time;

