/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice stdio; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_stdio+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, __asprintf@@GLIBC_2.2.5

	.weak	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_stdio+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, __getdelim@@GLIBC_2.2.5

	.weak	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_stdio+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, asprintf@@GLIBC_2.2.5

	.globl	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_stdio+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, clearerr@@GLIBC_2.2.5

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_stdio+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, clearerr_unlocked@@GLIBC_2.2.5

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_stdio+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, ctermid@@GLIBC_2.2.5

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_stdio+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, cuserid@@GLIBC_2.2.5

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_stdio+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, dprintf@@GLIBC_2.2.5

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_stdio+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, fclose@@GLIBC_2.2.5

	.weak	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_stdio+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, fcloseall@@GLIBC_2.2.5

	.globl	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_stdio+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, fdopen@@GLIBC_2.2.5

	.weak	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_stdio+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, feof@@GLIBC_2.2.5

	.weak	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_stdio+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, feof_unlocked@@GLIBC_2.2.5

	.weak	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_stdio+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, ferror@@GLIBC_2.2.5

	.weak	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_stdio+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, ferror_unlocked@@GLIBC_2.2.5

	.weak	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_stdio+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, fflush@@GLIBC_2.2.5

	.weak	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_stdio+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, fflush_unlocked@@GLIBC_2.2.5

	.weak	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_stdio+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, fgetc@@GLIBC_2.2.5

	.weak	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_stdio+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, fgetc_unlocked@@GLIBC_2.2.5

	.globl	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_stdio+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, fgetpos@@GLIBC_2.2.5

	.globl	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_stdio+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, fgetpos64@@GLIBC_2.2.5

	.weak	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_stdio+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, fgets@@GLIBC_2.2.5

	.weak	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_stdio+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, fgets_unlocked@@GLIBC_2.2.5

	.weak	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_stdio+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, fileno@@GLIBC_2.2.5

	.weak	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_stdio+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, fileno_unlocked@@GLIBC_2.2.5

	.weak	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_stdio+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, flockfile@@GLIBC_2.2.5

	.globl	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_stdio+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, fmemopen@GLIBC_2.2.5

	.globl	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_stdio+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, fmemopen@@GLIBC_2.22

	.globl	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_stdio+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, fopen@@GLIBC_2.2.5

	.weak	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_stdio+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, fopen64@@GLIBC_2.2.5

	.globl	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_stdio+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, fopencookie@@GLIBC_2.2.5

	.globl	w00031
	.type	w00031,@function
w00031:
	jmp	*__esn_wire_stdio+504(%rip)
	.size	w00031, .-w00031
	.symver	w00031, fprintf@@GLIBC_2.2.5

	.globl	w00032
	.type	w00032,@function
w00032:
	jmp	*__esn_wire_stdio+520(%rip)
	.size	w00032, .-w00032
	.symver	w00032, fputc@@GLIBC_2.2.5

	.globl	w00033
	.type	w00033,@function
w00033:
	jmp	*__esn_wire_stdio+536(%rip)
	.size	w00033, .-w00033
	.symver	w00033, fputc_unlocked@@GLIBC_2.2.5

	.weak	w00034
	.type	w00034,@function
w00034:
	jmp	*__esn_wire_stdio+552(%rip)
	.size	w00034, .-w00034
	.symver	w00034, fputs@@GLIBC_2.2.5

	.weak	w00035
	.type	w00035,@function
w00035:
	jmp	*__esn_wire_stdio+568(%rip)
	.size	w00035, .-w00035
	.symver	w00035, fputs_unlocked@@GLIBC_2.2.5

	.weak	w00036
	.type	w00036,@function
w00036:
	jmp	*__esn_wire_stdio+584(%rip)
	.size	w00036, .-w00036
	.symver	w00036, fread@@GLIBC_2.2.5

	.weak	w00037
	.type	w00037,@function
w00037:
	jmp	*__esn_wire_stdio+600(%rip)
	.size	w00037, .-w00037
	.symver	w00037, fread_unlocked@@GLIBC_2.2.5

	.globl	w00038
	.type	w00038,@function
w00038:
	jmp	*__esn_wire_stdio+616(%rip)
	.size	w00038, .-w00038
	.symver	w00038, freopen@@GLIBC_2.2.5

	.globl	w00039
	.type	w00039,@function
w00039:
	jmp	*__esn_wire_stdio+632(%rip)
	.size	w00039, .-w00039
	.symver	w00039, freopen64@@GLIBC_2.2.5

	.globl	w00040
	.type	w00040,@function
w00040:
	jmp	*__esn_wire_stdio+648(%rip)
	.size	w00040, .-w00040
	.symver	w00040, fscanf@@GLIBC_2.2.5

	.globl	w00041
	.type	w00041,@function
w00041:
	jmp	*__esn_wire_stdio+664(%rip)
	.size	w00041, .-w00041
	.symver	w00041, fseek@@GLIBC_2.2.5

	.weak	w00042
	.type	w00042,@function
w00042:
	jmp	*__esn_wire_stdio+680(%rip)
	.size	w00042, .-w00042
	.symver	w00042, fseeko@@GLIBC_2.2.5

	.weak	w00043
	.type	w00043,@function
w00043:
	jmp	*__esn_wire_stdio+696(%rip)
	.size	w00043, .-w00043
	.symver	w00043, fseeko64@@GLIBC_2.2.5

	.globl	w00044
	.type	w00044,@function
w00044:
	jmp	*__esn_wire_stdio+712(%rip)
	.size	w00044, .-w00044
	.symver	w00044, fsetpos@@GLIBC_2.2.5

	.globl	w00045
	.type	w00045,@function
w00045:
	jmp	*__esn_wire_stdio+728(%rip)
	.size	w00045, .-w00045
	.symver	w00045, fsetpos64@@GLIBC_2.2.5

	.weak	w00046
	.type	w00046,@function
w00046:
	jmp	*__esn_wire_stdio+744(%rip)
	.size	w00046, .-w00046
	.symver	w00046, ftell@@GLIBC_2.2.5

	.weak	w00047
	.type	w00047,@function
w00047:
	jmp	*__esn_wire_stdio+760(%rip)
	.size	w00047, .-w00047
	.symver	w00047, ftello@@GLIBC_2.2.5

	.weak	w00048
	.type	w00048,@function
w00048:
	jmp	*__esn_wire_stdio+776(%rip)
	.size	w00048, .-w00048
	.symver	w00048, ftello64@@GLIBC_2.2.5

	.weak	w00049
	.type	w00049,@function
w00049:
	jmp	*__esn_wire_stdio+792(%rip)
	.size	w00049, .-w00049
	.symver	w00049, ftrylockfile@@GLIBC_2.2.5

	.weak	w00050
	.type	w00050,@function
w00050:
	jmp	*__esn_wire_stdio+808(%rip)
	.size	w00050, .-w00050
	.symver	w00050, funlockfile@@GLIBC_2.2.5

	.weak	w00051
	.type	w00051,@function
w00051:
	jmp	*__esn_wire_stdio+824(%rip)
	.size	w00051, .-w00051
	.symver	w00051, fwrite@@GLIBC_2.2.5

	.globl	w00052
	.type	w00052,@function
w00052:
	jmp	*__esn_wire_stdio+840(%rip)
	.size	w00052, .-w00052
	.symver	w00052, fwrite_unlocked@@GLIBC_2.2.5

	.weak	w00053
	.type	w00053,@function
w00053:
	jmp	*__esn_wire_stdio+856(%rip)
	.size	w00053, .-w00053
	.symver	w00053, getc@@GLIBC_2.2.5

	.weak	w00054
	.type	w00054,@function
w00054:
	jmp	*__esn_wire_stdio+872(%rip)
	.size	w00054, .-w00054
	.symver	w00054, getc_unlocked@@GLIBC_2.2.5

	.globl	w00055
	.type	w00055,@function
w00055:
	jmp	*__esn_wire_stdio+888(%rip)
	.size	w00055, .-w00055
	.symver	w00055, getchar@@GLIBC_2.2.5

	.globl	w00056
	.type	w00056,@function
w00056:
	jmp	*__esn_wire_stdio+904(%rip)
	.size	w00056, .-w00056
	.symver	w00056, getchar_unlocked@@GLIBC_2.2.5

	.weak	w00057
	.type	w00057,@function
w00057:
	jmp	*__esn_wire_stdio+920(%rip)
	.size	w00057, .-w00057
	.symver	w00057, getdelim@@GLIBC_2.2.5

	.weak	w00058
	.type	w00058,@function
w00058:
	jmp	*__esn_wire_stdio+936(%rip)
	.size	w00058, .-w00058
	.symver	w00058, getline@@GLIBC_2.2.5

	.globl	w00059
	.type	w00059,@function
w00059:
	jmp	*__esn_wire_stdio+952(%rip)
	.size	w00059, .-w00059
	.symver	w00059, getw@@GLIBC_2.2.5

	.weak	w00060
	.type	w00060,@function
w00060:
	jmp	*__esn_wire_stdio+968(%rip)
	.size	w00060, .-w00060
	.symver	w00060, open_memstream@@GLIBC_2.2.5

	.globl	w00061
	.type	w00061,@function
w00061:
	jmp	*__esn_wire_stdio+984(%rip)
	.size	w00061, .-w00061
	.symver	w00061, pclose@@GLIBC_2.2.5

	.globl	w00062
	.type	w00062,@function
w00062:
	jmp	*__esn_wire_stdio+1000(%rip)
	.size	w00062, .-w00062
	.symver	w00062, perror@@GLIBC_2.2.5

	.globl	w00063
	.type	w00063,@function
w00063:
	jmp	*__esn_wire_stdio+1016(%rip)
	.size	w00063, .-w00063
	.symver	w00063, popen@@GLIBC_2.2.5

	.globl	w00064
	.type	w00064,@function
w00064:
	jmp	*__esn_wire_stdio+1032(%rip)
	.size	w00064, .-w00064
	.symver	w00064, printf@@GLIBC_2.2.5

	.weak	w00065
	.type	w00065,@function
w00065:
	jmp	*__esn_wire_stdio+1048(%rip)
	.size	w00065, .-w00065
	.symver	w00065, putc@@GLIBC_2.2.5

	.weak	w00066
	.type	w00066,@function
w00066:
	jmp	*__esn_wire_stdio+1064(%rip)
	.size	w00066, .-w00066
	.symver	w00066, putc_unlocked@@GLIBC_2.2.5

	.globl	w00067
	.type	w00067,@function
w00067:
	jmp	*__esn_wire_stdio+1080(%rip)
	.size	w00067, .-w00067
	.symver	w00067, putchar@@GLIBC_2.2.5

	.globl	w00068
	.type	w00068,@function
w00068:
	jmp	*__esn_wire_stdio+1096(%rip)
	.size	w00068, .-w00068
	.symver	w00068, putchar_unlocked@@GLIBC_2.2.5

	.weak	w00069
	.type	w00069,@function
w00069:
	jmp	*__esn_wire_stdio+1112(%rip)
	.size	w00069, .-w00069
	.symver	w00069, puts@@GLIBC_2.2.5

	.globl	w00070
	.type	w00070,@function
w00070:
	jmp	*__esn_wire_stdio+1128(%rip)
	.size	w00070, .-w00070
	.symver	w00070, putw@@GLIBC_2.2.5

	.globl	w00071
	.type	w00071,@function
w00071:
	jmp	*__esn_wire_stdio+1144(%rip)
	.size	w00071, .-w00071
	.symver	w00071, remove@@GLIBC_2.2.5

	.globl	w00072
	.type	w00072,@function
w00072:
	jmp	*__esn_wire_stdio+1160(%rip)
	.size	w00072, .-w00072
	.symver	w00072, rename@@GLIBC_2.2.5

	.weak	w00073
	.type	w00073,@function
w00073:
	jmp	*__esn_wire_stdio+1176(%rip)
	.size	w00073, .-w00073
	.symver	w00073, renameat@@GLIBC_2.4

	.globl	w00074
	.type	w00074,@function
w00074:
	jmp	*__esn_wire_stdio+1192(%rip)
	.size	w00074, .-w00074
	.symver	w00074, renameat2@@GLIBC_2.28

	.globl	w00075
	.type	w00075,@function
w00075:
	jmp	*__esn_wire_stdio+1208(%rip)
	.size	w00075, .-w00075
	.symver	w00075, rewind@@GLIBC_2.2.5

	.globl	w00076
	.type	w00076,@function
w00076:
	jmp	*__esn_wire_stdio+1224(%rip)
	.size	w00076, .-w00076
	.symver	w00076, scanf@@GLIBC_2.2.5

	.globl	w00077
	.type	w00077,@function
w00077:
	jmp	*__esn_wire_stdio+1240(%rip)
	.size	w00077, .-w00077
	.symver	w00077, setbuf@@GLIBC_2.2.5

	.weak	w00078
	.type	w00078,@function
w00078:
	jmp	*__esn_wire_stdio+1256(%rip)
	.size	w00078, .-w00078
	.symver	w00078, setbuffer@@GLIBC_2.2.5

	.globl	w00079
	.type	w00079,@function
w00079:
	jmp	*__esn_wire_stdio+1272(%rip)
	.size	w00079, .-w00079
	.symver	w00079, setlinebuf@@GLIBC_2.2.5

	.weak	w00080
	.type	w00080,@function
w00080:
	jmp	*__esn_wire_stdio+1288(%rip)
	.size	w00080, .-w00080
	.symver	w00080, setvbuf@@GLIBC_2.2.5

	.weak	w00081
	.type	w00081,@function
w00081:
	jmp	*__esn_wire_stdio+1304(%rip)
	.size	w00081, .-w00081
	.symver	w00081, snprintf@@GLIBC_2.2.5

	.globl	w00082
	.type	w00082,@function
w00082:
	jmp	*__esn_wire_stdio+1320(%rip)
	.size	w00082, .-w00082
	.symver	w00082, sprintf@@GLIBC_2.2.5

	.globl	w00083
	.type	w00083,@function
w00083:
	jmp	*__esn_wire_stdio+1336(%rip)
	.size	w00083, .-w00083
	.symver	w00083, sscanf@@GLIBC_2.2.5

	.globl	w00084
	.type	w00084,@function
w00084:
	jmp	*__esn_wire_stdio+1352(%rip)
	.size	w00084, .-w00084
	.symver	w00084, tempnam@@GLIBC_2.2.5

	.globl	w00085
	.type	w00085,@function
w00085:
	jmp	*__esn_wire_stdio+1368(%rip)
	.size	w00085, .-w00085
	.symver	w00085, tmpfile@@GLIBC_2.2.5

	.weak	w00086
	.type	w00086,@function
w00086:
	jmp	*__esn_wire_stdio+1384(%rip)
	.size	w00086, .-w00086
	.symver	w00086, tmpfile64@@GLIBC_2.2.5

	.globl	w00087
	.type	w00087,@function
w00087:
	jmp	*__esn_wire_stdio+1400(%rip)
	.size	w00087, .-w00087
	.symver	w00087, tmpnam@@GLIBC_2.2.5

	.weak	w00088
	.type	w00088,@function
w00088:
	jmp	*__esn_wire_stdio+1416(%rip)
	.size	w00088, .-w00088
	.symver	w00088, ungetc@@GLIBC_2.2.5

	.weak	w00089
	.type	w00089,@function
w00089:
	jmp	*__esn_wire_stdio+1432(%rip)
	.size	w00089, .-w00089
	.symver	w00089, vasprintf@@GLIBC_2.2.5

	.weak	w00090
	.type	w00090,@function
w00090:
	jmp	*__esn_wire_stdio+1448(%rip)
	.size	w00090, .-w00090
	.symver	w00090, vdprintf@@GLIBC_2.2.5

	.globl	w00091
	.type	w00091,@function
w00091:
	jmp	*__esn_wire_stdio+1464(%rip)
	.size	w00091, .-w00091
	.symver	w00091, vfprintf@@GLIBC_2.2.5

	.weak	w00092
	.type	w00092,@function
w00092:
	jmp	*__esn_wire_stdio+1480(%rip)
	.size	w00092, .-w00092
	.symver	w00092, vfscanf@@GLIBC_2.2.5

	.globl	w00093
	.type	w00093,@function
w00093:
	jmp	*__esn_wire_stdio+1496(%rip)
	.size	w00093, .-w00093
	.symver	w00093, vprintf@@GLIBC_2.2.5

	.weak	w00094
	.type	w00094,@function
w00094:
	jmp	*__esn_wire_stdio+1512(%rip)
	.size	w00094, .-w00094
	.symver	w00094, vscanf@@GLIBC_2.2.5

	.weak	w00095
	.type	w00095,@function
w00095:
	jmp	*__esn_wire_stdio+1528(%rip)
	.size	w00095, .-w00095
	.symver	w00095, vsnprintf@@GLIBC_2.2.5

	.weak	w00096
	.type	w00096,@function
w00096:
	jmp	*__esn_wire_stdio+1544(%rip)
	.size	w00096, .-w00096
	.symver	w00096, vsprintf@@GLIBC_2.2.5

	.weak	w00097
	.type	w00097,@function
w00097:
	jmp	*__esn_wire_stdio+1560(%rip)
	.size	w00097, .-w00097
	.symver	w00097, vsscanf@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
