/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice io-mux; do not edit */
	.text
	.weak	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_io_mux+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, poll@@GLIBC_2.2.5

	.globl	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_io_mux+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, ppoll@@GLIBC_2.4

	.weak	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_io_mux+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, pselect@@GLIBC_2.2.5

	.weak	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_io_mux+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, select@@GLIBC_2.2.5

	.globl	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_io_mux+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, signalfd@@GLIBC_2.7

	.globl	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_io_mux+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, timerfd_create@@GLIBC_2.8

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_io_mux+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, timerfd_gettime@@GLIBC_2.8

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_io_mux+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, timerfd_settime@@GLIBC_2.8

	.section	.note.GNU-stack,"",@progbits
