/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice string; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_string[] = {
    { "argz_count", 0 },   /* __argz_count@GLIBC_2.2.5 forward-alias */
    { "argz_next", 0 },   /* __argz_next@GLIBC_2.2.5 forward-alias */
    { "argz_stringify", 0 },   /* __argz_stringify@GLIBC_2.2.5 forward-alias */
    { "__errno_location", 0 },   /* __errno_location@GLIBC_2.2.5 shim */
    { "strtok_r", 0 },   /* __strtok_r@GLIBC_2.2.5 forward-alias */
    { "argz_add", 0 },   /* argz_add@GLIBC_2.2.5 forward-same */
    { "argz_add_sep", 0 },   /* argz_add_sep@GLIBC_2.2.5 forward-same */
    { "argz_append", 0 },   /* argz_append@GLIBC_2.2.5 forward-same */
    { "argz_count", 0 },   /* argz_count@GLIBC_2.2.5 forward-same */
    { "argz_create", 0 },   /* argz_create@GLIBC_2.2.5 forward-same */
    { "argz_create_sep", 0 },   /* argz_create_sep@GLIBC_2.2.5 forward-same */
    { "argz_delete", 0 },   /* argz_delete@GLIBC_2.2.5 forward-same */
    { "argz_extract", 0 },   /* argz_extract@GLIBC_2.2.5 forward-same */
    { "argz_insert", 0 },   /* argz_insert@GLIBC_2.2.5 forward-same */
    { "argz_next", 0 },   /* argz_next@GLIBC_2.2.5 forward-same */
    { "argz_replace", 0 },   /* argz_replace@GLIBC_2.2.5 forward-same */
    { "argz_stringify", 0 },   /* argz_stringify@GLIBC_2.2.5 forward-same */
    { "basename", 0 },   /* basename@GLIBC_2.2.5 forward-same */
    { "bcopy", 0 },   /* bcopy@GLIBC_2.2.5 forward-same */
    { "envz_add", 0 },   /* envz_add@GLIBC_2.2.5 forward-same */
    { "envz_entry", 0 },   /* envz_entry@GLIBC_2.2.5 forward-same */
    { "envz_get", 0 },   /* envz_get@GLIBC_2.2.5 forward-same */
    { "envz_merge", 0 },   /* envz_merge@GLIBC_2.2.5 forward-same */
    { "envz_remove", 0 },   /* envz_remove@GLIBC_2.2.5 forward-same */
    { "envz_strip", 0 },   /* envz_strip@GLIBC_2.2.5 forward-same */
    { "explicit_bzero", 0 },   /* explicit_bzero@GLIBC_2.25 forward-same */
    { "ffs", 0 },   /* ffs@GLIBC_2.2.5 forward-same */
    { "ffsl", 0 },   /* ffsl@GLIBC_2.2.5 forward-same */
    { "ffsll", 0 },   /* ffsll@GLIBC_2.2.5 forward-same */
    { "memccpy", 0 },   /* memccpy@GLIBC_2.2.5 forward-same */
    { "memcpy", 0 },   /* memcpy@GLIBC_2.2.5 forward-same */
    { "memmem", 0 },   /* memmem@GLIBC_2.2.5 forward-same */
    { "strcasestr", 0 },   /* strcasestr@GLIBC_2.2.5 forward-same */
    { "strcoll", 0 },   /* strcoll@GLIBC_2.2.5 forward-same */
    { "strcoll_l", 0 },   /* strcoll_l@GLIBC_2.3 forward-same */
    { "strdup", 0 },   /* strdup@GLIBC_2.2.5 forward-same */
    { "strerror", 0 },   /* strerror@GLIBC_2.2.5 forward-same */
    { "strerror_l", 0 },   /* strerror_l@GLIBC_2.6 forward-same */
    { "strerror_r", 0 },   /* strerror_r@GLIBC_2.2.5 forward-same */
    { "strndup", 0 },   /* strndup@GLIBC_2.2.5 forward-same */
    { "strsep", 0 },   /* strsep@GLIBC_2.2.5 forward-same */
    { "strsignal", 0 },   /* strsignal@GLIBC_2.2.5 forward-same */
    { "strtok", 0 },   /* strtok@GLIBC_2.2.5 forward-same */
    { "strtok_r", 0 },   /* strtok_r@GLIBC_2.2.5 forward-same */
    { "strverscmp", 0 },   /* strverscmp@GLIBC_2.2.5 forward-same */
    { "strxfrm", 0 },   /* strxfrm@GLIBC_2.2.5 forward-same */
    { "strxfrm_l", 0 },   /* strxfrm_l@GLIBC_2.3 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_string_n = sizeof __esn_wire_string / sizeof *__esn_wire_string;

