/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice system; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_system[] = {
    { "get_avphys_pages", 0 },   /* get_avphys_pages@GLIBC_2.2.5 forward-same */
    { "get_nprocs", 0 },   /* get_nprocs@GLIBC_2.2.5 forward-same */
    { "get_nprocs_conf", 0 },   /* get_nprocs_conf@GLIBC_2.2.5 forward-same */
    { "get_phys_pages", 0 },   /* get_phys_pages@GLIBC_2.2.5 forward-same */
    { "sysinfo", 0 },   /* sysinfo@GLIBC_2.2.5 forward-same */
    { "uname", 0 },   /* uname@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_system_n = sizeof __esn_wire_system / sizeof *__esn_wire_system;

