/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice wchar; do not edit */
	.text
	.globl	w00000
	.type	w00000,@function
w00000:
	jmp	*__esn_wire_wchar+8(%rip)
	.size	w00000, .-w00000
	.symver	w00000, __mbrlen@@GLIBC_2.2.5

	.weak	w00001
	.type	w00001,@function
w00001:
	jmp	*__esn_wire_wchar+24(%rip)
	.size	w00001, .-w00001
	.symver	w00001, btowc@@GLIBC_2.2.5

	.globl	w00002
	.type	w00002,@function
w00002:
	jmp	*__esn_wire_wchar+40(%rip)
	.size	w00002, .-w00002
	.symver	w00002, c16rtomb@@GLIBC_2.16

	.weak	w00003
	.type	w00003,@function
w00003:
	jmp	*__esn_wire_wchar+56(%rip)
	.size	w00003, .-w00003
	.symver	w00003, c32rtomb@@GLIBC_2.16

	.weak	w00004
	.type	w00004,@function
w00004:
	jmp	*__esn_wire_wchar+72(%rip)
	.size	w00004, .-w00004
	.symver	w00004, fgetwc@@GLIBC_2.2.5

	.weak	w00005
	.type	w00005,@function
w00005:
	jmp	*__esn_wire_wchar+88(%rip)
	.size	w00005, .-w00005
	.symver	w00005, fgetwc_unlocked@@GLIBC_2.2.5

	.globl	w00006
	.type	w00006,@function
w00006:
	jmp	*__esn_wire_wchar+104(%rip)
	.size	w00006, .-w00006
	.symver	w00006, fgetws@@GLIBC_2.2.5

	.globl	w00007
	.type	w00007,@function
w00007:
	jmp	*__esn_wire_wchar+120(%rip)
	.size	w00007, .-w00007
	.symver	w00007, fgetws_unlocked@@GLIBC_2.2.5

	.globl	w00008
	.type	w00008,@function
w00008:
	jmp	*__esn_wire_wchar+136(%rip)
	.size	w00008, .-w00008
	.symver	w00008, fputwc@@GLIBC_2.2.5

	.globl	w00009
	.type	w00009,@function
w00009:
	jmp	*__esn_wire_wchar+152(%rip)
	.size	w00009, .-w00009
	.symver	w00009, fputwc_unlocked@@GLIBC_2.2.5

	.globl	w00010
	.type	w00010,@function
w00010:
	jmp	*__esn_wire_wchar+168(%rip)
	.size	w00010, .-w00010
	.symver	w00010, fputws@@GLIBC_2.2.5

	.globl	w00011
	.type	w00011,@function
w00011:
	jmp	*__esn_wire_wchar+184(%rip)
	.size	w00011, .-w00011
	.symver	w00011, fputws_unlocked@@GLIBC_2.2.5

	.globl	w00012
	.type	w00012,@function
w00012:
	jmp	*__esn_wire_wchar+200(%rip)
	.size	w00012, .-w00012
	.symver	w00012, fwide@@GLIBC_2.2.5

	.weak	w00013
	.type	w00013,@function
w00013:
	jmp	*__esn_wire_wchar+216(%rip)
	.size	w00013, .-w00013
	.symver	w00013, fwprintf@@GLIBC_2.2.5

	.globl	w00014
	.type	w00014,@function
w00014:
	jmp	*__esn_wire_wchar+232(%rip)
	.size	w00014, .-w00014
	.symver	w00014, fwscanf@@GLIBC_2.2.5

	.weak	w00015
	.type	w00015,@function
w00015:
	jmp	*__esn_wire_wchar+248(%rip)
	.size	w00015, .-w00015
	.symver	w00015, getwc@@GLIBC_2.2.5

	.weak	w00016
	.type	w00016,@function
w00016:
	jmp	*__esn_wire_wchar+264(%rip)
	.size	w00016, .-w00016
	.symver	w00016, getwc_unlocked@@GLIBC_2.2.5

	.globl	w00017
	.type	w00017,@function
w00017:
	jmp	*__esn_wire_wchar+280(%rip)
	.size	w00017, .-w00017
	.symver	w00017, getwchar@@GLIBC_2.2.5

	.globl	w00018
	.type	w00018,@function
w00018:
	jmp	*__esn_wire_wchar+296(%rip)
	.size	w00018, .-w00018
	.symver	w00018, getwchar_unlocked@@GLIBC_2.2.5

	.weak	w00019
	.type	w00019,@function
w00019:
	jmp	*__esn_wire_wchar+312(%rip)
	.size	w00019, .-w00019
	.symver	w00019, mbrlen@@GLIBC_2.2.5

	.globl	w00020
	.type	w00020,@function
w00020:
	jmp	*__esn_wire_wchar+328(%rip)
	.size	w00020, .-w00020
	.symver	w00020, mbrtoc16@@GLIBC_2.16

	.weak	w00021
	.type	w00021,@function
w00021:
	jmp	*__esn_wire_wchar+344(%rip)
	.size	w00021, .-w00021
	.symver	w00021, mbrtoc32@@GLIBC_2.16

	.weak	w00022
	.type	w00022,@function
w00022:
	jmp	*__esn_wire_wchar+360(%rip)
	.size	w00022, .-w00022
	.symver	w00022, mbrtowc@@GLIBC_2.2.5

	.weak	w00023
	.type	w00023,@function
w00023:
	jmp	*__esn_wire_wchar+376(%rip)
	.size	w00023, .-w00023
	.symver	w00023, mbsinit@@GLIBC_2.2.5

	.weak	w00024
	.type	w00024,@function
w00024:
	jmp	*__esn_wire_wchar+392(%rip)
	.size	w00024, .-w00024
	.symver	w00024, mbsnrtowcs@@GLIBC_2.2.5

	.weak	w00025
	.type	w00025,@function
w00025:
	jmp	*__esn_wire_wchar+408(%rip)
	.size	w00025, .-w00025
	.symver	w00025, mbsrtowcs@@GLIBC_2.2.5

	.globl	w00026
	.type	w00026,@function
w00026:
	jmp	*__esn_wire_wchar+424(%rip)
	.size	w00026, .-w00026
	.symver	w00026, open_wmemstream@@GLIBC_2.4

	.globl	w00027
	.type	w00027,@function
w00027:
	jmp	*__esn_wire_wchar+440(%rip)
	.size	w00027, .-w00027
	.symver	w00027, putwc@@GLIBC_2.2.5

	.globl	w00028
	.type	w00028,@function
w00028:
	jmp	*__esn_wire_wchar+456(%rip)
	.size	w00028, .-w00028
	.symver	w00028, putwc_unlocked@@GLIBC_2.2.5

	.globl	w00029
	.type	w00029,@function
w00029:
	jmp	*__esn_wire_wchar+472(%rip)
	.size	w00029, .-w00029
	.symver	w00029, putwchar@@GLIBC_2.2.5

	.globl	w00030
	.type	w00030,@function
w00030:
	jmp	*__esn_wire_wchar+488(%rip)
	.size	w00030, .-w00030
	.symver	w00030, putwchar_unlocked@@GLIBC_2.2.5

	.globl	w00031
	.type	w00031,@function
w00031:
	jmp	*__esn_wire_wchar+504(%rip)
	.size	w00031, .-w00031
	.symver	w00031, swprintf@@GLIBC_2.2.5

	.globl	w00032
	.type	w00032,@function
w00032:
	jmp	*__esn_wire_wchar+520(%rip)
	.size	w00032, .-w00032
	.symver	w00032, swscanf@@GLIBC_2.2.5

	.globl	w00033
	.type	w00033,@function
w00033:
	jmp	*__esn_wire_wchar+536(%rip)
	.size	w00033, .-w00033
	.symver	w00033, ungetwc@@GLIBC_2.2.5

	.weak	w00034
	.type	w00034,@function
w00034:
	jmp	*__esn_wire_wchar+552(%rip)
	.size	w00034, .-w00034
	.symver	w00034, vfwprintf@@GLIBC_2.2.5

	.weak	w00035
	.type	w00035,@function
w00035:
	jmp	*__esn_wire_wchar+568(%rip)
	.size	w00035, .-w00035
	.symver	w00035, vfwscanf@@GLIBC_2.2.5

	.weak	w00036
	.type	w00036,@function
w00036:
	jmp	*__esn_wire_wchar+584(%rip)
	.size	w00036, .-w00036
	.symver	w00036, vswprintf@@GLIBC_2.2.5

	.globl	w00037
	.type	w00037,@function
w00037:
	jmp	*__esn_wire_wchar+600(%rip)
	.size	w00037, .-w00037
	.symver	w00037, vswscanf@@GLIBC_2.2.5

	.globl	w00038
	.type	w00038,@function
w00038:
	jmp	*__esn_wire_wchar+616(%rip)
	.size	w00038, .-w00038
	.symver	w00038, vwprintf@@GLIBC_2.2.5

	.globl	w00039
	.type	w00039,@function
w00039:
	jmp	*__esn_wire_wchar+632(%rip)
	.size	w00039, .-w00039
	.symver	w00039, vwscanf@@GLIBC_2.2.5

	.weak	w00040
	.type	w00040,@function
w00040:
	jmp	*__esn_wire_wchar+648(%rip)
	.size	w00040, .-w00040
	.symver	w00040, wcpcpy@@GLIBC_2.2.5

	.weak	w00041
	.type	w00041,@function
w00041:
	jmp	*__esn_wire_wchar+664(%rip)
	.size	w00041, .-w00041
	.symver	w00041, wcpncpy@@GLIBC_2.2.5

	.weak	w00042
	.type	w00042,@function
w00042:
	jmp	*__esn_wire_wchar+680(%rip)
	.size	w00042, .-w00042
	.symver	w00042, wcrtomb@@GLIBC_2.2.5

	.weak	w00043
	.type	w00043,@function
w00043:
	jmp	*__esn_wire_wchar+696(%rip)
	.size	w00043, .-w00043
	.symver	w00043, wcscasecmp@@GLIBC_2.2.5

	.weak	w00044
	.type	w00044,@function
w00044:
	jmp	*__esn_wire_wchar+712(%rip)
	.size	w00044, .-w00044
	.symver	w00044, wcscasecmp_l@@GLIBC_2.3

	.weak	w00045
	.type	w00045,@function
w00045:
	jmp	*__esn_wire_wchar+728(%rip)
	.size	w00045, .-w00045
	.symver	w00045, wcscat@@GLIBC_2.2.5

	.weak	w00046
	.type	w00046,@function
w00046:
	jmp	*__esn_wire_wchar+744(%rip)
	.size	w00046, .-w00046
	.symver	w00046, wcscoll@@GLIBC_2.2.5

	.weak	w00047
	.type	w00047,@function
w00047:
	jmp	*__esn_wire_wchar+760(%rip)
	.size	w00047, .-w00047
	.symver	w00047, wcscoll_l@@GLIBC_2.3

	.globl	w00048
	.type	w00048,@function
w00048:
	jmp	*__esn_wire_wchar+776(%rip)
	.size	w00048, .-w00048
	.symver	w00048, wcscspn@@GLIBC_2.2.5

	.globl	w00049
	.type	w00049,@function
w00049:
	jmp	*__esn_wire_wchar+792(%rip)
	.size	w00049, .-w00049
	.symver	w00049, wcsdup@@GLIBC_2.2.5

	.globl	w00050
	.type	w00050,@function
w00050:
	jmp	*__esn_wire_wchar+808(%rip)
	.size	w00050, .-w00050
	.symver	w00050, wcsftime@@GLIBC_2.2.5

	.weak	w00051
	.type	w00051,@function
w00051:
	jmp	*__esn_wire_wchar+824(%rip)
	.size	w00051, .-w00051
	.symver	w00051, wcsftime_l@@GLIBC_2.3

	.weak	w00052
	.type	w00052,@function
w00052:
	jmp	*__esn_wire_wchar+840(%rip)
	.size	w00052, .-w00052
	.symver	w00052, wcsncasecmp@@GLIBC_2.2.5

	.weak	w00053
	.type	w00053,@function
w00053:
	jmp	*__esn_wire_wchar+856(%rip)
	.size	w00053, .-w00053
	.symver	w00053, wcsncasecmp_l@@GLIBC_2.3

	.globl	w00054
	.type	w00054,@function
w00054:
	jmp	*__esn_wire_wchar+872(%rip)
	.size	w00054, .-w00054
	.symver	w00054, wcsncat@@GLIBC_2.2.5

	.weak	w00055
	.type	w00055,@function
w00055:
	jmp	*__esn_wire_wchar+888(%rip)
	.size	w00055, .-w00055
	.symver	w00055, wcsncpy@@GLIBC_2.2.5

	.weak	w00056
	.type	w00056,@function
w00056:
	jmp	*__esn_wire_wchar+904(%rip)
	.size	w00056, .-w00056
	.symver	w00056, wcsnrtombs@@GLIBC_2.2.5

	.globl	w00057
	.type	w00057,@function
w00057:
	jmp	*__esn_wire_wchar+920(%rip)
	.size	w00057, .-w00057
	.symver	w00057, wcspbrk@@GLIBC_2.2.5

	.weak	w00058
	.type	w00058,@function
w00058:
	jmp	*__esn_wire_wchar+936(%rip)
	.size	w00058, .-w00058
	.symver	w00058, wcsrtombs@@GLIBC_2.2.5

	.globl	w00059
	.type	w00059,@function
w00059:
	jmp	*__esn_wire_wchar+952(%rip)
	.size	w00059, .-w00059
	.symver	w00059, wcsspn@@GLIBC_2.2.5

	.globl	w00060
	.type	w00060,@function
w00060:
	jmp	*__esn_wire_wchar+968(%rip)
	.size	w00060, .-w00060
	.symver	w00060, wcsstr@@GLIBC_2.2.5

	.globl	w00061
	.type	w00061,@function
w00061:
	jmp	*__esn_wire_wchar+984(%rip)
	.size	w00061, .-w00061
	.symver	w00061, wcstod@@GLIBC_2.2.5

	.weak	w00062
	.type	w00062,@function
w00062:
	jmp	*__esn_wire_wchar+1000(%rip)
	.size	w00062, .-w00062
	.symver	w00062, wcstod_l@@GLIBC_2.3

	.globl	w00063
	.type	w00063,@function
w00063:
	jmp	*__esn_wire_wchar+1016(%rip)
	.size	w00063, .-w00063
	.symver	w00063, wcstof@@GLIBC_2.2.5

	.weak	w00064
	.type	w00064,@function
w00064:
	jmp	*__esn_wire_wchar+1032(%rip)
	.size	w00064, .-w00064
	.symver	w00064, wcstof64@@GLIBC_2.27

	.weak	w00065
	.type	w00065,@function
w00065:
	jmp	*__esn_wire_wchar+1048(%rip)
	.size	w00065, .-w00065
	.symver	w00065, wcstof_l@@GLIBC_2.3

	.globl	w00066
	.type	w00066,@function
w00066:
	jmp	*__esn_wire_wchar+1064(%rip)
	.size	w00066, .-w00066
	.symver	w00066, wcstok@@GLIBC_2.2.5

	.weak	w00067
	.type	w00067,@function
w00067:
	jmp	*__esn_wire_wchar+1080(%rip)
	.size	w00067, .-w00067
	.symver	w00067, wcstol@@GLIBC_2.2.5

	.weak	w00068
	.type	w00068,@function
w00068:
	jmp	*__esn_wire_wchar+1096(%rip)
	.size	w00068, .-w00068
	.symver	w00068, wcstol_l@@GLIBC_2.3

	.globl	w00069
	.type	w00069,@function
w00069:
	jmp	*__esn_wire_wchar+1112(%rip)
	.size	w00069, .-w00069
	.symver	w00069, wcstold@@GLIBC_2.2.5

	.weak	w00070
	.type	w00070,@function
w00070:
	jmp	*__esn_wire_wchar+1128(%rip)
	.size	w00070, .-w00070
	.symver	w00070, wcstold_l@@GLIBC_2.3

	.weak	w00071
	.type	w00071,@function
w00071:
	jmp	*__esn_wire_wchar+1144(%rip)
	.size	w00071, .-w00071
	.symver	w00071, wcstoll@@GLIBC_2.2.5

	.weak	w00072
	.type	w00072,@function
w00072:
	jmp	*__esn_wire_wchar+1160(%rip)
	.size	w00072, .-w00072
	.symver	w00072, wcstoll_l@@GLIBC_2.3

	.weak	w00073
	.type	w00073,@function
w00073:
	jmp	*__esn_wire_wchar+1176(%rip)
	.size	w00073, .-w00073
	.symver	w00073, wcstoul@@GLIBC_2.2.5

	.weak	w00074
	.type	w00074,@function
w00074:
	jmp	*__esn_wire_wchar+1192(%rip)
	.size	w00074, .-w00074
	.symver	w00074, wcstoul_l@@GLIBC_2.3

	.weak	w00075
	.type	w00075,@function
w00075:
	jmp	*__esn_wire_wchar+1208(%rip)
	.size	w00075, .-w00075
	.symver	w00075, wcstoull@@GLIBC_2.2.5

	.weak	w00076
	.type	w00076,@function
w00076:
	jmp	*__esn_wire_wchar+1224(%rip)
	.size	w00076, .-w00076
	.symver	w00076, wcstoull_l@@GLIBC_2.3

	.globl	w00077
	.type	w00077,@function
w00077:
	jmp	*__esn_wire_wchar+1240(%rip)
	.size	w00077, .-w00077
	.symver	w00077, wcswidth@@GLIBC_2.2.5

	.globl	w00078
	.type	w00078,@function
w00078:
	jmp	*__esn_wire_wchar+1256(%rip)
	.size	w00078, .-w00078
	.symver	w00078, wcsxfrm@@GLIBC_2.2.5

	.weak	w00079
	.type	w00079,@function
w00079:
	jmp	*__esn_wire_wchar+1272(%rip)
	.size	w00079, .-w00079
	.symver	w00079, wcsxfrm_l@@GLIBC_2.3

	.globl	w00080
	.type	w00080,@function
w00080:
	jmp	*__esn_wire_wchar+1288(%rip)
	.size	w00080, .-w00080
	.symver	w00080, wctob@@GLIBC_2.2.5

	.globl	w00081
	.type	w00081,@function
w00081:
	jmp	*__esn_wire_wchar+1304(%rip)
	.size	w00081, .-w00081
	.symver	w00081, wcwidth@@GLIBC_2.2.5

	.weak	w00082
	.type	w00082,@function
w00082:
	jmp	*__esn_wire_wchar+1320(%rip)
	.size	w00082, .-w00082
	.symver	w00082, wmemcpy@@GLIBC_2.2.5

	.weak	w00083
	.type	w00083,@function
w00083:
	jmp	*__esn_wire_wchar+1336(%rip)
	.size	w00083, .-w00083
	.symver	w00083, wmemmove@@GLIBC_2.2.5

	.weak	w00084
	.type	w00084,@function
w00084:
	jmp	*__esn_wire_wchar+1352(%rip)
	.size	w00084, .-w00084
	.symver	w00084, wmempcpy@@GLIBC_2.2.5

	.globl	w00085
	.type	w00085,@function
w00085:
	jmp	*__esn_wire_wchar+1368(%rip)
	.size	w00085, .-w00085
	.symver	w00085, wprintf@@GLIBC_2.2.5

	.globl	w00086
	.type	w00086,@function
w00086:
	jmp	*__esn_wire_wchar+1384(%rip)
	.size	w00086, .-w00086
	.symver	w00086, wscanf@@GLIBC_2.2.5

	.section	.note.GNU-stack,"",@progbits
