/* generated by gen-wire.py from fwd.tsv + symbol-slice.tsv, slice syslog; do not edit */
#include "wire.h"

ESN_WIRE_LOCAL struct esn_wire_ent __esn_wire_syslog[] = {
    { "closelog", 0 },   /* closelog@GLIBC_2.2.5 forward-same */
    { "openlog", 0 },   /* openlog@GLIBC_2.2.5 forward-same */
    { "setlogmask", 0 },   /* setlogmask@GLIBC_2.2.5 forward-same */
    { "syslog", 0 },   /* syslog@GLIBC_2.2.5 forward-same */
    { "vsyslog", 0 },   /* vsyslog@GLIBC_2.2.5 forward-same */
};

ESN_WIRE_LOCAL const unsigned long __esn_wire_syslog_n = sizeof __esn_wire_syslog / sizeof *__esn_wire_syslog;

