/* Generated by gen-xlat.py from WP-55's tables -- do not edit. */
#ifndef ESN_XLAT_CORE_H
#define ESN_XLAT_CORE_H

int __esn_errno_up(int v);
int __esn_errno_down(int v);
int __esn_signal_up(int v);
int __esn_signal_down(int v);

#endif
